In [3]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/imagined_speech/gpt_words_5/alpha_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('alpha_repeat-1', 'WER'): np.float64(1.704767221094964), ('alpha_repeat-1', 'BLEU'): np.float64(1.7702071204224945), ('alpha_repeat-1', 'METEOR'): np.float64(1.0183319350579307), ('alpha_repeat-1', 'BERT'): np.float32(2.8672938)}

In [4]:
window_zscores = {'gpt_layer': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for gpt_layer in [3,4,5,8,10]:
    for task in ['alpha_repeat-1']:
        scores = np.load(f'scores/S1/imagined_speech/gpt_words_{gpt_layer}/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['gpt_layer'].append(gpt_layer)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'gpt_layer': [3, 4, 5, 8, 10],
 'WER': [array([ 1.69808573,  1.38775688,  1.67618205,  1.585472  ,  2.07433026,
          2.12003682,  2.17737349,  1.35443391,  1.96127249, -0.03419428,
          1.4057339 ,  0.60253839,  0.91107536,  1.30702858,  0.94210129,
          2.08681939,  1.74927147,  1.10228352,  1.87232484,  1.10833761,
          1.16980045,  1.94580336,  1.54647383,  0.89301756,  1.08875183,
          1.63041194,  1.67835275,  2.21474418,  2.62475604,  2.75489   ,
          2.93921443,  2.97099294,  2.97968115,  3.17031994,  3.64385924,
          2.17547276,  0.62178464,  0.62662831,  0.53665631,  0.64655087,
          0.59646131]),
  array([ 3.11931129e-16, -4.30414027e-01, -8.21994937e-01, -5.32362316e-02,
          4.64056150e-01,  4.69522575e-01,  5.41676263e-01,  5.79982503e-01,
         -4.45849264e-01, -8.55027539e-01,  4.42524676e-01, -2.17194657e-01,
          9.60185512e-02, -2.90502645e-01,  1.18236962e-01, -4.55169639e-02,
          4.23338246e-01,  4.31988660e-01,  4.89476370e-01,  5.26907309e-01,
          5.67787244e-01, -9.90727296e-02,  2.02877498e-01,  2.79002620e-01,
          5.04495508e-01,  1.24471748e+00,  1.18975364e+00,  8.63788073e-01,
          1.13184575e+00,  4.15110949e-01, -2.88920920e-01, -3.08565811e-01,
          4.19119684e-01,  1.56327264e+00,  1.91666667e+00,  1.41596173e+00,
          7.67199260e-01,  7.52494744e-01,  1.67694281e+00,  1.82069339e+00,
          1.64974846e+00]),
  array([ 1.80435178,  0.39458176,  0.7553415 ,  0.65794351,  1.1450376 ,
          0.40872733,  1.1891742 ,  1.95762043,  0.8796883 ,  1.39007397,
          1.05956781,  1.03223887,  0.67617003,  1.04232344,  0.7667776 ,
          1.21165486,  1.6068432 ,  1.7444016 ,  2.3785895 ,  1.65056143,
          1.02012571,  1.24973367,  0.87942521,  0.88902428,  1.09511849,
          0.2549425 ,  0.29451819, -0.83297723,  0.14611468,  1.01485667,
          0.40168006,  0.42833926,  0.27511051,  1.47019011,  1.73797237,
          2.00656433,  1.32424345,  1.44767558,  0.59966694,  0.72514339,
          1.56436002]),
  array([-1.10687899, -1.41054884, -0.09980612, -0.11341835,  0.37007763,
         -0.35263975, -0.3274685 , -0.31330418,  0.27837294, -0.09912279,
          1.39594036,  1.36159942,  0.81845243,  0.45922626,  0.18464626,
         -0.04266291,  1.17038939,  0.56385146,  0.56767024,  0.57692013,
          0.59727689,  0.6713122 ,  0.24854791,  0.26759213,  0.39359017,
          1.07685674,  1.06879239,  0.69448679,  0.91569387,  0.9165204 ,
          0.36936949,  0.33018379,  0.9551091 ,  1.29248607,  1.50493678,
          1.14358388,  0.50607857,  0.57726705, -0.36499476, -0.24312732,
         -0.27068147]),
  array([ 0.70118773,  0.38386857,  0.6997037 ,  0.63997033,  0.34823663,
          0.39934853,  0.49224944, -0.23558761,  1.06731279,  0.74491905,
         -0.18638031,  1.37773842,  1.71504473,  2.11661612,  2.56334977,
          2.93601022,  2.63982538,  2.71008688,  2.93666484,  2.86266266,
          2.07258612,  2.12597724,  1.92681214,  1.03248127,  0.52368224,
          1.1940707 ,  1.27086241,  0.77705279,  1.77181739,  1.78736566,
          1.9206153 ,  1.96688878,  1.03161236,  2.86875489,  2.2517923 ,
          1.82121221,  2.85037584,  2.09079616,  0.51048259,  0.56197119,
          0.61428707])],
 'BLEU': [array([-0.27001006, -0.25807382, -0.49262311, -0.8134993 , -0.46979618,
          0.09354691,  0.76316771,  0.84269911,  0.96166192,  1.4114672 ,
          1.78257892,  1.6568799 ,  1.49129654,  1.80156908,  2.04109653,
          2.84435267,  2.72466377,  1.9939792 ,  1.58378699,  1.10347207,
          1.22736361,  1.25144237,  1.3565098 ,  0.69972741,  0.9814241 ,
          1.51014668,  1.60613338,  2.80654168,  2.78463245,  2.15198565,
          2.71052987,  2.62945683,  2.75423405,  3.12642343,  3.44596121,
          2.57295503,  2.30434386,  2.48715588,  2.9276197 ,  2.18407073,
          1.66339533]),
  array([-0.71106344, -1.00728351, -0.53917838, -0.88917955, -0.92865417,
         -0.70757539, -0.68837461, -0.54009352, -0.11775271, -0.34915528,
         -0.23678147, -0.03446278, -0.23890882,  0.07494018, -0.45278612,
         -0.22626916,  0.16018217,  0.69306549,  0.75951185,  0.33349364,
         -0.50864938, -0.41274998, -1.50033889, -1.10539859, -1.35350594,
         -0.6474447 , -0.53357838, -0.54640997, -0.06886069, -0.04588796,
          0.32226194,  0.23015297,  0.05423483,  0.65788347,  0.98953296,
          0.70626704,  0.87686435,  1.03214737,  1.38239376,  1.40619538,
          1.68468818]),
  array([ 0.10711633,  0.14219169,  0.25286393,  0.54276823,  0.53881591,
          0.75968704,  0.67347769,  0.73676474,  0.81378788,  0.93893092,
          1.28485223,  1.2111761 ,  1.66839135,  2.04652061,  2.47520212,
          2.3985014 ,  1.92157021,  1.09932218,  0.75564003,  0.2957186 ,
         -0.0646772 , -0.03506537, -0.55865013, -0.72474144, -0.39296577,
          0.22459349,  0.29709974,  0.82656829,  0.32954807,  0.79731293,
          1.74649321,  1.73761481,  1.99152563,  2.38909973,  2.26740621,
          2.02741262,  1.68503181,  2.24095678,  2.50430998,  2.55129347,
          2.80028719]),
  array([-1.92991462, -1.62996707, -0.9006065 , -0.86859215, -0.5789299 ,
         -0.0493198 ,  0.24842804,  0.07171027, -0.08403271,  0.63792374,
          0.40144472,  0.316386  ,  0.44441419,  1.08822502,  0.97842168,
          0.95528865,  1.46181811,  1.52566764,  1.25751807,  1.16028785,
          1.37156916,  0.91382332,  0.43080573,  0.6208344 ,  0.5320316 ,
          0.52981294,  0.21148226,  0.76772061,  0.7228852 , -0.22479045,
          0.65890519,  1.10905223,  1.32689227,  1.80453874,  1.65744065,
          1.73934173,  1.38368646,  1.6133465 ,  1.55993291,  1.68824105,
          2.01661927]),
  array([-2.13479561, -2.20339768, -1.41932425, -0.68963296, -0.72393416,
         -0.84270959, -0.56847752, -0.12490543, -0.34940059, -0.218324  ,
         -0.76494415, -0.55323233, -0.13954642,  0.47199043,  0.24664478,
          0.52558945,  0.99352602,  1.54251585,  1.63656373,  1.5532619 ,
          1.72109438,  1.77768664,  1.39990007,  0.75180317,  1.13945772,
          1.6886288 ,  1.89198763,  1.50837956,  1.49948045,  0.88662765,
          1.25127827,  1.27570729,  1.99379898,  2.43274814,  1.9248744 ,
          1.87630491,  1.99753651,  1.87410612,  3.01517485,  3.08455955,
          3.32685705])],
 'METEOR': [array([-0.51706148, -0.51392284, -0.6941442 , -0.96541238, -0.68135641,
         -0.49360196,  0.25101113,  0.41751509,  0.36938464,  0.64291286,
          1.76011242,  1.67060475,  1.83388196,  1.37685443,  2.27652892,
          3.09643289,  3.02345295,  3.02001618,  2.52619569,  2.22732788,
          2.05231319,  1.2763122 ,  1.30924702,  0.8334373 ,  1.06492417,
          2.69007951,  2.51319855,  3.51248348,  3.76084111,  3.21230858,
          2.77806011,  2.30797747,  2.52666648,  3.9293232 ,  4.17464701,
          3.65165969,  3.29956881,  3.36746762,  3.72933745,  2.78134718,
          2.3858214 ]),
  array([-0.16340043, -0.14428234,  0.58612414, -0.35355897, -0.33131619,
         -0.14722538, -0.85622861, -0.66852726, -0.21592673, -0.21630387,
         -0.16165808, -0.0119042 , -0.34967855, -0.25914039, -0.67376527,
         -0.39382323,  0.0325775 ,  0.32632224,  0.35072484,  0.0333326 ,
         -0.87336221, -0.7796561 , -1.57839704, -1.24234847, -1.41097204,
         -1.01433657, -0.82791108, -0.83752823, -0.45973386, -0.2550846 ,
          0.06877747, -0.02890692, -0.13328274,  0.56857624,  0.78823006,
          0.73670253,  0.86671149,  0.99684192,  1.31532139,  0.90045212,
          1.99648666]),
  array([-0.97912547, -0.98059468, -0.88056979, -0.64520975, -0.61885612,
         -0.43677518, -0.47572311,  0.62462701,  0.76491261,  0.80935341,
          0.97569193,  0.90933394,  1.5804892 ,  2.08748341,  2.2216817 ,
          2.29559875,  2.11456353,  0.64234247,  0.3750378 , -0.30847801,
         -0.87342894, -0.87461517, -1.27688101, -1.00170318, -0.73113172,
         -0.37619441, -0.2517681 ,  0.12967547,  0.16480439,  0.00314621,
          0.82592456,  0.81283897,  1.1509173 ,  2.87247032,  2.69354092,
          2.60172496,  2.287593  ,  2.71026458,  2.92772848,  2.4312294 ,
          2.56287338]),
  array([-1.19435798, -0.69388678, -0.06944084, -0.6325615 , -0.12979345,
          0.30677687,  0.32699051, -0.38669383, -0.39974515,  0.10816878,
         -0.1322774 ,  0.01877884, -0.06220943, -0.00293099,  0.12326925,
          0.16273802,  0.60711976,  0.58227053,  0.34928116,  0.32344227,
          0.48797834,  0.17045168, -0.13534763,  0.02775809, -0.04518288,
         -0.1265927 , -0.34074217,  0.04765027,  0.10409146, -0.44598994,
          0.30897197,  0.69122677,  0.88731414,  1.39558607,  1.29001189,
          1.13229399,  0.8504163 ,  0.72545453,  1.03901423,  0.77584521,
          0.9901266 ]),
  array([-2.02911351, -2.13692879, -1.7608703 , -1.15423935, -1.12775799,
         -1.21446868, -1.25024415, -1.10706481, -1.15308942, -0.51896514,
         -0.97049685, -0.80764387, -0.72437133,  0.57645741,  0.47120403,
          0.77062303,  0.97744177,  1.3208322 ,  1.35675424,  1.31663643,
          1.56351282,  2.43093545,  2.11363074,  1.64265379,  1.98334876,
          2.59977465,  2.83209457,  2.14324826,  2.35403914,  0.76160518,
          1.25538352,  1.24466698,  1.01808109,  2.45554663,  2.10404615,
          1.07487739,  1.12532115,  0.97038982,  1.84632794,  1.51409885,
          1.78352093])],
 'BERT': [array([ 0.82644135,  0.9372072 ,  0.8770689 , -0.944399  ,  0.34024566,
         -0.08912122, -0.2179982 ,  0.11536298,  0.5356516 ,  0.22180983,
          0.513481  ,  0.07249931,  0.4320324 ,  0.35182032,  0.4712013 ,
          0.4301722 ,  0.6885147 , -0.5341998 , -0.68376034, -1.596678  ,
         -1.6228777 , -0.8977285 , -1.4081879 ,  0.13993812, -0.4942012 ,
          0.08695924,  0.9983259 ,  0.4249631 , -0.06796091,  0.2842674 ,
          1.5314181 ,  0.03267609,  0.6891041 ,  1.7909236 ,  1.2552729 ,
          0.7843489 ,  1.6548678 ,  1.7961471 ,  2.489719  ,  0.5944661 ,
          1.7075087 ], dtype=float32),
  array([ 0.25327244,  0.01694315, -0.04807318,  0.3403047 ,  0.07364097,
         -0.4325357 ,  0.44363633, -0.11837135, -0.19979148,  0.16802111,
         -0.02676035, -0.3292586 ,  0.8510475 ,  1.1391995 ,  1.1577601 ,
          0.68740124,  0.9536775 ,  0.23850724, -0.16726325, -1.4126737 ,
         -1.2819012 ,  0.40521604,  0.08836161, -0.14270374,  0.01044954,
         -0.07478441,  0.29126307,  0.04522258,  0.7199806 ,  1.0704013 ,
          1.1174457 ,  1.9409385 ,  1.5697873 ,  1.4003859 ,  0.9285025 ,
          1.1041322 ,  0.9437773 ,  0.6363547 , -0.3032649 ,  0.38866016,
          0.13766894], dtype=float32),
  array([-0.6805724 , -0.85969144, -0.40011168,  0.15573733, -0.45014614,
         -0.5598176 , -0.255398  ,  0.21751592, -0.02710051,  0.20606264,
          0.09398437,  0.5635311 ,  0.51282936,  1.1180072 ,  1.7453156 ,
          2.2070813 ,  1.7257737 ,  1.3563807 ,  0.83951503, -0.64842534,
         -0.61066043, -0.33178553,  0.88810307,  0.5829055 ,  0.6254898 ,
          1.3396949 ,  3.1515749 ,  3.2368536 ,  3.80718   ,  4.712847  ,
          5.1917415 ,  5.6680164 ,  4.634117  ,  5.7461314 ,  4.5709066 ,
          4.800977  ,  4.9038954 ,  4.0207787 ,  4.226354  ,  4.26064   ,
          3.7585902 ], dtype=float32),
  array([-1.0880754 , -1.59371   , -1.905854  , -2.387481  , -0.09929342,
         -0.6531693 , -0.28440085, -0.13849103, -0.54108965, -0.64433825,
         -0.61823565,  0.12065221,  0.45547715,  0.4242137 ,  1.1123724 ,
          1.3521644 ,  1.6399567 ,  0.92311746,  0.6937518 ,  1.5095059 ,
          2.0148666 ,  2.7545495 ,  2.5905008 ,  2.0775223 ,  1.6661203 ,
          3.3532703 ,  3.8760297 ,  3.0939064 ,  4.3486776 ,  5.121391  ,
          4.7989273 ,  4.492045  ,  5.8080745 ,  6.8932247 ,  5.1149616 ,
          5.488021  ,  4.016856  ,  4.6502805 ,  3.4300606 ,  4.1453834 ,
          4.0751777 ], dtype=float32),
  array([-2.4987903 , -2.3023798 , -0.9787305 , -2.1414897 , -1.198638  ,
         -0.5296841 , -0.04940695, -0.4664416 , -0.42122263,  0.5641144 ,
          0.3869006 , -0.20377943,  0.5367627 ,  1.5329745 ,  1.7016658 ,
          1.8539573 ,  1.8840175 ,  2.0259345 ,  2.1918015 ,  1.9663326 ,
          1.4733883 ,  0.8311741 ,  1.1544749 ,  1.2844764 ,  1.8648359 ,
          1.632494  ,  2.7123783 ,  0.8018693 ,  1.2404085 ,  0.9874997 ,
          1.3300462 ,  1.2520046 ,  1.5316583 ,  1.8242762 ,  2.0236025 ,
          0.7094949 ,  1.5719863 ,  1.8156384 ,  1.3582907 ,  1.6020876 ,
          1.3105736 ], dtype=float32)]}

In [5]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

41
41
41
=
1689

,gpt_layer,WER,BLEU,METEOR,BERT
0,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,4,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
3,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [8]:
results_df

,gpt_layer,WER,BLEU,METEOR,BERT
0,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [6]:
gpt_layer_6=np.array(results_df.loc[0, 'BERT']).mean()
gpt_layer_7=np.array(results_df.loc[1, 'BERT']).mean()
gpt_layer_8=np.array(results_df.loc[2, 'BERT']).mean()
gpt_layer_9=np.array(results_df.loc[3, 'BERT']).mean()
gpt_layer_10=np.array(results_df.loc[4, 'BERT']).mean()
to_file = pd.DataFrame({'gpt_layer':[3,4,5,8,10], 'significantly_decoded': [gpt_layer_6,gpt_layer_7,gpt_layer_8,gpt_layer_9,gpt_layer_10]})
to_file.to_csv('imagined_speech_gpt_words.csv', index=False)

to_file

   gpt_layer  significantly_decoded
0          3               0.000000
1          4               0.000000
2          5               0.317073
3          8               0.365854
4         10               0.000000