In [1]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_movie/gpt_words_5/laluna.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('laluna', 'WER'): np.float64(2.818599966484292), ('laluna', 'BLEU'): np.float64(2.7414086899339147), ('laluna', 'METEOR'): np.float64(3.0183906555115003), ('laluna', 'BERT'): np.float32(5.088041)}

In [ ]:
window_zscores = {'gpt_layer': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for gpt_layer in [3,4,5,8,10]:
    for task in ['laluna']:
        scores = np.load(f'scores/S1/perceived_movie/gpt_words_{gpt_layer}/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['gpt_words'].append(gpt_layer)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'gpt_layer': [3, 4, 5, 8, 10],
 'WER': [array([ 0.76372104,  1.39585843,  1.20082258,  0.65846204, -0.50507627,
          0.19994175, -0.36063848, -0.53838329, -0.49254951, -0.04788928,
          0.01125159, -0.27990308, -0.57801485,  0.61521986, -0.89970724,
          0.25546877,  0.42568539,  0.07215383,  0.34465791, -0.20533809,
         -0.0488532 , -0.89449253, -0.70816339,  0.40369519,  0.23397801,
         -0.14998296, -0.26376172, -0.74871928, -0.09853293,  0.8193346 ,
          0.68906753,  0.22848142,  0.07148436,  0.06410766, -0.8100809 ,
         -0.11419369,  0.1814885 , -0.40659909,  0.41539383, -0.21141705,
          0.01308174,  0.41745633,  0.40525882,  0.56983913,  0.03044313,
          0.12126781,  2.01687933,  2.21748495,  3.36104836,  2.68693976,
          1.9419084 ,  1.77121775,  1.45384382,  1.4837892 ,  2.26635748,
          2.51786228,  2.22415066,  2.44199272,  1.61078051,  1.49717464,
          1.45145368,  2.34875355,  2.35264178,  3.30250219,  4.07721103,
          2.33408774,  1.52015265,  0.62791919,  1.56241353,  0.88185053,
         -0.10314212,  0.30314645,  0.81667176, -0.13906483,  0.71422387,
          1.46182161,  1.50351567,  1.37619513,  2.55606677,  2.02817057,
          2.75557044,  2.21808023,  2.18975005,  1.19032005,  0.40248548,
          0.30845685,  0.48466601,  0.15203822, -0.20851441,  0.52858643,
          0.34457729,  1.21216976,  0.95130844,  1.12217832, -0.18421252,
         -0.73593801,  1.64118128,  2.76800507,  3.0924152 ,  2.28645762,
          0.45069169, -0.15599742,  1.47972928,  0.78072516,  0.4869806 ,
          2.36859856,  1.22244306,  1.19250131,  0.58080882,  0.61827126,
          0.37762781,  0.70161882, -0.54321448, -0.17076159,  0.45567795,
          0.88377996,  1.31049277,  0.21644547,  0.27778653,  1.37614302,
          0.91401368,  1.69607149,  1.11581175,  1.14512239,  1.19097979,
          0.69148236,  0.76049589,  0.82915852,  1.47408695,  0.94720955,
          1.79252599,  2.43767561,  2.47153864,  2.8858914 ,  1.19414691,
          1.25723711,  1.94656039,  2.5079904 , -0.50743419,  3.20865083,
          1.99054885,  1.64793125,  1.58154717,  1.84671926,  1.55023633,
          1.20385853,  1.77491776,  1.6938004 ,  1.47789283,  0.99424252,
          1.1000382 ,  1.25055023,  1.20254412,  1.93576681,  1.31378274,
          1.06468884,  0.49382982, -0.00980628, -0.0470959 , -0.16743796,
          1.98198297,  1.93620888,  1.78137974,  1.54070578,  1.82749093,
          0.9304804 ,  0.03154009, -0.0674566 ,  0.25779244,  0.2786656 ,
          1.20555762,  0.13562727, -0.00411697,  0.64164057, -0.06876142,
          0.19317114,  0.13189818,  1.15813205,  0.9430641 ,  1.36434287,
          0.76881007,  0.59402868,  0.29741802,  0.26418633,  1.08580303,
          2.89429146,  2.16734891,  3.28448158,  3.16807739,  3.37652252,
          2.96690728,  3.35337738,  2.80026474,  3.16219185,  1.89796813,
          1.35710229,  1.90443587,  0.48523781,  1.83105938,  0.06641892,
          0.96694853,  1.67837555, -0.66304143, -0.25474886, -0.48263365,
          0.02986141, -0.51658303, -0.24048079, -0.30079313, -0.25975943,
         -0.84123014, -0.88402318, -1.62696277, -1.72498288, -1.41888073,
         -1.60060662, -2.62364656, -2.43424091, -2.29809281, -2.18797487,
         -2.02995439, -1.32251458, -1.34745101, -1.45195587, -1.30396186,
         -1.10276559, -0.49362588,  0.01195314, -0.29310519, -0.19747427,
         -0.16924949, -0.26255698,  0.50848101,  0.5991376 ,  0.46302715,
          1.63611742,  1.45731156, -0.00564342, -0.02310017, -0.05783149,
          0.45749571,  0.31448545,  1.18539879,  1.38579264,  2.08076747,
          2.03539785,  1.91440626,  1.31267933,  0.64438608,  0.9159675 ,
          1.81825574,  0.85011808,  1.52838596,  0.20632905,  0.99014754,
          0.24214029, -0.0608574 ,  1.01896703,  1.26383423,  1.62821767,
         -0.11624764,  0.05522202,  0.50932141,  0.24861341,  1.0080973 ,
          1.11884432,  0.41147134,  0.43245462,  0.22095181, -0.09397235,
         -0.13524203, -0.2736713 ,  0.43411684,  0.56195149,  1.20894485,
          1.19256959,  1.34869082,  0.73261342,  0.70710678,  1.26803787,
          1.19655773,  0.11506374,  0.49183396,  0.5577669 , -0.03700532,
         -0.13053135, -0.15436079, -0.28670271,  0.76977624,  1.1989911 ,
          0.08784833,  0.97407624,  1.22142307,  0.76432211,  0.6122583 ,
          0.49242763, -0.5472412 , -0.40067641, -0.61619425, -1.24327057,
         -0.46775066,  0.7903797 ,  0.07996254,  0.19210981,  1.16862777,
          0.89442719,  0.05310774,  0.36139703,  0.34752402, -0.19385017,
         -0.23633602,  0.54766255,  0.40446441,  0.30684241,  0.42667013,
          0.09439713, -0.06064629, -0.12792225, -0.13482197,  0.20637209,
         -1.18292184,  0.51568795, -0.14399731, -0.93724667, -0.78072516,
         -1.06234116, -0.96824584, -0.78750907, -0.6705148 , -0.93548553,
         -1.2093836 ]),
  array([ 1.59160001,  2.16666667,  2.85367933,  0.78786591,  0.6092077 ,
          2.57341775,  1.8817369 ,  1.64764315,  1.65322195, -0.13090387,
         -0.06944891,  0.74047564,  0.39876133, -0.4065547 ,  0.28159982,
         -0.98742943,  0.5280889 ,  0.20894723, -0.53300179, -0.10319921,
         -0.85239936, -0.83152184,  0.39605902, -0.43655343, -1.27164379,
         -0.85835439, -1.80071371, -1.63184424, -0.81804386, -0.52143958,
         -0.6024021 , -0.39670191,  0.91530891,  0.91658788,  1.41118024,
          1.2598947 ,  1.58597185,  0.3218379 , -0.32281837, -0.22029078,
          0.0204508 ,  0.46332637, -0.43383623, -1.14034289,  0.10850513,
         -1.09812675, -0.13881853, -0.1542014 , -1.33977018, -0.52841131,
         -0.81886119,  0.98176179,  0.55381862,  0.6125497 ,  0.46359473,
         -0.26688917, -0.31278087, -0.17609018,  0.9138071 ,  0.77034353,
          1.76548607,  1.88262005,  1.89620478,  2.76165966,  1.880851  ,
          1.90264909,  2.58212831,  2.66904611,  2.57701894,  2.6601646 ,
          1.92618734,  2.11546841,  2.51957812,  3.36816774,  3.33927346,
          3.17767239,  3.32122978,  2.27456071,  1.51955969,  0.98570601,
         -0.05037663,  0.1808376 , -0.75810991,  1.1677166 , -0.42717883,
          0.27628583,  0.43163849,  1.00548675,  0.66089455, -1.09333878,
         -0.62961186, -0.7254426 , -0.861954  ,  0.1718108 ,  0.90863935,
          0.53935989, -0.38204395, -0.018735  , -0.72528634,  0.10113636,
          0.42450149, -0.20851441,  0.52568128,  0.91616721,  0.49130368,
          0.138266  ,  1.23901566,  1.1969588 ,  0.66245673,  0.64584061,
          0.50891336,  0.92591938,  0.47991676,  0.99177039,  1.65307165,
          1.03088063,  1.27653582,  0.99858135,  1.14338443,  1.4292735 ,
          1.81984308,  1.00503732,  2.09674069,  2.07423996,  2.0566327 ,
          1.69775891,  1.62288234,  0.80577846,  0.67727972,  1.03471867,
          1.75116045,  1.48365074,  0.52500136,  0.82779055,  0.14737789,
          0.12092353,  0.72932496,  1.09269679, -0.47021164, -0.54315951,
          0.7076146 ,  0.26609607,  0.24846361,  0.65129817,  0.43667453,
          1.10217597, -0.28172764, -0.34158727,  0.67207128,  0.15203822,
          0.2847474 ,  1.59557599,  1.46180246,  1.39049288,  2.32403011,
          1.08924351,  1.33815767,  0.88784869,  1.77580876,  1.68527807,
          2.52695286,  2.30595255,  2.13386838,  1.85798385,  2.11879381,
          2.38086467,  2.42467075,  2.32020811,  1.83692793,  0.98590376,
          0.98707152,  1.63575138,  1.472857  ,  1.34892495, -0.09884048,
          0.15922595,  0.14760965,  0.35783655,  0.19064955, -2.01695349,
         -0.0853512 , -0.27250901,  1.14197832,  1.81265393,  1.79401988,
          0.36210182,  0.46175123,  0.1097459 ,  0.02728288, -0.08640358,
          0.02482223, -0.08462884,  0.30305453,  1.26018496, -0.03927211,
         -0.45667413,  0.12702494,  0.41720541,  0.83106089, -0.10235586,
         -0.73261342, -0.41170008, -0.76300645, -0.42452406, -0.6114455 ,
         -0.90673485, -0.69414376, -0.3200831 , -0.2989225 , -0.23851129,
         -0.01768043, -0.89897843, -0.88934056, -0.21747811,  0.09439713,
         -0.89814624, -0.81657876, -0.72416682, -1.30631917, -1.07682623,
         -1.01695036, -1.16862777, -1.196747  , -1.43777438, -1.27235354,
         -1.01697666, -1.47046209, -1.10991612, -0.20545729, -1.31040286,
         -1.20825582, -0.11704115, -0.47750118,  1.70020297,  2.48194326,
          1.64426437, -0.53249156,  0.03903919,  0.01693241, -0.01661776,
          1.4747039 ,  1.33193867,  1.08908803,  0.42295202,  0.20117473,
          2.07472549,  2.02756796,  1.36248778,  0.89959193,  0.91381155,
         -0.30636061, -0.2826121 , -0.58251187, -0.71127546, -0.91347835,
         -0.71182874,  0.00432746,  1.16326171,  1.22159399,  1.48676642,
          2.09784603,  0.9355986 ,  0.54353073,  0.31268432,  0.98891313,
          1.08873187,  1.26236921,  1.13389342,  0.9573865 ,  0.58131836,
          0.51312559,  1.80453583,  1.70902105,  2.51559556,  1.75725791,
          1.74454923,  1.14548027,  2.71909945,  2.66694297,  2.43565289,
          1.10503066,  1.5157123 ,  1.96240391,  2.00029142,  1.73879681,
          0.75819542,  1.53726989,  1.53687204,  0.83167183,  1.20570712,
          2.2457523 ,  1.67748427,  0.45195269, -0.0659937 ,  0.65594228,
          0.54469855,  0.31434711, -0.2921497 ,  0.29982016,  0.52036957,
         -0.42678981, -0.27175853,  0.07482887, -1.05186802, -1.88282989,
         -2.00479988, -0.93024473, -1.71725933, -1.69913813, -1.43587665,
         -1.36708771, -1.57581856, -1.62545812, -1.6515499 , -1.58426425,
         -1.80435892, -1.89881132, -1.87500068, -1.75121563, -1.49614838,
         -1.17217053, -1.2109972 , -0.99557501, -1.54126695, -0.74969167,
         -1.07331378, -1.56266657, -1.41999882, -1.38405844, -0.81963181,
         -1.34495108]),
  array([ 7.13076184e-01,  1.35837708e+00,  2.34197321e+00,  9.85706013e-01,
          8.92294177e-01, -4.11401864e-02,  6.08695652e-01,  1.47802357e+00,
          1.65754018e+00,  1.15878673e+00,  3.94610899e-01,  2.72237292e+00,
          2.13221249e+00,  2.55567238e+00,  1.92209395e+00,  3.05868724e+00,
          1.46578399e+00,  1.94332945e-01,  1.02641719e+00,  6.46342555e-01,
          8.60309002e-02, -6.61915886e-01, -7.12920553e-01, -3.77964473e-01,
         -8.82456389e-01, -1.12329004e+00, -1.28237080e+00, -1.82878652e+00,
         -1.04785227e+00, -1.50678010e+00, -1.49168004e+00, -1.44126792e+00,
         -1.47945288e+00, -1.48069948e+00, -1.68138500e+00, -1.63611742e+00,
         -6.85432479e-01, -4.55022200e-01, -3.42916717e-01, -1.98109973e-01,
          3.64641527e-02, -2.49048636e-01, -2.22294382e-15, -5.29851356e-01,
          3.28057146e-01, -3.95673841e-01,  9.76447256e-02, -2.64369569e-01,
         -7.28923697e-01,  8.03824757e-01,  1.20862332e+00,  1.03739286e+00,
          6.33167295e-01,  7.37737162e-01,  1.61006088e+00,  1.75735135e+00,
          1.77826529e+00,  2.20676171e+00,  1.40343499e+00,  3.06651272e+00,
          1.24682766e+00,  1.37688979e+00,  1.36682253e+00,  1.57874036e+00,
         -1.50806382e-01,  5.60436218e-01,  1.24007081e+00,  8.65279474e-01,
          8.33441541e-01,  8.35576134e-01,  2.49037100e-01,  8.71471687e-01,
          1.29586258e+00,  1.80991938e+00,  1.20681219e+00,  1.47663315e+00,
          1.28499688e+00,  7.54317030e-01,  7.97497741e-01,  4.01834063e-01,
          7.11134704e-01,  4.66740089e-01,  9.19585550e-01, -2.60025484e-02,
          1.65543857e-02, -5.94067750e-01,  9.27057733e-02,  1.05242321e+00,
         -9.31414183e-01, -4.41145287e-01, -1.11149235e-01, -2.61443493e-02,
         -8.55661036e-01,  7.73809977e-01,  2.24123128e-01,  8.48394679e-01,
          1.45267275e+00,  1.08917648e+00,  4.26032113e-01,  6.68153414e-01,
          6.93687976e-01,  9.91384481e-01,  1.37098832e+00,  2.84930593e-01,
          1.50302226e+00,  9.75966147e-01,  1.00991932e+00,  8.50556814e-01,
          1.33472129e+00,  5.74105948e-01,  5.53398591e-01,  3.38388181e-01,
          1.07260375e+00,  6.42746931e-01,  2.41684122e+00,  1.64462193e+00,
          1.69758358e+00,  1.98183773e+00,  1.95551327e+00,  2.15739147e+00,
          2.36373459e+00,  3.02098948e+00,  2.76240477e+00,  2.67444428e+00,
          1.77048178e+00,  1.27528693e+00,  1.23712233e+00,  1.39812123e+00,
          4.89767827e-01,  8.66099697e-01,  1.81746089e+00,  1.67845125e+00,
          7.11930907e-01,  1.00347827e+00,  1.44315436e+00,  1.82545695e-01,
          7.41009025e-01, -7.14857404e-01,  1.08095394e+00,  9.03486998e-01,
          1.12316027e+00, -3.88699493e-01, -3.17643715e-01, -5.00031888e-01,
         -7.68810066e-01, -8.19231921e-02,  1.57859015e+00,  8.75473787e-01,
          2.92227725e-01, -6.29307291e-01, -4.88915319e-01,  5.53633474e-01,
          7.09219559e-01,  6.12549704e-01,  7.93903029e-01,  6.29630921e-01,
          6.51217145e-01,  3.27468505e-01,  7.80013495e-01,  5.68145145e-01,
          1.15727512e+00,  2.79787718e+00,  2.56590469e+00,  2.43216175e+00,
          2.81917685e+00,  2.22831825e+00,  2.97038197e+00,  2.97038197e+00,
          3.35411898e+00,  3.33061905e+00,  2.70500890e+00,  1.67125804e+00,
          1.53252206e+00,  2.40425427e+00,  1.71859199e+00,  2.83735185e-01,
          4.39411324e-01,  5.55411442e-01,  1.26388393e+00,  9.97559980e-01,
          8.52066257e-01,  3.25818826e+00,  1.54223083e+00,  2.28135468e+00,
          2.44102877e+00,  2.63040551e+00,  2.79723301e+00,  2.61138823e+00,
          2.48731299e+00,  1.98412907e+00,  2.34934097e+00,  3.03616812e+00,
          1.76093205e+00,  1.98815106e+00,  6.63407659e-01,  1.61510680e-01,
          1.54152824e+00,  1.58025177e+00,  1.60481919e+00,  1.41437547e-01,
          1.17838142e-01,  7.20227098e-01,  3.18686150e-01,  3.54867171e-01,
         -3.22514474e-01, -6.57951695e-02, -1.34769962e+00, -1.64791542e+00,
         -1.61078051e+00, -1.62791966e+00, -1.33401001e+00, -1.50748225e+00,
          2.97533112e-02, -2.72990076e-02,  3.17598422e-01, -6.49639190e-01,
         -6.64139304e-01, -4.40589337e-01, -1.24514827e+00, -1.90772106e+00,
         -1.91040994e+00, -2.00849675e+00, -2.11980432e+00, -1.97105491e+00,
         -1.39410984e+00, -1.04730832e+00, -1.40859800e+00,  2.15079707e-01,
          2.28276406e-01, -7.17740563e-01, -5.39330879e-01, -3.71586253e-01,
         -4.57066185e-01, -1.63763418e-01, -1.12041887e+00,  6.13794906e-01,
          1.55517161e-01, -6.65209025e-01, -6.38966295e-01, -6.42124901e-01,
         -1.31833288e+00, -4.65574791e-01, -5.08079965e-01, -6.04960848e-01,
         -6.98548214e-01, -8.79748584e-01, -2.80822736e-01,  3.90670208e-01,
          8.20825282e-01,  6.87597577e-01,  5.74236969e-01,  6.42999053e-01,
          4.67874817e-01,  3.69295043e-01,  1.17164979e+00, -1.17219700e-01,
          1.92628532e-02,  1.02208642e+00,  1.11400589e+00,  1.08173216e+00,
          2.78777799e-01,  8.97984945e-01,  6.30263162e-01,  4.03056393e-01,
          1.28285769e+00,  5.56815650e-01,  1.24363617e-02,  1.57680034e+00,
          8.17680425e-01,  1.36661690e+00,  1.39103008e+00,  1.31132985e+00,
          1.30795405e+00,  1.23656804e+00,  1.85142830e+00,  1.92096661e+00,
          1.44434706e+00,  1.42062057e+00,  1.28794967e+00,  1.25326750e+00,
          5.09510171e-01,  9.36448232e-01,  8.69082973e-01,  6.33531886e-01,
         -4.80175403e-02,  3.91770864e-01,  2.68765256e-01, -3.62123561e-01,
          1.03785902e+00,  1.24084612e+00,  2.23649063e+00,  3.55794800e+00,
          3.23351570e+00,  2.65533198e+00,  4.01502094e+00,  3.10557096e+00,
          3.64662479e+00,  3.30232364e+00,  3.22573285e+00,  3.48373162e+00,
          2.43719702e+00,  1.20726713e+00,  2.40509188e+00,  8.47501110e-01,
          1.74208051e-01,  1.86859135e-01,  1.87769405e-01,  2.03444176e-01,
          1.06667720e-01, -5.47662554e-01, -1.52452649e+00, -1.55481992e+00,
         -1.77961467e+00, -1.58209205e+00, -1.96157503e+00, -9.22069664e-01,
         -8.47168128e-01, -8.93896173e-01, -6.25543242e-01, -9.06439923e-01,
         -1.16173388e+00, -1.35630111e+00, -8.24788689e-01, -1.09691655e+00,
         -6.19828949e-01, -7.91256568e-01, -6.84189105e-01, -4.33422934e-01,
         -3.42864809e-01,  7.41991340e-15, -4.26044792e-01]),
  array([ 0.72160981,  2.01799137,  1.8545317 ,  0.75819542, -0.35590283,
         -0.9420932 , -0.26974021, -0.44360718, -0.43592186, -0.06103674,
         -0.00583222,  0.68525392,  1.35983849,  1.71249583,  1.56547336,
          0.25376358,  1.48869074,  2.09620607,  1.52383241,  0.78376958,
          0.95316192, -0.76652883, -0.57228075, -1.22318568, -1.2667105 ,
         -0.85610254, -1.04797787, -0.80000336, -0.75481318, -0.58141691,
         -0.65254616, -0.53469225, -0.64559987, -1.37141811, -1.56989876,
         -1.67638892, -1.5068804 , -1.3033068 , -0.3965424 , -0.33091374,
         -0.04824922,  0.35770047,  0.29092742,  0.54503978, -0.02822787,
          1.25852282,  0.90631821,  0.8922686 , -0.02878368,  0.6       ,
          1.05654109,  1.72687463,  0.53588924,  0.61058022,  1.32173289,
          1.37599198,  2.02348227,  1.40937137,  2.37450168,  2.27997704,
          2.42340176,  2.69760195,  2.59929705,  3.48560211,  3.60460456,
          1.86387479,  1.83666724,  2.69268997,  2.92370836,  3.137004  ,
          2.12294753,  1.45861431,  1.95682324,  1.74639229,  1.85680966,
          2.57859229,  2.57594299,  2.39220144,  1.76583512,  2.07358682,
          2.04295387,  1.42951531,  1.47572957,  1.35876   ,  1.49903952,
          1.2795104 ,  1.51328252,  1.1389114 ,  1.69941166,  1.58061963,
          1.29433667,  1.17816454,  0.90874369,  1.03191649,  1.85322073,
          2.8829331 ,  2.27309128,  1.67816051,  2.15874976,  1.04717631,
          0.49290383,  0.87436265,  0.48759236, -0.73878675,  1.6277987 ,
          1.28517913,  2.36722909,  2.30972761,  1.54624357,  1.74553199,
          0.46875467, -0.25905965,  0.55983145,  2.03246213,  3.65317392,
          2.63117406,  2.90508825,  1.85349907,  1.1969581 ,  2.36091007,
          0.97007119,  0.89174928,  1.06006601,  1.1385473 ,  1.19097979,
          1.82764375,  1.80325667,  1.79520404,  1.65605774,  2.03370393,
          2.82664334,  2.55605677,  1.65631218,  0.77773298,  1.51423059,
          0.26612349,  0.71421287,  1.1823734 , -0.4744627 , -0.54236408,
          0.78139668,  0.3074594 ,  0.28373447,  0.50694111,  0.31792434,
         -0.10783277, -0.30341721, -0.37577969, -0.42568539, -0.82755207,
         -0.71350919, -0.56453506,  0.26328592,  1.03155392,  1.15056499,
          0.90144107,  0.30756371,  0.67777068, -0.27533144,  0.51824785,
          0.86554705,  1.64050005,  1.57649193,  1.28186263,  0.80997874,
          0.85691933,  0.84425308,  1.54546452,  1.81295857,  1.89237062,
          1.16121861,  0.91772192,  0.7954684 ,  0.68599434,  0.77433199,
          1.09578099,  1.0494929 ,  2.10542699,  1.01156689,  1.54361004,
          2.86161746,  2.30947176,  2.84214292,  2.78679945,  3.57494148,
          2.87022275,  2.21212732,  2.35755898,  2.18697214,  1.28544474,
          2.2238489 ,  1.2523568 ,  1.39951064,  1.36184544,  1.11004293,
          0.56505083,  0.20153823,  0.56527103, -0.89524937,  0.03826532,
         -0.71709451, -0.36358072,  0.37031943, -0.24196696, -0.5150962 ,
         -0.0273964 , -0.68774638, -0.38304537,  0.45781782, -0.27447932,
         -0.09030308, -0.02835356,  0.62278545,  0.59251077,  0.97279635,
         -0.06273186,  0.04323377,  1.02651071, -0.50709255, -1.14906888,
         -0.18181818,  0.60173383,  0.50428927,  0.42105447,  0.65167848,
          0.88178405,  1.52502068,  1.09147673,  2.03421402,  0.81029434,
          0.86276353,  1.97694017,  1.43739748,  0.61588176,  0.54118272,
          0.54062929,  2.5669604 ,  3.73313937,  2.41742472,  2.36186183,
          2.31154184,  1.32447623,  0.92179769,  0.28867513,  1.01695036,
          1.97801876,  2.05062683,  2.6289549 ,  1.76452076,  2.09807752,

In [4]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

331
331
331
=
1689

,gpt_layer,WER,BLEU,METEOR,BERT
0,3,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,4,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [8]:
results_df

,gpt_layer,WER,BLEU,METEOR,BERT
0,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [5]:
gpt_layer_6=np.array(results_df.loc[0, 'BERT']).mean()
gpt_layer_7=np.array(results_df.loc[1, 'BERT']).mean()
gpt_layer_8=np.array(results_df.loc[2, 'BERT']).mean()
gpt_layer_9=np.array(results_df.loc[3, 'BERT']).mean()
gpt_layer_10=np.array(results_df.loc[4, 'BERT']).mean()
to_file = pd.DataFrame({'gpt_words':[3,4,5,8,10], 'significantly_decoded': [gpt_layer_6,gpt_layer_7,gpt_layer_8,gpt_layer_9,gpt_layer_10]})
to_file.to_csv('perceived_movie_gpt_words.csv', index=False)

to_file

   gpt_words  significantly_decoded
0          3               0.196375
1          4               0.087613
2          5               0.132931
3          8               0.199396
4         10               0.226586