In [6]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_speech/gpt_words_5/wheretheressmoke.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('wheretheressmoke', 'WER'): np.float64(7.155794176075754), ('wheretheressmoke', 'BLEU'): np.float64(5.9819780851328215), ('wheretheressmoke', 'METEOR'): np.float64(6.147434015058574), ('wheretheressmoke', 'BERT'): np.float32(14.002044)}

In [7]:
window_zscores = {'gpt_layer': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for gpt_layer in [3,4,5,8,10]:
    for task in ['wheretheressmoke']:
        scores = np.load(f'scores/S1/perceived_speech/gpt_words_{gpt_layer}/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['gpt_layer'].append(gpt_layer)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'gpt_layer': [3, 4, 5, 8, 10],
 'WER': [array([-5.37826588e-02,  8.87179157e-01,  7.01598259e-01,  5.60855047e-01,
          7.29414201e-01,  2.24651482e+00,  1.08236126e+00,  1.65503185e+00,
          2.08617312e+00,  1.84191450e+00,  1.99827230e+00,  2.43723456e+00,
          2.12277840e+00,  2.86556127e+00,  3.00057885e+00,  2.81019506e+00,
          2.24106129e+00,  2.77235530e+00,  1.41674271e+00,  7.65723925e-01,
          1.77561563e+00,  8.44763720e-01,  8.05242191e-01,  9.25237295e-01,
          9.27782833e-01,  1.53359590e-01,  2.01527509e-01,  6.16571666e-01,
          1.05099994e+00, -2.23662720e-02,  5.65735715e-01,  9.10142915e-01,
          9.23281351e-01,  4.25413563e-01,  1.93302542e-01,  9.03786479e-02,
          1.75852269e+00,  1.28533196e+00,  7.94882912e-01,  1.15550277e+00,
          5.94353290e-01,  9.11701011e-01,  6.21260595e-01, -6.87782156e-02,
          1.97620157e-01,  3.68855557e-02,  1.25390546e+00,  1.12419978e-01,
         -2.92875964e-01, -4.57471006e-01, -5.38237707e-01,  3.30891298e-01,
          3.04924789e-01,  8.66580587e-01,  3.83680582e-01,  1.01570189e+00,
          1.94935887e+00,  1.29825711e-01, -8.46302016e-01, -6.63451267e-01,
          1.20010587e+00,  1.62952523e+00,  2.40924356e+00,  2.47028546e+00,
          1.32655344e+00,  1.86301170e+00,  1.06371494e+00,  4.92500013e-01,
          6.82349452e-01,  6.05310301e-01, -1.54475254e-01, -8.49234789e-01,
         -4.14516897e-03, -1.90000211e-01, -8.17504975e-01, -5.25097551e-01,
         -3.47056450e-01,  4.59334003e-01,  3.71753386e-01,  1.26614612e+00,
          1.79985523e+00,  1.63956302e+00,  1.95180015e+00,  1.52456341e+00,
          2.26391034e+00,  1.20331874e+00,  1.03110746e+00,  1.29086908e+00,
          1.04014062e+00,  2.78251437e+00,  3.44003062e+00,  3.53591888e+00,
          4.72197815e+00,  6.54733096e+00,  6.54573668e+00,  6.71582983e+00,
          6.54177016e+00,  6.98705960e+00,  5.85185111e+00,  5.71134453e+00,
          4.65827710e+00,  4.83558195e+00,  4.89484484e+00,  5.52453790e+00,
          4.92307059e+00,  5.53342481e+00,  5.12188457e+00,  5.59956690e+00,
          4.85198274e+00,  4.11775504e+00,  4.01927884e+00,  3.85457945e+00,
          2.78948553e+00,  1.97821856e+00,  2.51335000e+00,  2.05524124e+00,
          2.72151450e+00,  2.74534893e+00,  1.84180982e+00,  1.83977755e+00,
          3.34056219e+00,  2.72101907e+00,  3.39361820e+00,  2.65957185e+00,
          3.59113917e+00,  2.18073991e+00,  2.51943697e+00,  2.67909875e+00,
          2.41737601e+00,  2.41334505e+00,  2.14067570e+00,  3.04428812e+00,
          3.35245710e+00,  3.23278580e+00,  4.13172026e+00,  3.85267737e+00,
          4.73731520e+00,  3.41799519e+00,  4.10717633e+00,  3.11174964e+00,
          3.55322356e+00,  3.84664475e+00,  3.83033197e+00,  3.52159112e+00,
          3.41937140e+00,  2.89164146e+00,  4.18269326e+00,  2.58493233e+00,
          3.49944147e+00,  3.49084276e+00,  3.48363141e+00,  3.24295227e+00,
          2.03917932e+00,  2.34074161e+00,  2.29002004e+00,  2.12654649e+00,
          1.23141608e+00,  2.26810688e-01,  6.92024592e-01,  5.35524238e-01,
         -1.01744616e-01,  1.95867257e-01, -7.76930969e-02,  4.29512711e-01,
         -1.05292329e-01, -2.61633654e-01,  4.31134620e-03,  3.84088853e-01,
         -1.18520231e-01, -7.07914723e-01, -8.22687661e-01,  7.58272917e-01,
         -1.29731625e-01,  4.12568499e-01, -1.23873852e+00, -2.51736318e-01,
         -8.36899287e-01, -8.16944295e-01, -7.43512753e-01,  1.87016090e-01,
         -1.38972316e-01, -2.44328100e-01, -8.01463866e-01, -1.29848929e+00,
         -4.26026103e-01, -1.63425465e+00, -1.02307632e+00,  9.19174791e-01,
          2.51850381e-01,  4.50834817e-01,  7.74455035e-01, -1.94486134e-01,
         -6.30947263e-01, -1.83066067e-01, -3.66414670e-01,  4.48119448e-01,
          8.79121804e-01,  1.23876688e+00,  1.38760592e+00,  1.53334239e+00,
          1.84219646e+00,  4.14042154e+00,  2.69957022e+00,  3.52335497e+00,
          4.64617853e+00,  4.19755365e+00,  2.18687166e+00,  2.89662061e+00,
          2.55155132e+00,  1.76874764e+00,  2.43559895e+00,  2.92508970e+00,
          2.70062585e+00,  2.78890453e+00,  2.12557607e+00,  2.24500263e+00,
          1.78386736e+00,  2.11371191e+00,  1.01958570e+00,  1.70979699e+00,
          1.26747167e+00,  1.11111111e-01,  8.40262002e-01,  1.69249490e-01,
         -8.28633236e-01, -8.75000000e-01,  9.70376654e-01,  5.00299184e-01,
          8.30285690e-01,  2.00020637e+00,  1.08129432e+00,  4.90024502e-01,
          5.66572116e-01,  2.47241624e+00,  2.83247381e+00,  2.47241624e+00,
          3.49901538e+00,  2.27078246e+00,  2.20279572e+00,  1.88977992e+00,
          1.74484953e+00,  2.32366977e+00,  1.53457391e+00,  2.10822827e+00,
          1.79459605e+00,  1.68138500e+00,  1.45967847e+00,  1.18275956e+00,
          1.65963557e+00,  4.12717015e-01,  9.19082032e-01,  7.21201832e-01,
         -2.59015672e-01, -9.84650716e-02,  1.20268017e-01,  4.67609765e-02,
         -7.35811347e-01, -1.61801430e-01,  2.88040158e-01, -2.97420377e-01,
         -5.82511869e-01, -1.38973935e+00, -5.78958810e-01, -5.68828143e-01,
          6.84092676e-01,  1.40859800e+00, -7.87068370e-01,  8.35584533e-01,
          4.18265471e-01,  1.40275411e+00,  1.41900718e+00,  1.35214539e+00,
          2.37689217e+00,  1.91438112e+00,  1.43108833e+00,  1.46823461e+00,
          1.19098728e+00,  1.87190590e+00,  1.25198350e+00,  1.40897908e+00,
          2.82501121e+00,  2.73425248e+00,  2.63698508e+00,  1.88564818e+00,
          3.40997170e+00,  3.54022369e+00,  3.27101995e+00,  3.00896862e+00,
          3.19818807e+00,  3.04813617e+00,  3.19178282e+00,  3.13294838e+00,
          3.06749574e+00,  3.09917738e+00,  2.91951229e+00,  1.96566120e+00,
          2.34012617e+00,  1.81847977e+00,  2.66266400e+00,  2.86264413e+00,
          2.23204860e+00,  6.62113326e-01,  2.92981590e+00,  3.10245636e+00,
          9.32592123e-01,  2.30568422e+00,  2.96019170e+00,  2.87992181e+00,
          3.45969522e+00,  2.24732202e+00,  2.52094501e+00,  3.20407519e+00,
          2.87171324e+00,  3.13498992e+00,  3.40214626e+00,  3.81563299e+00,
          3.10158303e+00,  2.05903837e+00,  2.02068783e+00,  3.28228012e+00,
          1.60620343e+00,  5.18247852e-01,  6.11386141e-01,  6.57943509e-01,
          1.29330996e+00,  7.79985485e-01,  1.96532334e-01,  1.69030851e-01,
         -3.55075370e-01,  2.66279087e-01,  1.69637786e-01,  9.40977917e-01,
          9.33799056e-01,  1.24349473e+00,  4.54858826e-01,  8.66432266e-01,
          1.02899151e+00,  1.78289024e+00,  2.10249836e+00,  1.60359179e+00,
          7.95647961e-01,  9.25216856e-01,  1.97760916e+00,  2.12317010e+00,
          4.64828754e-01,  6.98131047e-01,  2.73719931e-01,  4.01273804e-01,
          2.13426920e+00,  1.11028898e+00,  1.09164156e+00,  1.41132577e+00,
          6.49156901e-01,  7.55904504e-01,  5.53818620e-01,  3.16385999e-02,
          5.20287278e-02,  5.58947292e-01,  1.21873576e+00,  7.08816593e-01,
          2.30540240e+00,  1.66405087e+00,  2.01539793e+00,  1.08052870e+00,
          1.32965436e+00,  2.06669026e+00,  2.20547945e+00,  2.21153521e+00,
          2.85973233e+00,  2.78986202e+00,  3.00726281e+00,  1.87547385e+00,
          3.35057513e+00,  2.85699835e+00,  1.93367325e+00,  2.69641412e+00,
          3.05890468e+00,  3.92019342e+00,  3.26093777e+00,  2.97155482e+00,
          3.71120292e+00,  4.21768326e+00,  3.46825956e+00,  5.11902292e+00,
          4.10349687e+00,  3.34056219e+00,  3.35658557e+00,  2.74139107e+00,
          2.80840891e+00,  2.56844500e+00,  2.87384848e+00,  3.01045085e+00,
          1.59218471e+00,  2.99434495e+00,  2.33486893e+00,  2.69356631e+00,
          2.48867673e-01,  3.51014826e-01,  8.83541262e-01,  9.98752858e-01,
          1.04097410e+00,  5.12321310e-01,  3.07829067e-01,  3.02464291e-01,
          6.72071277e-01,  6.56986117e-01,  2.74611977e-01,  9.10525313e-01,
          2.29955362e+00,  1.70714782e+00,  2.04240299e+00,  2.27506784e+00,
          1.69816195e+00,  1.26523199e+00,  9.96898353e-01,  1.86681879e+00,
          9.85716040e-01,  8.91465919e-01,  9.40545139e-01,  6.51000326e-01,
          8.77504604e-01,  1.27916933e+00,  1.48674618e+00,  1.31469071e+00,
          1.27295608e+00,  1.60363977e+00,  1.26076403e+00,  7.42391432e-01,
          1.04473984e+00,  8.56102544e-01,  1.29046497e+00,  1.17577427e+00,
          8.08673096e-01,  1.11361790e+00,  1.78701902e+00,  3.76638278e-01,
          7.69230769e-01,  1.03616490e+00,  7.58045969e-01,  9.69831087e-01,
          1.02765642e+00,  5.56890099e-01, -5.34506901e-02, -5.55662383e-01,
         -7.37462087e-01,  6.96250345e-01, -2.26778684e-01,  1.32116740e-01,
         -7.85597540e-01, -3.57268946e-01, -1.44849199e-01,  7.82150847e-02,
          8.96663644e-02,  1.76951023e-01,  4.58764277e-01,  2.08854532e-01,
          1.74647183e-01,  3.88031953e-01,  2.27211881e-01,  4.17106507e-01,
          1.03514209e+00,  1.34102009e+00,  9.45410792e-01,  9.15447749e-01,
          8.99762872e-01,  8.95498091e-01,  1.68679534e+00,  1.35511415e+00,
          2.18000479e+00,  2.18956233e+00,  1.87153746e+00,  2.03372336e+00,
          1.12891556e+00,  1.54425112e+00,  1.08510351e+00,  1.02135395e+00,
          2.97851164e+00,  2.64847596e+00,  2.93404692e+00,  3.19215322e+00,
          3.28464708e+00,  3.63505877e+00,  3.62933660e+00,  3.75417354e+00,
          5.17454890e+00,  4.90813745e+00,  4.57745046e+00,  3.69352137e+00,
          3.76950741e+00,  3.85952919e+00,  4.40710938e+00,  3.99083568e+00,
          4.24110595e+00,  3.45268484e+00,  2.67443156e+00,  2.70817594e+00,
          3.33639488e+00,  2.50521843e+00,  1.46918074e+00,  7.82302410e-01,
          1.09619108e+00,  6.40524996e-01, -2.74545789e-01, -5.64518661e-01,
         -2.93323841e-02, -6.64189196e-02, -1.43988493e-01, -1.60915525e-01,
         -7.41828231e-02,  4.61445690e-01, -5.91200389e-01, -1.27093436e+00,
         -1.31875064e+00, -9.21829268e-01, -6.43491828e-01, -7.90756289e-01,
         -1.78714482e+00, -9.85144809e-01, -9.92323045e-01, -5.88295523e-02,
         -9.01504014e-01,  2.03113280e-01,  1.92097617e-01,  5.76823009e-01,
          1.27872351e+00,  7.65524196e-01,  7.58559144e-01,  1.85280493e+00,
          2.16756477e+00,  2.16198479e+00,  2.17085833e+00,  1.06108390e+00,
          1.82912014e+00,  1.19754555e+00,  4.21775192e-01,  5.56093432e-01,
          4.16386586e-01,  5.56193785e-01,  4.17849690e-01,  1.37073499e-01,
          1.05168379e-01,  2.07732133e-01, -2.25934619e-02, -5.36479936e-01,
         -7.37462087e-01, -6.86071233e-01,  6.16699793e-01,  4.37672502e-01,
          6.36284763e-02,  1.03913396e+00,  1.85321228e+00,  1.96941301e+00,
          2.06166078e+00,  1.92239851e+00,  1.87311114e+00,  2.78695592e+00,
          2.60904547e+00,  2.33850209e+00,  1.97206956e+00,  1.95434592e+00,
          2.03314426e+00,  2.20283344e+00,  2.89938769e+00]),
  array([ 1.84578893e+00,  3.02339214e+00,  2.78812516e+00,  2.80231692e+00,
          3.07757671e+00,  1.60870443e+00,  1.94781623e+00,  1.18304696e-01,
          2.85350550e-01,  9.73070374e-02,  1.79605302e-01,  1.30449000e+00,
          9.73859612e-01,  8.20703444e-01,  1.93632135e+00,  1.97005755e+00,
          2.08734328e+00,  1.66326625e+00,  3.46218536e-01,  8.11083719e-01,
          7.40475637e-01, -3.29166904e-01,  6.14527058e-01, -1.99046857e-02,
         -5.11651207e-03,  7.98332075e-01,  4.62859504e-02,  4.39462543e-01,
          9.42809042e-01,  1.32582493e+00,  1.21159175e+00,  9.31330732e-02,
          8.27930928e-01,  4.49733342e-01,  1.68002577e-01,  6.82433804e-01,
          2.16199850e+00,  1.23108098e+00,  2.04875916e+00,  1.69717816e+00,
          1.74535574e+00,  8.39501947e-01,  1.22227641e+00,  5.10747313e-01,
          1.45595077e+00,  2.02166221e+00,  1.73291055e+00,  2.75994080e+00,
          2.37898991e+00,  1.58912321e+00,  1.46339351e+00,  2.70722715e+00,
          2.56521057e+00,  3.19712851e+00,  2.23634670e+00,  9.28279122e-01,
         -7.86599827e-01,  1.31475147e+00,  1.63897328e+00,  6.95127533e-01,
          2.21148711e+00,  1.78974418e+00,  1.58471909e+00,  1.33610984e+00,
          1.33484762e+00,  9.80444339e-01,  1.17448052e+00,  1.68776879e+00,
          6.96440909e-01,  1.43019388e+00,  6.25663725e-01,  8.98192640e-01,
         -1.72067576e-01,  6.72071277e-01,  7.78033610e-01,  1.20079859e+00,
          1.39891306e+00,  2.84130380e-01,  2.61921094e-01,  1.24121837e+00,
         -2.78959666e-01, -4.94421055e-01, -1.34544998e-01,  4.77712457e-01,
         -6.96310624e-01, -6.88610147e-01, -8.73192003e-01, -6.01486991e-01,
          1.06819076e-01, -9.95549018e-01, -1.89594517e-01,  8.83703557e-01,
          2.05911471e+00,  1.91112770e+00,  2.16905829e+00,  2.31183464e+00,
          2.48647972e+00,  2.88169617e+00,  2.78049471e+00,  2.78224952e+00,
          3.08278622e+00,  3.29564786e+00,  3.43042568e+00,  3.42759084e+00,
          3.65731482e+00,  3.51743542e+00,  3.73617028e+00,  4.01351963e+00,
          4.41049185e+00,  4.46080278e+00,  6.49905030e+00,  5.22009513e+00,
          5.70010511e+00,  3.11728347e+00,  3.57588161e+00,  3.63142097e+00,
          2.90101088e+00,  2.86146290e+00,  2.57719254e+00,  2.50871540e+00,
          2.68024139e+00,  3.03028979e+00,  3.45662006e+00,  4.42605852e+00,
          4.37398899e+00,  2.84801091e+00,  3.14535872e+00,  3.32511385e+00,
          2.96972086e+00,  3.98066356e+00,  2.06598468e+00,  2.93815765e+00,
          3.33135032e+00,  3.26450861e+00,  3.24253732e+00,  3.14865658e+00,
          2.34989035e+00,  2.96029352e+00,  2.54356648e+00,  1.27110921e+00,
          6.98411740e-01,  1.50323054e+00,  4.11657147e-01,  4.36775566e-01,
         -5.00030637e-01, -8.21583836e-01,  3.84722602e-01,  1.60356745e+00,
          1.85987599e+00,  7.71059680e-01,  1.29824561e+00,  2.74946896e+00,
          2.15495056e+00,  6.00245048e-01,  4.63326369e-01,  1.32114298e+00,
          1.22685905e+00,  1.04130784e+00,  1.43152708e+00,  1.20535511e+00,
          1.49691040e+00,  1.87308843e+00,  1.54170699e+00,  1.08456198e+00,
          1.49611627e+00,  1.30187763e+00,  1.61532039e+00,  1.19136679e+00,
          6.26099034e-01,  1.05317749e-01, -4.32417536e-02, -4.75633081e-01,
         -1.28079029e+00,  1.09378857e+00, -1.26635403e+00, -4.85000222e-01,
          1.67466620e+00,  3.23382283e-01,  4.18729130e-01,  2.31138372e+00,
          1.80054356e+00,  2.87820967e+00,  2.97085669e+00,  1.10331088e+00,
          2.50279733e+00,  1.41448644e+00,  2.61656202e+00,  1.66654208e+00,
          1.77081589e+00,  1.97605176e+00,  1.41594947e+00,  1.54948627e+00,
          1.19404463e+00,  1.43672194e+00,  2.29512766e+00,  1.98338803e+00,
          1.68556593e+00,  1.13562040e+00,  2.08122361e+00,  2.16266909e+00,
          1.73408401e+00,  1.63147460e+00,  1.84273191e+00,  2.88887005e+00,
          3.67582431e+00,  3.99275065e+00,  2.88139860e+00,  2.58649827e+00,
          3.86511668e+00,  2.36415360e+00,  2.98347136e+00,  2.96648379e+00,
          2.85515258e+00,  3.63137496e+00,  3.24743634e+00,  3.34845152e+00,
          2.13600501e+00,  2.51981323e+00,  2.06765170e+00,  1.73563689e+00,
          2.18224287e+00,  3.54578744e+00,  1.96965108e+00,  1.40739309e+00,
          1.74081257e+00,  3.17220634e-01,  2.03246213e+00,  2.53034912e+00,
          1.89624489e+00,  2.11051052e+00,  2.29444574e+00,  2.75806624e+00,
          2.78906106e+00,  2.45460579e+00,  2.69167705e+00,  2.51933715e+00,
          3.28248715e+00,  2.06937433e+00,  2.20951593e+00,  3.50727342e+00,
          4.19336681e+00,  3.16118401e+00,  3.07644247e+00,  2.95656509e+00,
          2.59624005e+00,  1.74339144e+00,  2.28852677e+00,  1.95949995e+00,
          2.42579837e+00,  1.98737215e+00,  1.84032337e+00,  1.41624705e+00,
          1.03215862e+00,  5.46236685e-01,  7.05893519e-01,  6.34606046e-01,
          1.90935682e-02, -3.25759810e-01,  1.42678980e-01,  3.46190687e-01,
          1.96176027e-01, -4.56238792e-01, -6.86406473e-01,  2.49907596e-01,
          4.06399150e-01,  1.03312771e+00,  8.56987639e-01,  5.43385532e-01,
          1.98165441e-01,  1.13117461e+00,  2.95926363e+00,  1.97058711e+00,
          3.17095499e+00,  2.60076434e+00,  2.12746895e+00,  2.17451084e+00,
          1.83854963e+00,  3.25962835e+00,  3.55489755e+00,  3.65237667e+00,
          3.55892918e+00,  3.48092794e+00,  3.17698106e+00,  2.65148581e+00,
          2.84653741e+00,  1.59989861e+00,  6.41373015e-01,  8.32195466e-01,
          9.88086231e-01,  9.34451972e-01,  1.69997991e+00,  1.72906663e+00,
          1.57165358e+00,  2.35501840e+00,  2.25615376e+00,  1.32101528e+00,
          1.49278098e+00,  1.87411397e+00,  1.91398796e+00,  1.10214917e+00,
          3.34422433e+00,  3.07149564e+00,  4.45507568e+00,  4.84210863e+00,
          3.41919434e+00,  3.39339349e+00,  4.09704469e+00,  4.03065040e+00,
          4.36248945e+00,  3.30366513e+00,  2.40423791e+00,  2.99840705e+00,
          2.62584784e+00,  3.09376344e+00,  3.38504159e+00,  3.82389198e+00,
          4.28630867e+00,  3.01511345e+00,  2.97427187e+00,  3.33110181e+00,
          2.51041444e+00,  1.40739309e+00,  2.22957554e+00,  2.26501495e+00,
          2.20932648e+00,  2.38665667e+00,  1.96099608e+00,  1.93626760e+00,
          1.38218948e+00,  2.92977026e+00,  2.70064291e+00,  2.66077926e+00,
          2.79806369e+00,  3.95160658e+00,  2.95436465e+00,  1.87841983e+00,
          2.13188392e+00,  1.90841353e+00,  1.26062845e+00,  1.66540833e+00,
          1.04677320e+00,  1.07052872e+00,  3.76146088e+00,  3.22444524e+00,
          2.51153263e+00,  2.83289736e+00,  2.03434710e+00,  2.12906037e+00,
          2.78854189e+00,  2.52086172e+00,  2.56521057e+00,  2.18654226e+00,
          3.00171728e+00,  2.16091203e+00,  1.21280689e+00,  2.35716142e+00,
          2.53488285e+00,  2.26129244e+00,  2.23978645e+00,  2.60401272e+00,
          3.15085897e+00,  2.56000122e+00,  2.93324424e+00,  1.17932379e+00,
          1.53212340e+00,  1.68510844e+00,  2.41897263e+00,  2.34532272e+00,
          2.98814975e+00,  2.93999158e+00,  2.39365788e+00,  1.89148636e+00,
          2.54130846e+00,  2.74410650e+00,  1.98949269e+00,  1.98340368e+00,
          1.73975294e+00,  2.40852809e+00,  2.34947989e+00,  1.50384996e+00,
          1.51548781e+00,  2.01546290e+00,  1.33465454e+00,  1.72378015e+00,
          1.62832672e+00,  1.61928503e+00,  9.01127353e-01,  1.00180287e+00,
          2.08905892e-01,  9.64333735e-01,  1.87849024e-01,  2.09188978e-01,
         -1.88537572e-01,  4.67251096e-01,  4.51795864e-02, -6.42313767e-01,
          3.65588173e-01,  4.53636728e-01, -5.74771615e-01, -5.29285777e-01,
          4.02863797e-01, -7.61591867e-02,  1.21086863e+00,  1.82352941e+00,
          8.16295051e-01,  1.40608602e+00,  2.41508576e+00,  1.74332936e+00,
          1.88231686e+00,  1.84917723e+00,  1.71733360e+00,  2.62817581e+00,
          2.63074376e+00,  3.34953830e+00,  4.43680876e+00,  3.82893240e+00,
          3.59501140e+00,  3.60077604e+00,  3.74102961e+00,  3.31937206e+00,
          3.20722468e+00,  2.22374795e+00,  1.69999709e+00,  3.03153814e+00,
          2.30280655e+00,  8.51649179e-01,  1.35231384e+00,  1.56530126e+00,
          2.03518867e+00,  1.07443268e+00,  6.40171365e-01,  4.31156567e-01,
          1.00748317e-01,  3.30183793e-01, -7.22626518e-01,  4.12893079e-01,
         -5.98684340e-02,  2.92227725e-01,  7.39640567e-01,  7.87058817e-01,
          1.00797185e+00,  4.83000258e-01,  5.25485752e-01,  8.47382622e-02,
         -1.02641944e-01,  4.83361605e-01,  1.01417452e+00,  1.33690278e+00,
          1.14396979e+00,  8.10498825e-01,  9.76249051e-01,  1.30206853e+00,
          1.19281412e+00,  1.21885057e+00,  9.23077657e-01,  6.20302421e-01,
          3.57114625e-02,  2.61805500e-01,  1.50550516e-01, -2.92660269e-01,
          3.24511798e-01, -2.39114050e-02,  3.07937204e-01,  3.04751836e-01,
          8.54957091e-01,  8.77727474e-01,  5.00050080e-01,  1.28384669e-01,
          1.56642147e+00,  2.06071823e+00,  1.93410031e+00,  1.35169067e+00,

In [8]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

563
563
563
=
1689

,gpt_layer,WER,BLEU,METEOR,BERT
0,3,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,4,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,5,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [4]:
results_df

,gpt_layer,WER,BLEU,METEOR,BERT
0,6,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,7,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."

In [9]:
gpt_layer_6=np.array(results_df.loc[0, 'BERT']).mean()
gpt_layer_7=np.array(results_df.loc[1, 'BERT']).mean()
gpt_layer_8=np.array(results_df.loc[2, 'BERT']).mean()
gpt_layer_9=np.array(results_df.loc[3, 'BERT']).mean()
gpt_layer_10=np.array(results_df.loc[4, 'BERT']).mean()
to_file = pd.DataFrame({'gpt_layer':[3,4,5,8,10], 'significantly_decoded': [gpt_layer_6,gpt_layer_7,gpt_layer_8,gpt_layer_9,gpt_layer_10]})
to_file.to_csv('perceived_speech_gpt_words.csv', index=False)

to_file

   gpt_layer  significantly_decoded
0          3               0.646536
1          4               0.658970
2          5               0.619893
3          8               0.648313
4         10               0.619893