In [1]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('../scores/S1/perceived_speech/gpt_layer_7/wheretheressmoke.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('wheretheressmoke', 'WER'): np.float64(9.382415796015598), ('wheretheressmoke', 'BLEU'): np.float64(7.924743532248992), ('wheretheressmoke', 'METEOR'): np.float64(8.182272810645832), ('wheretheressmoke', 'BERT'): np.float32(16.221134)}

In [2]:
window_zscores = {'gpt_layer': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for gpt_layer in [6,7,8,9,10]:
    for task in ['wheretheressmoke']:
        scores = np.load(f'../scores/S1/perceived_speech/gpt_layer_{gpt_layer}/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['gpt_layer'].append(gpt_layer)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'gpt_layer': [6, 7, 8, 9, 10],
 'WER': [array([ 4.69308215e-01,  1.26151726e-01,  7.13331718e-01,  4.87428668e-01,
          7.77288332e-01,  7.52299349e-01,  1.09093577e+00,  7.00676918e-02,
          2.62995955e-01, -8.50442530e-01, -6.66038927e-01,  6.11635715e-01,
          1.21033782e+00,  1.93295005e+00,  1.12010367e+00,  2.19824211e-01,
          1.38102392e+00,  8.18043856e-01,  5.66138517e-01,  8.26106919e-01,
          9.04362947e-01,  8.30727930e-01,  1.61385069e+00,  1.81248371e+00,
          1.84580280e+00,  2.73087154e+00,  1.76086985e+00,  2.14210587e+00,
          1.75810590e+00,  2.14936732e+00,  1.17088579e+00,  8.29331871e-01,
          9.48852411e-01,  1.20329570e+00,  8.30652340e-01,  1.36380784e+00,
          1.76162454e+00,  2.04974032e+00,  1.42331331e+00,  1.88883558e+00,
          1.32865422e+00,  1.00462323e+00,  1.29042969e+00,  1.19596218e+00,
          1.55445553e+00,  7.94798602e-01,  5.11465902e-01,  7.41881120e-01,
          1.08459413e+00,  1.92450090e-01,  8.81336990e-01,  1.03816362e+00,
          1.04492102e+00,  1.64750894e+00,  1.41973027e+00,  9.18348458e-01,
          6.38396103e-01,  1.57082878e+00,  4.86533633e-01,  1.11342240e+00,
          2.47832610e+00,  2.88945838e+00,  2.74562424e+00,  3.78590122e+00,
          2.35233561e+00,  1.82470552e+00,  2.09410187e+00,  1.45450350e+00,
          5.45227959e-01,  4.31011312e-01, -3.19398048e-01, -1.01744616e-01,
          5.97057039e-01,  4.64478893e-01, -1.46855037e-01,  1.37130294e-01,
          3.28810283e-01,  3.37106771e-01,  2.09905600e+00,  2.56737719e-01,
          7.13509186e-01,  4.02828622e-01, -1.09568058e-01, -4.61965772e-01,
          2.25646841e-01,  2.02272654e-01,  8.81626715e-01,  1.04014062e+00,
          1.23403510e-01,  7.52617809e-01,  1.32581290e+00,  9.39793423e-01,
          1.15092725e+00,  1.20915635e+00,  1.37706075e+00,  2.34980228e+00,
          1.86760995e+00,  1.52786117e+00,  3.48192406e-01,  2.93835348e-01,
          8.75251473e-01,  1.02454353e+00,  6.07013035e-01,  5.43104402e-01,
         -9.19245152e-02,  2.54198059e-01,  5.04878164e-01,  7.38105125e-01,
          9.96547314e-01,  3.19455620e-01, -4.95470921e-01, -5.83061830e-01,
         -2.66301328e-02, -5.09540696e-01,  1.09748613e-01,  2.07599001e+00,
          2.32628996e-01,  1.15813205e+00,  1.72195340e+00,  1.80230851e+00,
          3.19003453e-02,  2.98210026e-01,  9.09090909e-02,  1.31065028e+00,
          1.17323857e+00,  1.38419707e+00,  1.65695123e+00,  1.90363454e+00,
          1.54860717e+00,  1.53160153e+00,  2.07301659e+00,  1.40754634e+00,
          2.58045369e+00,  2.68569251e+00,  1.78902871e+00,  2.24728271e+00,
          3.14494034e+00,  2.97938560e+00,  2.57138926e+00,  2.19693648e+00,
          2.48965203e+00,  4.52167704e+00,  2.10331413e+00,  2.76793078e+00,
          2.74468085e+00,  3.16807739e+00,  1.52830919e+00,  2.63899847e+00,
          1.84485279e+00,  2.60146574e+00,  2.07981181e+00,  1.89105056e+00,
          1.75822114e+00,  2.20940946e+00,  1.94716087e+00,  1.90349354e+00,
          2.60876078e+00,  1.59276253e+00,  2.02728019e+00,  1.98584372e+00,
          2.13695757e+00,  7.87426962e-01,  5.50532056e-01,  9.57816982e-01,
          1.21662382e+00,  1.13195335e+00,  5.14165439e-01,  8.92393999e-01,
          1.43423165e+00,  8.47168128e-01,  7.79705359e-01,  6.08695652e-01,
          9.29981110e-01,  2.70303256e-01, -1.27017059e+00, -4.09303633e-01,
          2.34082294e-01,  1.57366477e+00,  1.66622046e+00,  1.04130825e+00,
          7.58266774e-01,  8.31633315e-01,  1.62759499e+00, -1.14294283e-01,
          1.52321131e+00,  1.49076934e+00,  8.77519930e-01,  1.60678934e+00,
          9.66021859e-01,  1.12695123e+00,  1.36825240e+00,  6.03194004e-01,
          2.72963918e-01, -2.89928763e-01,  5.55027299e-01,  3.36801803e-01,
          4.40652649e-02,  2.85682705e-01,  1.47480734e+00,  1.46209854e+00,
          2.58290969e+00,  2.50565793e+00,  2.63353581e+00,  2.84198321e+00,
          1.66523397e+00,  1.79624663e+00,  1.33609415e+00,  1.95769930e+00,
          8.83892284e-01,  8.08676874e-01,  1.44008140e+00,  2.15614117e+00,
          1.87380082e+00,  2.14156433e+00,  2.11800773e+00,  3.08306944e+00,
          3.16684950e+00,  2.25389037e+00,  1.83560482e+00,  1.83593170e+00,
          2.22076266e+00,  1.25346701e+00,  1.81710946e+00,  1.64817961e-01,
          3.02190425e-01,  2.18975643e-01,  7.52573245e-01,  1.29175239e+00,
          1.57905559e+00,  1.07498132e+00,  1.77566538e+00,  2.85411548e-01,
          3.83130514e-01,  2.11999576e+00,  4.92835404e-01,  1.09619108e+00,
          1.44505710e+00,  2.06816092e+00,  8.45751115e-01,  1.98003679e+00,
          1.85142830e+00,  1.78122272e+00,  2.37019936e+00,  2.30946035e+00,
          1.95522698e+00,  1.74916109e+00,  2.38445481e+00,  1.95251906e+00,
          2.54046139e+00,  2.77904690e+00,  2.57736609e+00,  2.38174779e+00,
          2.76322835e+00,  1.48607761e+00,  1.61124774e+00,  8.14272210e-01,
          1.03503319e+00,  1.65154990e+00,  2.93639776e-01,  6.82195066e-01,
          1.30662158e+00,  6.96048941e-01,  3.47960103e-01,  4.04061018e-01,
          5.84158961e-01,  3.11017265e-01,  1.15222016e+00,  8.37490121e-01,
          4.06840754e-01, -6.19134288e-01,  4.03958832e-01,  5.80723580e-01,
         -1.08593818e-01,  3.71223452e-01,  7.46830487e-01,  1.61750174e+00,
          4.33058324e-01,  4.41128773e-01,  1.24402737e+00,  5.93735796e-01,
          1.90268890e+00,  1.87584637e+00,  1.62935552e+00,  2.38042316e+00,
          3.20943175e+00,  2.72028211e+00,  2.61137137e+00,  2.75717830e+00,
          3.04026101e+00,  2.87513190e+00,  2.51282529e+00,  3.09660672e+00,
          2.92764907e+00,  3.01075915e+00,  2.05823527e+00,  2.00301616e+00,
          2.13283489e+00,  1.76607955e+00,  1.80492413e+00,  2.71836047e+00,
          3.36006084e+00,  5.97443631e-01,  2.92420788e+00,  2.15994262e+00,
          1.76526589e+00,  3.18639956e+00,  2.20139816e+00,  2.17581548e+00,
          2.37500000e+00,  2.35010870e+00,  2.34911870e+00,  3.03796206e+00,
          2.65758913e+00,  3.08842237e+00,  2.26796275e+00,  1.45893251e+00,
          2.07138066e+00,  2.05607229e+00,  8.81737934e-01,  3.11495471e+00,
          1.57777112e+00,  1.23019747e+00,  1.32682288e+00,  1.38639777e+00,
          2.14383503e+00,  7.82136495e-01,  1.05402413e+00,  1.05749107e+00,
          1.43925965e+00,  1.16803166e+00,  2.21951113e-01,  8.59048401e-02,
          9.51577040e-01,  5.88426978e-01,  4.37004151e-01, -4.29540742e-03,
          1.74620847e-01,  1.84309113e+00,  2.08482708e+00,  1.59148698e+00,
          8.51399680e-01,  9.55333842e-01,  5.58179523e-01,  3.19421317e+00,
          3.81883851e+00,  2.74613526e+00,  2.29776942e+00,  3.43061633e+00,
          2.89820675e+00,  3.51222862e+00,  2.31732764e+00,  2.90925888e+00,
          2.85461197e+00,  3.15952998e+00,  3.49937926e+00,  2.14374169e+00,
          1.41791086e+00,  1.85294118e+00,  2.42461858e+00,  2.67920384e+00,
          2.53655516e+00,  2.72093809e+00,  3.02492523e+00,  3.01678804e+00,
          2.62874281e+00,  2.85915493e+00,  2.31585538e+00,  1.51167395e+00,
          2.01025524e+00,  2.00182814e+00,  1.66477792e+00,  1.06195842e+00,
          1.21413655e+00,  1.32638667e+00,  1.23109771e+00,  1.33734729e+00,
          2.31342772e+00,  2.21876177e+00,  1.58484242e+00,  2.03268504e+00,
          6.87154024e-01,  3.93579511e-01,  4.44395635e-01, -5.37498053e-01,
          8.16551810e-01,  8.38354670e-01,  1.34185742e-01,  1.81860711e-01,
          9.60834166e-01,  1.63767945e+00,  1.68509067e+00,  1.70515231e+00,
          2.24212960e+00,  1.76607495e+00,  2.03144779e+00,  2.20723495e+00,
          1.85662659e+00,  1.92222661e+00,  2.27092439e+00,  2.60180012e+00,
          1.93956303e+00,  2.80255039e+00,  3.52752180e+00,  3.21832688e+00,
          3.28912572e+00,  3.83938846e+00,  3.75267766e+00,  3.65734149e+00,
          2.39595792e+00,  2.37189235e+00,  2.21923722e+00,  1.90015899e+00,
          2.59328174e+00,  2.49817174e+00,  2.41316414e+00,  2.67463762e+00,
          2.23502243e+00,  2.27314041e+00,  1.53215123e+00,  1.79825917e+00,
          1.61619833e+00,  1.54070578e+00,  1.50048683e+00,  6.03989610e-01,
          3.98255235e-01, -1.51487442e-01, -3.66039134e-01, -1.29207536e-01,
         -6.90330360e-01, -1.65963557e+00, -1.84615385e+00, -1.22554158e+00,
         -1.55924427e+00, -1.37250135e+00, -2.30567051e+00, -2.07205296e+00,
         -1.74154307e+00, -5.87572403e-01, -1.35942976e-01, -1.13612729e-01,
         -8.60549634e-01,  5.70148629e-01, -9.95797498e-01, -7.48968731e-01,
         -8.90081903e-01, -1.02218143e+00, -4.32388202e-01, -7.59017359e-01,
         -1.12153454e+00, -5.96950739e-01, -1.88541782e+00, -9.26758897e-01,
         -7.98081408e-01, -1.43500561e+00, -1.06921695e+00, -1.34084338e+00,
         -7.60258589e-01, -1.11157240e+00, -1.84141455e+00, -1.81707563e+00,
         -9.94936676e-01,  1.79560979e-01, -2.13401700e-01,  4.08319112e-01,
          3.32694396e-01,  3.78978305e-01,  6.18957086e-01,  8.55092549e-01,
          1.00137120e+00,  8.69616671e-01,  5.98443944e-01,  1.32345961e+00,
          3.66057079e-01,  1.64485063e+00,  2.02300696e+00,  2.63910942e+00,
          2.43442127e+00,  2.76798441e+00,  3.05125373e+00,  3.22150393e+00,
          2.47578453e+00,  9.62575979e-01,  1.00850874e-01,  1.30228193e+00,
          1.64473348e+00,  1.38457860e+00,  1.62027538e+00,  2.48282838e+00,
          1.63982450e+00,  1.81548129e+00,  1.72996299e+00,  1.53151299e+00,
          1.73061308e+00,  1.39256391e+00,  1.21500621e+00,  6.67053263e-01,
          4.70631599e-01,  1.88288660e+00,  1.65393934e+00,  1.54917229e+00,
          4.33738197e-01,  6.78125368e-01,  1.12445786e+00,  8.39772999e-01,
          6.81090618e-01,  1.43487507e+00,  2.12927082e+00,  1.33978769e+00,
          8.22326584e-01,  4.74161082e-01,  2.90179273e-01,  1.20500252e+00,
          3.69303517e-01,  6.49790691e-01,  1.80352041e+00,  1.66067564e+00,
          2.40430617e+00,  1.72086040e+00,  1.79526820e+00,  1.74133801e+00,
          1.59325771e+00,  1.88996506e+00,  1.10789669e+00,  1.42927350e+00,
          3.18980761e-01, -1.66783977e-01, -8.68960885e-01, -4.89067674e-01,
          6.58416361e-01,  6.45599869e-01,  6.75737378e-01,  1.06838502e+00,
          1.07307917e+00, -3.67307177e-01, -3.67109085e-01,  6.44730600e-01,
          4.87538090e-01, -2.66160394e-01,  1.16131241e+00,  1.17884549e-01,
          1.10276041e+00,  1.65757216e-01,  1.69538515e+00,  1.20181575e+00,
          2.57185098e+00,  2.72496135e+00,  3.57308582e+00,  2.60678980e+00,
          3.85421040e+00,  4.19274080e+00,  3.85192110e+00,  2.97804195e+00,
          3.20532752e+00,  3.08171321e+00,  1.92673931e+00,  1.78996959e+00,
          2.57115624e+00,  1.37955551e+00,  1.01157923e+00,  1.01856683e+00,
          1.13449850e+00,  1.20064096e+00,  1.01187645e+00]),
  array([ 1.20215673e+00,  1.58586736e+00,  1.35628539e+00,  1.18913911e+00,
          1.56842533e+00,  1.55015307e+00,  3.44352649e-01,  8.61175113e-01,
          1.09237992e+00,  1.02816773e+00,  2.90421715e-01,  1.50964842e+00,
          1.86500962e-01, -5.78888020e-02,  1.06937416e+00,  1.19754713e+00,
          4.55135959e-01,  8.11473757e-01,  4.36927694e-01,  1.92094429e+00,
          8.66471234e-01,  8.40099985e-01,  2.75354387e+00,  3.07177698e+00,
          3.04186316e+00,  1.09050920e+00,  1.10149945e+00,  1.59121263e+00,
          2.67554780e+00,  2.24582291e+00,  1.23198297e+00,  1.63518813e+00,
          9.23140360e-01,  4.54878210e-01,  8.05202862e-01,  5.44279152e-01,
          1.53587017e+00,  1.23562461e+00,  1.84288535e-01, -5.94438298e-02,
         -9.23623608e-02, -4.72537268e-01, -8.22582176e-01,  3.69524209e-01,
         -3.34451902e-03,  1.45119014e+00,  3.19283944e+00,  2.09778599e+00,
          2.45533108e+00,  2.62767504e+00,  3.39270682e+00,  3.04724700e+00,
          2.06965261e+00,  4.38269324e+00,  5.25956994e+00,  7.08243152e+00,
          8.19857001e+00,  4.38722430e+00,  3.83487030e+00,  5.29193862e+00,
          4.64990555e+00,  4.71877676e+00,  4.68374538e+00,  3.66273887e+00,
          3.45525458e+00,  2.08459505e+00,  1.27208203e+00,  5.74384046e-01,
         -4.47543584e-01, -4.06261669e-01, -1.19811061e+00, -8.13574243e-01,
         -9.23203178e-01, -1.00253292e+00, -9.19565017e-01, -6.33750222e-01,
         -4.13982920e-01, -5.79757559e-01,  1.37352745e+00,  1.35764635e+00,
          2.01552980e+00,  1.53357247e+00,  2.23347121e+00,  6.82070499e-01,
          3.87085393e-01,  2.84021580e-01,  1.20031359e-01,  3.84432314e-01,
          2.48303460e-01,  8.55029213e-01,  5.79324122e-01,  8.70178640e-01,
          1.26230921e+00,  2.73503744e+00,  2.16666667e+00,  2.31274733e+00,
          2.39614507e+00,  2.33253026e+00,  2.74675670e+00,  3.48139770e+00,
          2.31046105e+00,  2.41534463e+00,  2.73812198e+00,  2.60654308e+00,
          2.00712875e+00,  1.60891934e+00,  1.80100002e+00,  2.01543762e+00,
          2.39223155e+00,  2.33839669e+00,  2.42858833e+00,  3.07622892e+00,
          2.97670315e+00,  2.87256775e+00,  2.37263705e+00,  2.47028546e+00,
          3.37879482e+00,  2.80840891e+00,  1.56376233e+00,  1.57969969e+00,
          1.60168736e+00,  1.84048595e+00,  2.36643191e+00,  2.50710605e+00,
          2.64222207e+00,  1.94266695e+00,  8.91831503e-01,  1.17634340e+00,
          8.04886122e-01,  1.66729078e+00,  5.40565376e-01,  7.47794502e-01,
          1.12443304e+00,  1.81956005e+00,  1.65636001e+00,  1.36153468e+00,
          1.55249967e+00,  1.31232493e+00,  8.57969178e-01,  1.38703942e+00,
          1.73609912e+00,  9.82061692e-01,  1.65629935e+00,  1.92693733e+00,
          8.17648145e-01,  1.41169545e+00,  1.85043339e+00,  1.87113279e+00,
          1.18423727e+00,  1.12247216e+00,  1.55906979e+00,  1.46120933e+00,
          6.00192092e-01,  2.11197157e+00,  2.67575253e+00,  1.50887623e+00,
          1.57011894e+00,  1.27361216e+00,  7.35485120e-01,  6.46002999e-01,
          7.68364116e-01,  2.41738880e-01,  6.63167080e-01,  1.02377621e+00,
          1.38430910e+00,  4.21765501e-01,  7.12807301e-01,  1.12452039e+00,
         -1.19009728e-01,  1.64260792e-01, -2.11951668e-15, -4.49358517e-01,
         -1.57277402e-01, -1.64519042e+00, -1.16554303e+00, -1.43072239e+00,
          3.83130514e-01, -8.70069292e-01, -8.21336793e-01, -1.05091190e+00,
         -2.40170404e-01, -2.38405582e-01, -8.24344081e-01,  1.27844315e+00,
         -3.78262317e-01,  7.40868907e-01,  4.63406823e-02,  1.28316226e-01,
          3.02950401e-01,  4.81997470e-01, -2.17661811e-01, -1.72905403e-01,
          3.95056153e-01, -1.26082930e-01,  1.69051388e+00,  1.50389647e+00,
          1.03750359e+00,  3.66414670e-01,  6.76261691e-01,  9.79977426e-01,
          1.38419707e+00,  2.05216912e+00,  1.32581290e+00,  3.15408309e+00,
          2.61076722e+00,  3.60413167e+00,  2.58198890e+00,  3.16152116e+00,
          3.92083460e+00,  3.02686965e+00,  2.83163942e+00,  3.40935119e+00,
          2.94838051e+00,  3.20494851e+00,  3.14496966e+00,  2.50372038e+00,
          2.79330410e+00,  3.31017595e+00,  1.97183119e+00,  1.72726235e+00,
          2.22083373e+00,  2.42561512e+00,  2.78483736e+00,  2.33486893e+00,
          3.10528519e+00,  1.66416310e+00,  9.49419869e-01,  1.55180265e+00,
          9.39497925e-01,  2.97760500e-01,  1.06458755e+00,  4.24716566e-01,
          5.46808819e-01, -1.21460559e+00,  1.59591607e+00,  2.52056346e-02,
          7.06854583e-01,  8.63824573e-01,  8.89364272e-01,  5.10706929e-01,
          3.29430146e-01,  1.62004135e+00,  1.54377154e+00,  2.16170975e+00,
          1.95974491e+00,  1.75868656e+00,  2.18025228e+00,  1.85955892e+00,
          2.32656116e+00,  1.10038779e+00,  2.36127681e+00,  2.16132157e+00,
          1.85312329e+00,  2.09090909e+00,  1.59937380e+00,  2.26455209e+00,
          1.76465312e+00,  1.22105095e+00,  9.27505653e-01,  1.29350185e+00,
          1.04446594e+00,  4.73496872e-01,  2.31406128e-01,  3.02368589e-01,
          1.51260101e+00,  1.20303331e+00,  1.01090053e+00,  5.74728320e-01,
          1.07165176e+00,  1.33344816e+00,  3.64009383e-01,  1.60900808e+00,
          1.75852783e+00,  1.21505370e+00,  7.26004023e-01,  7.33511907e-01,
         -2.02794391e-01, -1.83280472e-01,  5.73048384e-01,  6.67431292e-02,
          7.95769679e-01,  7.35944424e-02, -3.64044429e-02,  6.04394436e-01,
          1.20280818e+00,  1.45232164e+00,  1.16037415e+00,  1.43750000e+00,
          1.53130235e+00,  1.42866391e+00,  1.08584870e+00,  2.43370225e+00,
          2.24200192e+00,  1.64955312e+00,  2.02749626e+00,  2.59530729e+00,
          2.08590785e+00,  2.43462392e+00,  2.61790663e+00,  2.09243680e+00,
          3.30850658e+00,  1.73955053e+00,  4.23885773e+00,  2.44402147e+00,
          2.12575242e+00,  2.37226887e+00,  3.02124153e+00,  2.90227163e+00,
          3.22624872e+00,  2.24548239e+00,  2.43854507e+00,  3.08842237e+00,
          2.91253593e+00,  3.31922525e+00,  1.20385853e+00,  1.55040507e+00,
          9.35441116e-01,  9.45598488e-01,  9.31092707e-01,  2.39334268e+00,
          1.68554361e+00,  1.37646811e+00,  2.21072142e+00,  2.37492900e+00,
          2.20107081e+00,  1.68777992e+00,  1.19990603e+00,  1.20986909e+00,
          1.56734014e+00,  1.25518183e+00,  1.13002439e+00,  1.83391657e+00,
          1.83627917e+00,  1.36547286e+00,  2.19352607e+00,  9.12626766e-01,
          1.12724296e+00,  1.02450358e+00,  1.30474906e+00,  1.80197232e+00,
          3.24548669e+00,  3.42495183e+00,  2.10138167e+00,  3.08989422e+00,
          2.48194326e+00,  1.93180258e+00,  1.21356225e+00,  1.32059129e+00,
          3.67342313e+00,  2.72703586e+00,  1.94854811e+00,  2.25372105e+00,
          2.38619292e+00,  1.70546862e+00,  1.32872768e+00,  3.28552571e+00,
          3.45354490e+00,  3.11310260e+00,  3.03460322e+00,  3.33852923e+00,
          4.03929350e+00,  3.88928772e+00,  4.17319928e+00,  2.61802843e+00,
          2.09947345e+00,  2.01025524e+00,  2.98594096e+00,  3.54480226e+00,
          4.13040336e+00,  3.51482651e+00,  3.04113264e+00,  3.77678340e+00,
          3.45106567e+00,  2.89533041e+00,  2.82364362e+00,  2.11008111e+00,
          1.01281459e+00,  1.67741705e+00,  1.61434874e+00,  2.17855714e+00,
          1.50060897e+00,  2.85313446e+00,  2.21772863e+00,  1.94667226e+00,
          2.55426542e+00,  2.66722789e+00,  1.83549818e+00,  1.88317825e+00,
          1.73157830e+00,  1.69969016e+00,  1.81568064e+00,  1.76340269e+00,
          1.41235522e+00,  1.11362773e+00,  6.98700573e-01,  8.76218526e-01,
          1.06528168e+00,  1.10019691e+00,  1.65371014e+00,  9.86028731e-01,
          2.69955996e-01, -1.71111162e-01,  4.11471337e-01,  1.08453851e+00,
          1.46714107e+00,  1.34162838e+00,  1.04800383e+00,  1.00119119e+00,
          3.46687623e-01,  3.66731814e-01, -3.31069929e-01, -5.18561800e-01,
         -4.94790053e-01,  1.95283366e-01, -1.88576280e-01,  1.36558867e-01,
          3.91007574e-01, -3.41584485e-01,  3.81264506e-01,  1.16981811e-01,
          3.16710657e-01,  8.12030993e-01,  1.10356784e-01, -3.62964971e-16,
         -3.74723322e-01, -8.97984945e-01, -2.93143457e-01, -9.00901643e-01,
         -6.34705948e-01,  1.20474968e-01, -1.61164593e-01,  5.56093432e-01,
          9.35485530e-01,  1.19994560e+00,  1.26886480e-01,  4.42918559e-01,
          8.98877105e-01,  1.35150130e+00,  1.03895023e+00,  7.49029515e-02,
          2.76723317e-01,  1.49614838e+00,  4.06225584e-03, -5.78554427e-01,
          9.37703517e-01,  1.53545961e+00,  2.93948176e+00,  2.36934029e+00,
          2.17151544e+00,  3.32007542e+00,  2.10272753e+00,  9.28341851e-01,
          1.53245983e+00,  1.56134174e+00,  5.53751947e-01,  2.24467839e+00,
          1.42659852e+00,  9.91041056e-01,  1.55368076e+00,  1.74516618e+00,
          2.70616375e+00,  2.32419215e+00,  1.86745617e+00,  1.82707080e+00,
          1.74881824e+00,  2.37624445e+00,  1.28239633e+00,  2.23400613e+00,
          2.32751457e+00,  2.76265024e+00,  3.41297815e+00,  3.42204493e+00,

In [3]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

563
563
563
=
1689

,gpt_layer,WER,BLEU,METEOR,BERT
0,6,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,7,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."

In [4]:
results_df

,gpt_layer,WER,BLEU,METEOR,BERT
0,6,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,7,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,8,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,10,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."

In [5]:
gpt_layer_6=np.array(results_df.loc[0, 'BERT']).mean()
gpt_layer_7=np.array(results_df.loc[1, 'BERT']).mean()
gpt_layer_8=np.array(results_df.loc[2, 'BERT']).mean()
gpt_layer_9=np.array(results_df.loc[3, 'BERT']).mean()
gpt_layer_10=np.array(results_df.loc[4, 'BERT']).mean()
to_file = pd.DataFrame({'gpt_layer':[6,7,8,9,10], 'significantly_decoded': [gpt_layer_6,gpt_layer_7,gpt_layer_8,gpt_layer_9,gpt_layer_10]})
to_file.to_csv('../perceived_speech_gpt_layer.csv', index=False)

to_file

   gpt_layer  significantly_decoded
0          6               0.666075
1          7               0.674956
2          8               0.605684
3          9               0.598579
4         10               0.655417