In [12]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('../scores/S1/perceived_movie/gpt_layer_10/laluna.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('laluna', 'WER'): np.float64(2.2919088563404566), ('laluna', 'BLEU'): np.float64(4.164183565894594), ('laluna', 'METEOR'): np.float64(3.62231013232706), ('laluna', 'BERT'): np.float32(6.0924754)}

In [13]:
window_zscores = {'subject': [], 'gpt_layer': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for subject in ['S1','S2','S3']:
    for gpt_layer in [6,7,8,9,10]:
        for task in ['laluna']:
            scores = np.load(f'../scores/{subject}/perceived_movie/gpt_layer_{gpt_layer}/{task}.npz', allow_pickle=True)['window_zscores'].item()
            # print(scores['window_zscores'].item())
            window_zscores['subject'].append(subject)
            window_zscores['gpt_layer'].append(gpt_layer)
            window_zscores['WER'].append(scores[(task, 'WER')])
            window_zscores['BLEU'].append(scores[(task, 'BLEU')])
            window_zscores['METEOR'].append(scores[(task, 'METEOR')])
            window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'subject': ['S1',
  'S1',
  'S1',
  'S1',
  'S1',
  'S2',
  'S2',
  'S2',
  'S2',
  'S2',
  'S3',
  'S3',
  'S3',
  'S3',
  'S3'],
 'gpt_layer': [6, 7, 8, 9, 10, 6, 7, 8, 9, 10, 6, 7, 8, 9, 10],
 'WER': [array([-1.93657401e-01, -3.54860432e-01,  5.08162014e-01, -1.08874467e+00,
         -1.68656181e+00, -1.02617250e+00, -2.83337706e-01, -5.59016994e-01,
         -5.65271031e-01,  5.22066004e-02, -1.08000789e+00, -1.27573963e+00,
         -1.57804399e+00, -1.47402102e+00,  3.87298335e-01, -8.32244145e-01,
         -1.54034493e+00,  1.91548220e-01,  4.93625884e-01, -1.04302106e+00,
         -1.74356314e+00, -1.97141975e+00, -6.40866752e-01, -1.31954569e+00,
         -5.40476936e-01, -8.55130347e-01, -2.47100217e-01, -7.42902427e-01,
         -7.91063252e-01, -1.28295818e+00, -1.39457562e+00, -2.11885845e+00,
         -2.23776507e+00, -2.23881897e+00, -1.68105118e+00, -1.80066583e+00,
         -7.75788665e-01, -2.15336282e+00, -1.99884759e+00, -1.93689164e+00,
         -1.71179510e+00, -1.32581399e+00, -1.35918768e+00, -1.14847371e+00,
         -1.15734275e+00, -1.06854332e+00, -1.30926289e+00, -1.30144653e+00,
         -1.30926289e+00, -6.12146092e-01,  4.05261529e-02, -7.41828231e-02,
         -3.95919263e-01, -3.48442697e-01,  1.38335651e+00,  3.04073504e+00,
          5.86899402e-01,  7.15349959e-01,  9.11561376e-01,  1.73973921e+00,
          9.17924819e-01,  1.96007582e+00,  1.91653496e+00,  3.24762763e+00,
          2.23979373e+00,  3.10107735e+00,  2.91594321e+00,  2.86216701e+00,
          2.99869070e+00,  3.21757904e+00,  2.32852923e+00,  1.43912349e+00,
          2.01621502e+00,  1.82737836e+00,  1.82336588e+00,  1.66333467e+00,
          1.72171345e+00,  1.59106245e+00,  1.65609963e+00,  1.08772414e+00,
          1.02773629e+00,  1.22008453e+00,  3.76299862e-01,  4.49818355e-01,
         -2.03113280e-01, -3.66508333e-01, -2.10322244e-01, -6.78636811e-01,
         -9.26203362e-01, -9.54930883e-01, -5.29900852e-01, -5.14535460e-01,
         -7.48400197e-01,  2.63477778e-01,  1.09976415e+00,  7.16598572e-01,
         -3.09521634e-01,  7.23219709e-02, -1.57026184e+00, -1.03604035e+00,
         -7.85135257e-01, -2.02535241e-01, -5.18856549e-01,  6.10141825e-01,
          1.78862361e-01, -5.66676335e-16, -5.27779814e-02, -6.30218724e-02,
          5.12470743e-01, -4.38127342e-01,  1.57440180e+00,  7.74703976e-01,
          4.93058650e-01,  9.79729219e-01,  5.35626856e-01, -1.81848242e-02,
          3.97301787e-01,  1.82501595e+00,  2.00372419e+00,  5.65925572e-01,
          4.04145610e-15,  8.31375520e-02,  1.28462368e+00,  1.35600536e+00,
          1.33045496e+00,  8.31238024e-01,  8.19078297e-01,  8.62975693e-01,
          6.18694159e-01,  2.67356744e-02,  9.00433485e-01,  1.66540833e+00,
          5.84815310e-01,  8.33483235e-01,  1.70244007e-01,  1.90885429e-01,
          6.24506251e-01,  8.38158076e-01,  1.27801930e+00, -5.48682890e-01,
          2.14341981e+00,  1.43395771e+00,  1.38447581e+00,  4.11571352e-01,
          1.89545644e-01,  1.00376466e+00,  1.76281788e+00,  1.71880941e+00,
          1.67111931e+00,  1.04787112e+00,  1.97037797e+00,  2.36236964e+00,
          2.24928693e+00,  3.14047172e+00,  2.32043177e+00,  2.84939192e+00,
          1.37619513e+00,  9.30971431e-01,  1.91713400e+00,  1.60428941e+00,
          2.59565357e+00,  3.45090719e+00,  3.92030198e+00,  2.28839737e+00,
          2.46205122e+00,  1.77384553e+00,  2.36959608e+00,  2.25251164e+00,
          1.10643605e+00,  2.07159078e+00,  1.16666667e+00,  1.04170822e+00,
          9.09633655e-01,  1.39829918e+00,  1.63650391e+00,  1.96529169e+00,
          1.92374205e+00,  2.11788337e+00,  1.01179893e+00, -3.84812212e-01,
          8.28517156e-01,  6.16315634e-01,  1.22960711e+00,  1.20122620e+00,
          1.96869172e+00,  1.27188788e+00,  5.16309979e-01,  2.81671301e-01,
          2.15131809e-01,  1.28514842e+00,  1.75494274e-01,  1.30342511e+00,
          1.35500728e+00,  5.07434192e-01,  1.12607821e-01,  4.95665558e-01,
          1.87948973e+00, -4.46113437e-01,  7.58295955e-01,  6.63861629e-01,
         -8.06266110e-01,  4.76731295e-01,  2.07730875e-01,  5.15741426e-01,
         -5.74505905e-01, -9.01035640e-01, -7.13968654e-01, -1.19759151e+00,
         -3.63032966e-01, -1.16914798e+00, -9.58985518e-01, -8.71572057e-01,
         -1.77790265e+00, -1.85493333e+00, -1.64947184e+00, -1.61972297e+00,
         -6.53523202e-01, -1.62958241e+00, -1.42350975e+00, -1.19277272e+00,
         -1.03155674e+00, -2.70445984e-01, -3.01892041e-01,  5.16682453e-01,
          7.34045111e-01,  1.01837390e+00,  1.74957856e+00,  7.45221267e-02,
         -2.05195670e-01,  9.16554796e-01,  9.35112512e-01,  2.09855954e+00,
          1.43019388e+00,  1.69565217e+00,  1.58730433e+00,  5.17521829e-01,
          2.30361300e+00,  1.10432147e+00,  1.08459722e+00,  1.02590357e+00,
         -5.03558685e-01,  3.78519398e-01,  1.33763389e-01, -6.45330817e-01,
          2.00601341e-01,  1.60509684e-01, -1.91057398e-01,  1.60548770e-01,
          7.40475637e-01, -1.95123136e-01, -1.31193027e+00, -1.22900783e+00,
         -5.37682792e-01,  1.41731734e-01, -1.30322738e-02,  1.29486223e-01,
         -1.33825409e-01,  9.88293931e-01,  1.26087668e+00,  5.61210253e-01,
          1.10235651e+00,  1.96123800e+00,  1.49066272e+00,  1.20494610e+00,
          1.71181587e+00,  1.08889122e+00,  2.16336332e+00,  3.89094713e-01,
         -6.63167080e-01,  5.70626893e-01,  1.27894889e+00,  1.91004440e+00,
          1.83118159e+00,  1.93351016e+00,  1.89095488e+00,  1.16274810e+00,
          1.40699828e+00,  1.49013176e+00,  7.24866969e-01,  5.56205914e-01,
          4.95470921e-01,  1.66156691e+00,  2.12289111e+00,  2.10548139e+00,
         -1.81101183e-02, -1.29486223e-01,  7.76628069e-01,  7.74596669e-01,
          2.56165157e+00,  2.02224334e+00,  1.61306683e+00,  1.74587828e+00,
          1.95402768e+00,  2.56269591e+00,  2.17013000e+00,  2.72598519e+00,
          1.92222661e+00,  2.19209833e+00,  1.81548129e+00,  1.95252886e+00,
          1.53654217e+00,  1.81019840e+00,  2.39308602e+00,  1.28066510e+00,
          2.27574782e+00,  1.88328038e+00,  2.79758457e+00,  2.20540468e+00,
          3.18784523e-01,  8.60793497e-01,  7.34754550e-01,  5.00030637e-01,
          4.02557045e-01, -7.71710058e-01, -4.40923824e-01, -1.70986189e+00,
         -1.65271467e+00, -1.75687440e+00, -1.66648200e+00, -1.50290114e+00,
         -1.18498477e+00, -1.37200202e+00, -1.06038423e+00, -1.76324147e+00,
         -2.40167254e-02, -4.26013820e-01, -9.19145030e-01, -7.36614483e-01,
         -6.25511992e-01, -8.06093425e-01, -1.40964250e+00]),
  array([-1.29407927e-01,  4.59325100e-01,  3.90387757e-01, -1.11529648e+00,
         -4.75460395e-01, -1.00260717e+00, -3.88727733e-01, -5.38339456e-01,
         -5.01779895e-01, -1.19254173e+00, -1.19304280e+00,  6.47362901e-01,
         -7.26716836e-01, -4.51980994e-01, -1.00774039e+00, -1.01464967e+00,
          3.89550227e-01,  7.90723868e-02, -6.25543242e-01,  7.52482918e-01,
          8.78950175e-01,  1.33881737e-01,  2.65126688e-01, -4.62348742e-01,
          2.14649209e-01, -1.58705211e-01, -1.00038934e+00, -8.04747572e-01,
          5.86666668e-01,  8.41842258e-01,  7.11536745e-01,  1.99918417e-01,
          5.73834350e-02,  5.32955444e-02, -1.52118966e-01,  5.02067169e-01,
          9.11807773e-02,  2.71556685e-01,  3.70077629e-01,  5.58120203e-01,
          9.11407491e-01,  4.33038284e-01,  4.50364323e-01, -2.89846235e-01,
          6.91851266e-02,  1.31589948e+00, -2.04210988e-01, -1.75326631e-01,
         -1.25723711e+00,  1.47513841e+00,  1.07548374e+00,  7.69684843e-01,
          1.32466675e+00,  1.38110434e+00,  1.99464667e+00,  1.26657429e+00,
          1.19314939e+00,  1.31710976e+00,  1.31370926e+00,  1.30226607e+00,
          1.31676192e+00,  2.41951525e+00,  2.29517020e+00,  2.34349961e+00,
          8.61030633e-01,  1.68696586e+00,  8.03171902e-01,  8.32126409e-01,
          8.19737325e-01, -1.37807647e-02, -2.43421118e-01,  2.50987599e-01,
         -1.28906554e-01, -1.73421994e-01, -1.13020187e-01, -2.30034273e-01,
         -2.06372086e-01,  4.69314664e-01,  5.67732091e-01,  8.98403437e-01,
          8.40079559e-01,  1.97006831e-01,  2.41154598e-01,  1.12135086e+00,
          4.39462543e-01,  1.02040473e+00,  1.21362143e+00,  9.38825606e-01,
          1.51852829e+00,  5.26579376e-01,  1.12817041e+00,  9.42622254e-01,
          7.94937355e-01,  7.34898546e-02,  7.49409646e-01,  1.64441869e+00,
          5.14535460e-01, -3.44469377e-02, -7.05695755e-01,  4.81627871e-02,
          4.47622245e-01, -2.63664022e-01,  4.63615060e-01, -7.01952584e-01,
          3.00443924e-01, -4.29239899e-02,  1.10006791e+00,  1.08041946e+00,
          5.27835720e-01, -3.60476772e-01, -9.02983580e-01, -1.36248778e+00,
         -5.68117751e-01,  9.12560587e-01, -4.77712457e-01, -8.90673187e-01,
          3.95284708e-01,  8.49692484e-02,  1.76552601e-01,  4.74581540e-01,
         -8.67109970e-02, -4.27569125e-02,  1.22126309e-01,  1.49565373e-01,
          1.68826614e-01, -1.44135097e-01, -1.98418948e-01, -1.76538475e-01,
         -3.41160731e-01, -6.55434415e-02,  5.29921354e-01,  4.00676411e-01,
          1.31790518e+00,  5.93072144e-01,  1.34808615e+00,  1.83597018e-01,
          6.32455532e-01,  4.51065662e+00,  2.95216773e+00,  3.37668832e+00,
          3.41456172e+00,  1.26362231e+00,  1.26105485e+00,  1.73107555e+00,
          1.72362415e+00, -7.13881134e-02, -3.36216785e-01, -4.10025610e-01,
          5.84189998e-01,  2.06391698e+00,  2.27817819e+00,  3.32951735e-01,
          3.06736560e-01,  1.82374414e-01,  1.26233958e+00,  9.79434721e-01,
          1.35741083e+00,  9.07569646e-01,  1.99946688e+00,  8.27028073e-01,
          2.02837021e+00,  1.85929126e+00,  1.62408628e+00,  2.52437250e+00,
          2.74043381e+00,  3.06882014e+00,  1.99317637e+00,  2.77449036e+00,
          2.14409304e+00,  2.01447666e+00,  2.20797843e+00,  1.03503319e+00,
          9.39444776e-01,  8.04251094e-01,  8.11268539e-01,  2.39080576e-01,
          2.92940883e-01, -4.19590679e-01,  1.95844952e-01, -2.63806235e-01,
          8.56588372e-01,  7.13997880e-01,  1.33399947e+00,  2.10410145e+00,
          2.01818131e+00,  1.20458321e+00,  1.38649597e+00,  1.78234623e-01,
          9.33942324e-02,  1.01258533e+00,  9.98794183e-01,  1.12729339e+00,
         -3.49481623e-01,  6.26628314e-01,  1.15910264e+00,  1.58915437e+00,
          1.91384615e+00,  6.80677930e-01,  1.04344902e+00, -8.06308242e-01,
         -7.47028279e-01, -3.11085508e-01, -7.40659899e-01, -1.32929365e+00,
          3.81810880e-01,  9.55485171e-01,  2.23100326e-01, -1.40640030e-01,
         -1.31180841e-01, -9.77398211e-01, -7.76714771e-01, -8.32461265e-01,
         -2.20594199e-02, -1.12750131e+00, -8.09153935e-01, -1.02168850e+00,
         -1.73409092e+00, -8.05299830e-01, -5.49351050e-01, -2.09341924e-01,
         -9.90400779e-02, -2.81734911e-01, -1.26207782e+00, -5.87544275e-01,
          6.04960848e-01,  8.54242196e-01,  5.17521829e-01, -1.09028523e-01,
          1.58955407e+00,  7.91323285e-01,  8.76681233e-01,  1.87660804e+00,
          2.55777918e+00,  4.31421191e+00,  3.70303041e+00,  2.80611493e+00,
          1.30886684e+00, -7.00597421e-02, -7.85031644e-02, -1.17103002e-01,
          4.75633081e-01, -6.20946271e-01,  1.25543478e-01, -6.74093848e-01,
          1.39917139e-01, -1.64996477e+00, -1.19571699e+00, -9.71857629e-01,
         -1.33887913e+00, -1.19478215e+00, -1.32529275e+00, -1.43719966e+00,
         -1.67648708e+00, -8.48788088e-01, -1.07825703e+00, -8.93226473e-01,
         -1.14960999e+00, -8.75410222e-01, -6.43526836e-01, -3.80187813e-01,
         -1.12073216e+00, -9.53582599e-01, -4.21965078e-01,  2.48861139e-01,
          1.65757216e-01,  3.01892041e-01, -4.72055183e-01,  2.11055379e-01,
          3.01928956e-02, -2.67410353e-01, -2.02229744e-01, -3.68316958e-01,
         -4.07652742e-01, -2.93083495e-01,  9.60219511e-01, -3.66774747e-01,
         -2.17642875e-01, -1.07362468e-01, -8.65004027e-01, -3.19320350e-01,
          3.69369492e-01,  1.48743738e+00,  2.10599254e+00,  2.14660321e+00,
          1.70077822e+00,  1.59418453e+00,  2.43305675e+00,  5.46915144e-01,
          8.58266022e-01,  4.15511487e-01,  2.53432493e+00,  1.81067989e+00,
          1.40382359e+00,  9.15432427e-01,  7.35615200e-01,  5.91520482e-01,
          1.19734219e+00,  5.36479936e-01,  1.02310054e+00,  1.96566120e+00,
         -3.88468568e-01,  6.67415409e-01, -3.21800252e-02,  8.78368967e-02,
          2.01522888e-01, -2.23216510e-02, -9.16737016e-03,  2.81727637e-01,
         -6.93033952e-01, -2.58402838e-01, -3.84754797e-01,  4.49790014e-01,
          3.20640590e-01,  2.35161747e-01,  3.98502580e-01,  4.34376341e-03,
         -8.84140399e-02, -2.38893067e-01, -2.49358815e-01, -6.98933000e-01,
         -3.53417581e-01, -3.82045791e-01, -8.14984575e-02, -1.81787714e-01,
         -8.76819317e-01, -1.21389357e+00, -1.08855723e+00, -8.86658628e-01,
         -7.53778361e-01, -1.51518505e-01, -1.49839937e+00]),
  array([ 2.52204252e+00,  2.88611935e+00,  2.85235216e+00,  2.52633148e+00,
          2.91104402e+00,  1.50276130e+00,  3.84409387e+00,  5.52496231e-01,
          5.35327989e-01,  1.05054337e+00,  5.60780971e-03,  7.54102426e-01,
          4.21637021e-01, -4.02960224e-01,  2.46182982e-01, -8.60814837e-01,
          4.50965004e-01,  1.31323516e-01,  5.02500000e-01, -1.41264483e-01,
         -8.74286820e-01, -8.50125793e-01, -1.66381113e+00, -1.40785701e+00,
         -2.06671442e+00, -2.22095070e+00, -2.51711957e+00, -2.45136427e+00,
         -2.29036897e+00, -1.46875015e+00, -1.50354408e+00, -2.01801333e+00,
         -2.04713636e+00, -1.33356719e+00, -1.63737033e+00, -1.56112403e+00,
         -1.35745318e+00, -1.23811717e+00, -3.61634768e-01, -1.04107681e+00,
         -1.59111457e+00, -1.27688480e+00, -1.25515493e+00, -1.07830164e+00,
         -1.16554303e+00,  9.53733575e-02, -1.37395198e+00, -1.35764707e+00,
         -1.31347863e+00, -5.29998940e-01, -7.61024518e-01, -8.20341294e-01,
         -1.19790014e+00, -1.13581527e+00, -3.25856044e-01, -1.09975584e+00,
         -1.12479377e+00, -1.02455956e+00, -9.60356842e-01, -9.50587273e-01,
         -9.75813431e-01, -8.75849717e-01, -9.67871909e-01,  7.26193242e-02,
          2.43108319e-01,  1.07863874e+00,  9.79807555e-01,  1.94213363e+00,
          1.85640058e+00,  1.09684970e+00,  1.02911945e+00,  2.89846235e-01,
         -1.10946867e-01, -1.59176966e-01,  7.01646415e-01,  5.72656287e-01,
          6.09487941e-01,  5.11909642e-01,  6.28802490e-01,  8.47225714e-01,
          7.91483911e-01,  1.09276298e+00,  2.04181668e-01,  2.85237190e-01,
          3.61588739e-01,  2.74351631e-01,  4.50326088e-01,  7.14513593e-02,
          6.58462043e-01,  6.16797725e-01,  2.99301069e-01,  2.26990552e-01,
         -8.42089830e-01,  2.07827503e-01,  9.61318958e-01,  4.82467126e-01,
         -4.28802393e-01, -8.90870806e-02,  1.96648167e-01,  2.16981518e-02,
         -7.69811853e-01, -2.09941017e-01,  4.11700080e-01,  6.86047956e-01,
          2.74656893e-01,  1.14162170e+00,  1.01962962e+00,  1.00723932e+00,
          6.05310301e-01,  6.06928418e-01,  3.64759527e-01, -2.73719931e-01,
         -4.78753194e-01, -1.79319874e-01, -6.07725070e-01, -1.97766378e-01,
         -5.16397779e-01, -1.61078051e+00, -1.49622417e+00, -4.45472954e-01,
         -1.03767305e+00, -9.41844594e-01, -8.16128839e-01, -7.43616064e-01,
         -6.95395361e-01, -9.87996898e-01, -9.77252756e-01, -9.20383043e-01,
         -1.10476692e+00, -8.81145016e-01, -3.27007648e-01, -5.17521829e-01,
         -4.97545268e-01,  8.14270107e-01, -1.08845917e+00, -9.95870595e-01,
         -8.55337203e-01, -7.05475622e-01,  1.91685130e+00, -4.97701137e-01,
          1.02551931e+00,  2.00006809e+00,  1.99589743e+00, -7.92659768e-01,
          5.36770668e-01,  1.23592124e+00,  1.74200520e+00,  1.69332866e+00,
          7.14001136e-01,  1.21225625e+00,  2.27530682e+00,  4.65915841e-01,
          4.03473292e-01,  1.12111986e+00,  1.37611138e+00,  2.63584494e+00,
          3.11138623e+00,  2.99869070e+00,  3.27659574e+00,  3.48867499e+00,
          4.34640364e+00,  4.90739128e+00,  4.66771876e+00,  4.57506942e+00,
          4.02540103e+00,  2.66561421e+00,  1.80168276e+00,  1.67232112e+00,
          1.99097511e+00,  1.98325934e+00,  1.24128431e+00,  1.03473604e+00,
          9.41750181e-01,  7.10442437e-01,  7.67689442e-01,  1.77635423e-01,
          9.18381272e-01,  1.15047850e+00,  1.72438683e+00,  6.71765585e-01,
         -8.73704057e-02, -3.20081248e-01, -5.58387938e-01, -6.98805941e-01,
         -7.34785863e-01,  2.02664866e+00,  2.35032090e+00,  2.12689933e+00,
          1.85144527e+00,  9.44547642e-01,  1.94647982e+00,  9.55993750e-01,
          2.08360713e+00,  1.40378879e+00,  1.87833039e+00,  1.38148563e+00,
          1.05847677e+00,  4.49278643e-01,  1.90971886e+00,  1.90277194e+00,
          9.66796282e-01,  1.54600333e+00,  3.56973269e-01, -3.56383243e-01,
         -7.62999896e-01, -1.09726183e+00,  1.38232703e-01, -3.63694302e-01,
         -3.27093281e-01,  5.39196198e-01, -4.40652649e-02,  7.42332223e-01,
          7.37737162e-01,  6.19058273e-01,  1.02881345e+00,  8.19221646e-01,
          1.90538682e-01,  1.00000000e+00,  1.13921355e+00,  5.50444463e-01,
          1.55472453e+00,  1.48166919e+00,  1.37638852e+00,  3.57959169e-01,
          1.42184655e+00,  8.38020627e-01,  5.07494091e-01,  1.11710384e+00,
          1.96138354e+00,  8.83879554e-01,  8.06481620e-01, -3.05673508e-01,
          1.38287350e+00,  5.29998940e-01,  1.50402830e+00,  5.35666397e-01,
          2.16932491e+00,  2.00479988e+00,  9.91791927e-01,  9.76626671e-01,
          2.14908774e+00,  1.16065628e+00,  1.75165820e+00,  3.49966071e-01,
          1.01263208e+00,  1.70266539e-01,  9.11393392e-01,  2.16333960e-01,
         -2.88812210e-01, -2.20290780e-01, -1.31898674e+00, -1.29793533e+00,
         -6.40866752e-01, -9.53582599e-01, -4.80020891e-03, -9.60768923e-01,
         -1.11396167e+00, -9.46557181e-01, -7.67470899e-01, -5.29921354e-01,
         -1.48456598e-01, -8.54068518e-01, -2.74640173e-01, -5.79856083e-01,
          2.37109451e-01, -5.49783433e-01,  5.84201026e-01,  2.21835634e+00,
          2.00150476e+00,  1.68941138e+00, -4.97176869e-02, -1.90000211e-01,
          5.39682540e-01,  5.93795396e-01,  4.80822369e-01,  5.02570711e-01,
          1.44452823e+00,  2.37760013e+00,  2.31163045e+00,  2.08617270e+00,
          2.84887759e+00,  1.78805758e+00,  2.27885088e+00,  2.25241017e+00,
          8.46778657e-01,  7.31986389e-01,  1.56283919e+00,  2.71634256e+00,
          2.68964342e+00,  2.15918544e+00,  2.42642071e+00,  2.60995288e+00,
          2.03937254e+00,  1.79682440e+00,  1.51098861e+00,  1.40104066e+00,
          3.86186093e-01,  6.13400631e-01,  1.14722227e+00,  6.49365978e-01,
          2.86966124e+00,  8.51830370e-01,  1.36849443e+00,  1.49448874e+00,
          4.11670656e-01,  1.71710837e-01,  1.59677627e-01,  4.59663070e-01,
          4.06138466e-01, -2.35648169e-01, -2.52446721e-01, -4.93625884e-01,
         -5.89301157e-01, -6.50814027e-01, -4.17878399e-01, -8.07750060e-01,
         -9.21022433e-01, -1.07832540e+00, -1.01343805e+00, -6.81195302e-01,
         -1.13898959e+00, -4.74964855e-01, -1.60556076e-01, -9.97675880e-01,
         -8.21951395e-01, -1.11719976e+00, -9.99325529e-01, -7.78412857e-01,
         -6.76425437e-01, -7.04001649e-02, -3.85125445e-01]),
  array([ 7.13076184e-01,  1.35837708e+00,  2.34197321e+00,  9.85706013e-01,
          8.92294177e-01, -4.11401864e-02,  6.08695652e-01,  1.47802357e+00,
          1.65754018e+00,  1.15878673e+00,  3.94610899e-01,  2.72237292e+00,
          2.13221249e+00,  2.55567238e+00,  1.92209395e+00,  3.05868724e+00,
          1.46578399e+00,  1.94332945e-01,  1.02641719e+00,  6.46342555e-01,
          8.60309002e-02, -6.61915886e-01, -7.12920553e-01, -3.77964473e-01,
         -8.82456389e-01, -1.12329004e+00, -1.28237080e+00, -1.82878652e+00,
         -1.04785227e+00, -1.50678010e+00, -1.49168004e+00, -1.44126792e+00,

In [14]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

331
331
331
=
1689

,subject,gpt_layer,WER,BLEU,METEOR,BERT
0,S1,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,S1,7,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
2,S1,8,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,S1,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,S1,10,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,S2,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,S2,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, ..."
7,S2,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,S2,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
9,S2,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,S3,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
11,S3,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
12,S3,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
13,S3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
14,S3,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [15]:
results_df['BERT'] = results_df['BERT'].apply(np.mean)
to_file = results_df.drop(columns=['WER','BLEU','METEOR']).rename(columns={'BERT':'significantly_decoded'})
to_file

   subject  gpt_layer  significantly_decoded
0       S1          6               0.096677
1       S1          7               0.021148
2       S1          8               0.078550
3       S1          9               0.247734
4       S1         10               0.223565
5       S2          6               0.244713
6       S2          7               0.302115
7       S2          8               0.404834
8       S2          9               0.432024
9       S2         10               0.241692
10      S3          6               0.290030
11      S3          7               0.283988
12      S3          8               0.311178
13      S3          9               0.401813
14      S3         10               0.250755

In [16]:
# gpt_layer_6=np.array(results_df.loc[0, 'BERT']).mean()
# gpt_layer_7=np.array(results_df.loc[1, 'BERT']).mean()
# gpt_layer_8=np.array(results_df.loc[2, 'BERT']).mean()
# gpt_layer_9=np.array(results_df.loc[3, 'BERT']).mean()
# gpt_layer_10=np.array(results_df.loc[4, 'BERT']).mean()
# to_file = pd.DataFrame({'gpt_layer':[6,7,8,9,10], 'significantly_decoded': [gpt_layer_6,gpt_layer_7,gpt_layer_8,gpt_layer_9,gpt_layer_10]})
to_file.to_csv('perceived_movie_gpt_layer.csv', index=False)

to_file

   subject  gpt_layer  significantly_decoded
0       S1          6               0.096677
1       S1          7               0.021148
2       S1          8               0.078550
3       S1          9               0.247734
4       S1         10               0.223565
5       S2          6               0.244713
6       S2          7               0.302115
7       S2          8               0.404834
8       S2          9               0.432024
9       S2         10               0.241692
10      S3          6               0.290030
11      S3          7               0.283988
12      S3          8               0.311178
13      S3          9               0.401813
14      S3         10               0.250755