In [13]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('../scores/S1/imagined_speech/gpt_layer_10/alpha_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['story_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('alpha_repeat-1', 'WER'): np.float64(0.6803876542976238), ('alpha_repeat-1', 'BLEU'): np.float64(1.1852455224633727), ('alpha_repeat-1', 'METEOR'): np.float64(1.8014219498921065), ('alpha_repeat-1', 'BERT'): np.float32(1.7755879)}

In [14]:
window_zscores = {'subject': [], 'gpt_layer': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for subject in ['S1','S2','S3']:
    for gpt_layer in [6,7,8,9,10]:
        for task in ['alpha_repeat-1']:
            scores = np.load(f'../scores/{subject}/imagined_speech/gpt_layer_{gpt_layer}/{task}.npz', allow_pickle=True)['window_zscores'].item()
            # print(scores['window_zscores'].item())
            window_zscores['subject'].append(subject)
            window_zscores['gpt_layer'].append(gpt_layer)
            window_zscores['WER'].append(scores[(task, 'WER')])
            window_zscores['BLEU'].append(scores[(task, 'BLEU')])
            window_zscores['METEOR'].append(scores[(task, 'METEOR')])
            window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'subject': ['S1',
  'S1',
  'S1',
  'S1',
  'S1',
  'S2',
  'S2',
  'S2',
  'S2',
  'S2',
  'S3',
  'S3',
  'S3',
  'S3',
  'S3'],
 'gpt_layer': [6, 7, 8, 9, 10, 6, 7, 8, 9, 10, 6, 7, 8, 9, 10],
 'WER': [array([-0.04627448, -0.41003426, -0.03793216, -0.08561877,  0.42254826,
          0.46447889, -0.30012559,  0.46271912,  0.19150803,  0.58511751,
          1.94550548,  1.85176193,  1.54195294,  1.93717165,  1.54088314,
          1.99043633,  1.84925535,  2.0331765 ,  1.86815358,  1.88082761,
          1.94602231,  1.95065206,  1.54499124,  2.43862888,  1.85616901,
          1.90264675,  1.1247263 ,  0.77132494,  0.98285415,  0.99669791,
          1.00169525,  1.07539739,  0.9486833 ,  1.2829225 ,  0.83317896,
          0.33159634, -0.30467346, -0.27147318,  0.53207781,  0.66750044,
          0.5535254 ]),
  array([-0.93286234, -0.37969035,  0.01561928, -0.040996  , -0.34291383,
          0.51438453,  0.54922502, -0.19602825,  0.27216553, -0.02322095,
          0.55735497,  0.4493758 ,  0.72247779,  0.43342293,  0.80740264,
          0.4937055 ,  0.96669875,  0.39316736,  0.38126451,  1.0288984 ,
          1.12309904,  1.85680261,  1.63050194,  0.8711506 ,  1.07973517,
          0.97609216,  0.3219331 ,  0.6936561 ,  0.91766294,  1.6307485 ,
          2.60181509,  1.86026882,  1.73082308,  2.65196988,  2.1739665 ,
          1.86611075,  1.33824386,  1.37679507,  2.2784341 ,  1.51633833,
          0.64371161]),
  array([-0.07980241, -0.43946254, -0.00399684, -0.07980869,  0.40956129,
          1.2275781 ,  2.05658612,  2.10848923,  1.6518658 ,  2.1049319 ,
          1.89728758,  1.71668233,  2.10839424,  2.4527393 ,  2.28138124,
          2.7589196 ,  1.85118272,  1.12658343,  1.13900245,  1.8599149 ,
          1.81420259,  1.85089737,  1.5218817 ,  0.85221834,  1.01108577,
          1.76459829,  1.79039943,  1.45134934,  2.43198646,  2.52638899,
          3.78034264,  2.77173708,  1.85349907,  2.84649901,  2.41751534,
          2.80727419,  1.3810982 ,  0.57622176,  0.63108255, -0.16802629,
          0.63650226]),
  array([ 1.80435178,  0.39458176,  0.7553415 ,  0.65794351,  1.1450376 ,
          0.40872733,  1.1891742 ,  1.95762043,  0.8796883 ,  1.39007397,
          1.05956781,  1.03223887,  0.67617003,  1.04232344,  0.7667776 ,
          1.21165486,  1.6068432 ,  1.7444016 ,  2.3785895 ,  1.65056143,
          1.02012571,  1.24973367,  0.87942521,  0.88902428,  1.09511849,
          0.2549425 ,  0.29451819, -0.83297723,  0.14611468,  1.01485667,
          0.40168006,  0.42833926,  0.27511051,  1.47019011,  1.73797237,
          2.00656433,  1.32424345,  1.44767558,  0.59966694,  0.72514339,
          1.56436002]),
  array([-0.98727177, -1.2094158 , -1.62271244, -1.5728635 , -1.06833511,
         -1.00756086, -1.73536101, -1.6750762 , -1.0976387 , -0.03342078,
         -0.1931835 , -0.25081463, -0.62882703, -0.2795457 , -0.52514294,
          0.71369785,  0.50138411,  1.22582535,  1.23700547,  1.26433261,
          1.30191151,  1.40253322,  1.00899568,  1.90933748,  1.3027689 ,
          0.37853873,  1.10632756,  1.55006672,  0.99577621,  0.20452383,
         -0.44180475,  1.20458321,  1.20915635,  1.54072629,  1.7912462 ,
          1.29263677,  1.54738635,  0.66169786,  0.77159133,  0.88285789,
          0.78297774]),
  array([ 1.78472971,  0.96398156,  0.31871639,  0.50540297,  0.99861482,
          1.02770858,  0.6685211 ,  0.72929592, -0.51992887,  0.52513535,
         -0.37501014, -0.03732617,  0.2220101 , -0.93325653, -0.07495057,
         -0.65306893, -0.99378337,  0.17516961, -0.5182909 ,  0.25392542,
          0.28178297,  0.29374252, -0.16571432,  0.58676705, -0.17931987,
         -0.32947797, -0.47720929, -1.0080973 , -0.92210015, -0.25335963,
          0.73568294,  0.73568294,  0.57909069,  1.58188529,  0.36560588,
         -0.78431434, -0.39226084, -0.19664817, -0.15575531, -0.79107679,
          0.07985639]),
  array([ 0.56505421, -0.21970906,  0.14185619, -0.44944782,  0.08815496,
         -0.60902777, -1.02484588, -0.13857353, -0.49290383,  0.49901376,
          0.35863063,  0.77015405,  0.13135948, -0.03623807, -0.1093083 ,
         -0.63567416, -1.01306405, -0.45493261, -0.44772883,  0.25797952,
          0.27799157,  0.98003791,  0.59122937,  1.19534292,  0.41435613,
         -0.37562483, -0.56863155, -0.34563496, -0.23275399,  1.26927403,
          1.6212218 ,  1.6212218 ,  1.39829918,  0.9154995 ,  1.17589702,
          0.05595347, -0.35082321, -1.06924508,  0.77459667,  0.21766181,
          0.12159095]),
  array([ 0.65907873, -0.17532916,  0.15202926,  0.35577893,  0.82544121,
          0.07382385,  0.42799756,  0.67093639,  0.27672104, -0.47414113,
         -1.49227609, -1.0498361 , -0.76254381, -1.        , -0.1278043 ,
          0.11240732,  0.48911732,  0.21364745,  0.25460846,  0.36221075,
          0.32312487,  1.02377621,  0.59335104,  0.51825299, -0.31448545,
          0.32911827,  0.16666254,  0.44195757,  0.51306955,  1.38586973,
          1.85577282,  1.85577282,  1.60877791,  2.49979346,  1.9427243 ,
          1.65064451,  1.4072299 ,  0.81818182,  0.90913673,  1.23803943,
          1.14516809]),
  array([-0.41181385, -0.92966968, -0.54494926, -0.44887706, -0.70133632,
         -1.39801768, -1.1447673 , -1.82050514, -0.55364502, -0.4423578 ,
         -1.3536998 , -1.0753361 , -0.74204814, -1.01015254, -0.13764944,
         -0.68516579, -1.05280372, -2.09562351, -1.2142193 , -1.16041426,
         -1.10782562, -0.4084801 , -0.08274077,  0.40456067,  0.55485132,
          0.48373924,  0.34733575, -0.17729688, -0.08070148, -0.13288212,
          0.10542553,  0.11008303, -0.06013293,  0.20668798,  0.44529131,
          0.12746914, -0.33514339, -1.02661104, -0.12106256, -0.75829596,
          0.15447525]),
  array([ 0.67492637,  0.69951084,  1.01795941,  0.35285039,  0.78703349,
          0.07273397,  0.46988601,  0.56921939, -0.62466674, -0.45763255,
          0.24804332, -0.19156526,  0.12827074, -0.0605924 , -0.13393073,
         -0.69291777, -1.0749428 ,  0.11867817, -0.5937954 ,  0.28020319,
         -0.47257333, -0.45637611, -0.90673485,  0.57821312, -0.13774614,
         -0.20539406,  0.41725378,  1.39524768, -0.02912851,  1.46468798,
          2.38795567,  2.38795567,  1.38627663,  3.02868706,  1.81732996,
          0.03695265,  0.49914158, -0.13863226,  0.79707734,  1.13370074,
          2.01036814]),
  array([ 1.02131297,  0.86646238,  0.42314293,  0.63709374,  0.54044379,
          0.32481103,  0.17522476,  0.08173295,  0.47519096, -0.58447384,
          0.66114197,  0.76557631,  0.48304589,  0.84125392,  0.60142067,
          0.43888925,  0.38147604,  0.40988162,  0.65390829, -0.03398793,
          0.05424727,  0.72131176,  0.30962298,  0.85301351,  0.14312409,
          0.02801659, -0.02577591,  0.39312798,  0.61845653,  0.65188939,
         -0.56777497, -0.51298918, -0.41913228,  0.07066925, -0.15118046,
         -0.33161245, -0.8330049 , -1.08896644,  0.33669025,  0.40842271,
          0.27706951]),
  array([ 1.84984171,  0.81383188,  1.97206956,  1.47234966,  2.11437406,
          1.77749078,  1.72595687,  1.53232868,  0.55137772, -0.50439437,
          0.67267279,  0.73892511,  0.41495513,  0.75244081,  0.61747799,
          0.40891682,  0.35007002, -0.31296066, -0.11162911, -0.7679796 ,
         -0.68885035, -0.71653203, -1.20000385, -0.68280908, -0.74221176,
          0.75307018,  0.68288349,  1.0698957 ,  1.45585889,  1.37414433,
          1.04874333,  1.16422979,  2.36551256,  2.69085699,  3.65408983,
          5.07417054,  2.55889208,  3.02594799,  2.47721112,  2.64758545,
          1.59583547]),
  array([ 1.87161218,  1.74337037,  1.16927599,  1.37898354,  1.15748307,
          0.9940676 ,  0.92887589,  0.89144979,  1.20737303,  0.99199734,
          0.83335785,  0.19449643,  0.59339987,  0.90928907,  0.69859301,
          0.47405468,  0.37277744, -1.07884623, -0.81281371, -1.4019344 ,
         -1.36547735, -1.34839592, -0.37087127, -0.51438453, -0.55968818,
          0.08785611,  0.01779202, -0.33745526,  0.67185361,  1.35375921,
          1.91868582,  2.00348852,  1.35813677,  2.45838245,  2.54028853,
          1.601883  ,  1.33643688,  1.00624485,  1.56909229,  1.64826787,
          2.75304738]),
  array([ 1.69205895,  0.78666218,  0.31919711,  0.60663431,  0.46917044,
          0.95696949,  0.88971795,  0.84563235,  1.31176642, -0.55584245,
          0.07273397, -0.65411991,  0.53000229,  0.11581372,  0.64299905,
          0.47564513,  0.28847917, -1.04094985, -0.88981054, -1.50030753,
         -1.36515215, -1.43282776, -1.19722581, -1.35604142,  0.21777735,
         -1.40177016, -0.7066176 , -0.30151134, -0.02274883, -0.85287205,
         -0.50825159, -0.45035487, -1.27556114,  0.07368391, -0.12212631,
          0.60166452, -0.86407199, -0.11481404,  0.33232713,  0.35763718,
          0.35112344]),
  array([ 0.92520456,  2.43559895,  1.92209878,  1.34869082,  1.17635793,
          1.71958854,  1.58801551,  1.49486764,  1.11564509,  0.19706979,
          1.96994121,  1.54241068,  1.16456368,  1.52412832,  1.34839592,
          0.38553503, -0.35809908, -1.71958854, -1.62582006, -1.48150512,
         -1.42510514, -1.36534666, -1.14735257, -1.38229214,  0.11647306,
         -0.71333172, -0.06939728,  0.3448175 , -0.16891032, -0.14081913,
          0.15242004,  0.21499787,  0.27628583,  0.71906591,  1.4211568 ,
          0.55785637,  0.22412683, -0.17309693,  0.29488391,  0.41394695,
         -0.89920786])],
 'BLEU': [array([-1.19981319e+00, -1.49232987e+00, -7.30358789e-01, -4.18314456e-01,
         -1.41076272e-01,  1.95797566e-02,  1.55155536e-03,  9.07911546e-02,
         -1.25446804e-01, -3.19742129e-02,  6.39427191e-02, -6.45134651e-02,
          1.75942807e-02,  3.40642193e-01,  1.57608203e-01,  4.54206698e-01,
          8.63524812e-01,  9.55533086e-01,  1.53298761e+00,  1.53460713e+00,
          1.20641848e+00,  7.64616459e-01,  3.39676094e-01,  6.79147019e-01,
          1.03446334e+00,  1.01421350e+00,  7.89057242e-01,  1.22475010e+00,
          1.19746950e+00,  8.17675272e-01,  2.09804424e+00,  2.50214713e+00,
          2.79311403e+00,  2.34536682e+00,  1.85892038e+00,  1.09215455e+00,
          1.24287495e+00,  1.42033503e+00,  9.44058004e-01,  2.00584534e-01,
          5.54890227e-01]),
  array([-1.25709091, -1.23098144, -1.45716545, -0.91609216, -0.646003  ,
         -0.4422729 ,  0.1394891 , -0.06252221, -0.28940066, -0.45584231,
          0.15056762,  0.34229582,  0.41995116,  0.13323468,  0.2577964 ,
          0.17867833,  0.53898026,  0.18325058,  0.24540061,  0.60939137,
          0.74519527,  0.39325623,  0.84161596,  0.68792957,  0.55755387,
          1.09483451,  2.73317073,  3.81735392,  3.71422845,  2.76397617,
          4.27303912,  4.11662409,  3.54914251,  3.86688775,  3.87174475,
          3.53960695,  2.82354632,  2.68845807,  3.07261236,  2.30434022,
          2.21242879]),
  array([-1.24410707, -1.58272708, -1.48349245, -1.14897967, -0.88836497,
         -1.04374098, -1.1080699 , -0.95545637, -0.53834477,  0.2318739 ,
         -0.01250709,  0.20778278,  0.28390046,  0.65338943,  0.90893043,
          1.61634376,  1.32531616,  1.93699646,  1.09825444,  1.51312135,
          1.77893295,  1.39712302,  0.44018893,  0.25842169,  0.62286258,
          1.07338396,  0.76700336,  1.37102135,  1.31933657,  1.69413241,
          2.65465459,  2.51004593,  2.67600786,  3.35610478,  2.91599817,
          2.66174142,  2.78688375,  2.1513925 ,  2.09000544,  1.8       ,
          1.35148285]),
  array([ 0.10711633,  0.14219169,  0.25286393,  0.54276823,  0.53881591,
          0.75968704,  0.67347769,  0.73676474,  0.81378788,  0.93893092,
          1.28485223,  1.2111761 ,  1.66839135,  2.04652061,  2.47520212,
          2.3985014 ,  1.92157021,  1.09932218,  0.75564003,  0.2957186 ,
         -0.0646772 , -0.03506537, -0.55865013, -0.72474144, -0.39296577,
          0.22459349,  0.29709974,  0.82656829,  0.32954807,  0.79731293,
          1.74649321,  1.73761481,  1.99152563,  2.38909973,  2.26740621,
          2.02741262,  1.68503181,  2.24095678,  2.50430998,  2.55129347,
          2.80028719]),
  array([-2.51911778, -2.22501919, -1.76739127, -2.05830463, -1.77124585,
         -1.2152629 , -0.90271724, -0.1495335 ,  0.23462399,  0.70397272,
          0.7332816 ,  0.98916029,  1.47115973,  1.81624248,  1.75909092,
          2.25221661,  2.42912762,  2.1272567 ,  1.77374033,  1.15462655,
          1.30405557,  1.31525416,  0.88516309,  1.20194417,  1.08857701,
          1.0828702 ,  1.22720862,  0.87398103,  0.408143  ,  0.40888112,
          1.37492871,  1.32707518,  2.52102038,  2.07327117,  1.93186658,
          2.35856737,  2.08509056,  1.80018891,  2.05365439,  1.71568257,
          1.59593275]),
  array([ 0.18451908, -0.17143559, -0.71136574, -0.66438356, -0.33678265,
         -0.45647898,  0.60693596,  1.10898814,  0.54769106,  0.37333211,
          0.41978652,  0.37917727,  0.54414714,  0.20698456,  0.30756953,
          0.55414079,  0.5482136 ,  0.91452866,  1.00050137,  0.99287701,
          0.64937187,  1.11925529,  1.68500752,  0.90437809,  0.70338216,
          0.7612491 ,  1.18562626,  1.19632349,  0.66930231,  0.97220179,
          0.52427636,  0.43175289,  0.72459887,  1.22756563,  0.36907632,
          0.55621653,  0.3754758 ,  0.26571603,  0.24128271,  0.31286599,
         -0.57709058]),
  array([-0.52298246, -0.55292014, -0.79656109, -0.7441611 , -0.78638693,
         -0.89105338, -0.85631941, -0.68237223, -0.89268947, -0.35440837,
         -0.19849466, -0.21907114, -0.44075278, -0.16132427, -0.12008191,
         -0.29574572,  0.02060651, -0.02017922,  0.01769773,  0.09348673,
          0.22640832,  0.23182058,  1.16325543,  1.33526453,  1.12500106,
          1.10017889,  1.09402931,  0.59966391,  0.56775499,  0.94619015,
          1.39889993,  1.37556962,  1.47981329,  1.99396204,  1.87948973,
          1.68399343,  1.39764672,  0.95607032,  1.36565935,  0.70967083,
          1.0656553 ]),
  array([ 0.15889422, -0.17903346, -0.72475263, -0.02220257, -0.02351019,
          0.19955703,  0.31897737,  0.49629054,  0.94804025,  0.43009798,
         -0.16103559, -0.86585199, -0.79204106, -0.41604199, -0.36944587,
         -0.88554543, -0.30515458, -0.05766058,  0.00883056,  0.96481224,
          0.72904337,  0.73899696,  1.7892415 ,  1.43636969,  1.86513198,
          1.21038778,  1.81250796,  1.29650538,  0.6574997 ,  1.61188537,
          2.76588412,  2.70888314,  2.80700636,  2.73863821,  2.21085444,
          2.47716289,  1.35609295,  0.38112771,  0.74143877,  0.42743827,
          0.77953242]),
  array([-0.5181664 , -0.53529673, -0.78401429, -0.34779775, -0.71467824,
         -0.81911058, -0.79246011, -0.64566265, -0.54861055, -1.37685678,
         -0.90736471, -1.2608212 , -0.78459814, -0.76978516, -0.37055398,
         -0.20163463, -0.29040893, -0.44123996, -0.80605261, -0.70859278,
         -0.20156304,  0.19466914,  1.04913483,  0.76418415,  1.06764502,
          0.62453852,  0.64663689,  1.20634624,  1.16192988,  0.60002755,
          1.56216017,  1.53088842,  1.36900933,  0.89715314,  1.25787937,
          1.44437287,  1.65347282,  1.03542886,  0.99688394,  1.06392   ,
          0.57200735]),
  array([ 0.84539759,  0.50770405,  0.6888761 ,  0.96264578,  0.61416157,
          0.52235869,  0.58423135,  0.38289803,  0.15089291, -0.62387771,
         -0.48098031, -0.85905305, -0.81826649, -0.74615283, -0.32881028,
         -0.49323436, -1.06090996, -0.89957823, -0.35820541, -0.3503122 ,
         -0.26259486,  0.21056729,  0.2184374 ,  0.46248146,  0.70615718,
          1.15062064,  1.14044912,  0.7074441 ,  0.72089775,  1.05026597,
          1.9323173 ,  1.86741935,  1.55824889,  2.11691475,  2.39986209,
          2.55541369,  2.38285452,  1.53915542,  1.47117778,  1.61419003,
          1.53444594]),
  array([ 0.77023062,  0.86808133,  1.36188566,  1.75198169,  2.02101228,
          1.78888693,  2.04653236,  2.07390227,  1.24168557,  1.36938388,
          1.76679909,  1.77448713,  1.33086859,  0.64351138, -0.17296726,
         -0.28944301,  0.125652  , -0.26282062, -0.51114139, -0.49326286,
         -0.34807136, -0.44780788,  0.50900654,  0.70927743,  0.50163249,
          0.57580543,  0.16110889,  0.19553542, -0.73003438,  0.26259486,
          1.20920681,  1.25471403,  1.09884753,  0.74230749,  0.74117183,
          0.11271097, -0.13043777, -0.22835921, -0.31069425, -0.29873143,
         -0.4225269 ]),
  array([ 2.59192239,  2.36301914,  2.3145695 ,  2.39733965,  2.01280689,
          1.79741311,  1.73166326,  1.34135106,  1.07180684,  1.16295775,
          1.21216247,  0.82558214,  0.31696128,  0.65817338, -0.2358351 ,
         -0.30745519, -0.32627894, -0.71321578, -0.9895679 , -1.38161659,
         -1.73152969, -1.35656278, -2.0077466 , -1.94370313, -2.31507004,
         -1.04312828, -0.01601906,  0.06167374,  0.1213035 ,  0.06237972,
          1.16889701,  1.20353317,  1.06487957,  1.10996501,  1.15913442,
          1.8195428 ,  1.86281412,  1.68672049,  1.65850932,  1.29988098,
          1.67447412]),
  array([ 1.87296636,  1.66937935,  2.22638604,  1.8322581 ,  1.8443341 ,
          1.69641937,  1.87647102,  1.59715813,  1.69878181,  1.22295898,
          1.48362864,  1.48528192,  0.97128913,  0.68217835,  0.4709242 ,
         -0.34060654, -0.72598051, -1.24058492, -1.49231158, -1.39930399,
         -1.74080553, -1.30149799, -0.85150857, -0.67938988, -0.52075564,
         -0.40922094, -0.34724516,  0.67744654,  1.24009075,  1.78085338,
          2.35263419,  2.3736149 ,  2.13612807,  1.19667985,  0.82380375,
          0.52521104,  0.65590458,  0.51307486,  0.43795339,  1.24439017,
          1.91787615]),
  array([ 1.73106557,  1.22347184,  1.08145259,  1.17715036,  1.14874382,
          0.95229201,  0.90859381,  0.9843741 ,  0.70699935,  0.83811328,
          0.91977434,  0.88931003,  0.66871166,  0.34936246,  0.53400295,
          0.41459479,  0.09766456, -1.19273729, -1.02677455, -1.37654002,
         -1.82767618, -1.87483055, -1.58299708, -1.37444196, -1.18449796,
          0.03873306,  0.08427592,  0.17883841, -0.3155185 ,  0.17062231,
          0.76276808,  0.81494337,  1.18790856,  1.289855  ,  1.37411659,
          1.02260547,  1.1663638 ,  0.56200034,  0.92656939,  0.93933759,
          1.31163655]),
  array([ 0.87965216,  0.97543789,  1.16181481,  1.23583475,  0.88203896,
          0.67493031,  0.31971152, -0.2122142 , -0.19165692, -0.40486525,
         -0.03594426,  0.21625366, -0.04344279, -0.38384182, -0.66943754,
         -0.76407827, -0.78220795, -2.26964326, -1.61748447, -1.9771376 ,
         -1.90855384, -1.91091583, -1.53608874, -0.80900554, -0.62863457,
         -0.0287803 ,  0.44343957,  0.55455929,  0.63151978,  0.13818068,
          0.64508543,  0.64050969,  0.52112335,  1.07018455,  0.6939624 ,
          0.46135526,  0.17620731,  0.09291811, -0.40932508, -0.41488195,
         -0.026601  ])],
 'METEOR': [array([-0.73972155, -0.09119364,  0.46000496,  0.21994074,  0.42104741,
          0.577002  ,  0.53253052, -0.1719626 , -0.20770773,  0.07737105,
          0.52741925,  0.40685332, -0.40942422, -0.34198244, -0.4824151 ,
         -0.189852  , -0.10190602, -0.19982939,  0.19012144,  0.22478312,
          0.06003755, -0.22315876, -0.56441204, -0.26623244, -0.02655744,
          0.22068281,  0.3896253 ,  0.74510771,  0.90420093,  0.65816899,
          1.97196554,  1.93672318,  1.83151642,  1.60684691,  1.19879593,
          0.37986787,  0.45717086,  0.63281   ,  0.23144799, -0.63004171,
         -0.35091226]),
  array([-1.30761385, -1.08563652, -1.23070219, -0.83792247, -0.61645579,
         -0.43567594,  0.03044009,  0.18072474, -0.08892788, -0.01672636,
          0.38215462,  0.50828641,  1.60274781,  0.73111054,  0.86893165,
          0.73470303,  1.19060784,  0.55171622,  0.30829871,  0.67600486,
          0.89475554,  0.54922447,  1.26690551,  0.13268847, -0.02508629,
          0.28112956,  1.22589867,  2.88738959,  2.14954988,  2.6760302 ,

In [15]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

41
41
41
=
1689

,subject,gpt_layer,WER,BLEU,METEOR,BERT
0,S1,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,S1,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,S1,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
3,S1,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,S1,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,S2,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,S2,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,S2,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,S2,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,S2,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,S3,6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
11,S3,7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
12,S3,8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
13,S3,9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
14,S3,10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [16]:
results_df['BERT'] = results_df['BERT'].apply(np.mean)
to_file = results_df.drop(columns=['WER','BLEU','METEOR']).rename(columns={'BERT':'significantly_decoded'})
to_file

   subject  gpt_layer  significantly_decoded
0       S1          6               0.000000
1       S1          7               0.414634
2       S1          8               0.341463
3       S1          9               0.341463
4       S1         10               0.024390
5       S2          6               0.000000
6       S2          7               0.024390
7       S2          8               0.219512
8       S2          9               0.000000
9       S2         10               0.024390
10      S3          6               0.000000
11      S3          7               0.000000
12      S3          8               0.000000
13      S3          9               0.000000
14      S3         10               0.000000

In [17]:
# gpt_layer_6=np.array(results_df.loc[0, 'BERT']).mean()
# gpt_layer_7=np.array(results_df.loc[1, 'BERT']).mean()
# gpt_layer_8=np.array(results_df.loc[2, 'BERT']).mean()
# gpt_layer_9=np.array(results_df.loc[3, 'BERT']).mean()
# gpt_layer_10=np.array(results_df.loc[4, 'BERT']).mean()
# to_file = pd.DataFrame({'gpt_layer':[6,7,8,9,10], 'significantly_decoded': [gpt_layer_6,gpt_layer_7,gpt_layer_8,gpt_layer_9,gpt_layer_10]})
to_file.to_csv('imagined_speech_gpt_layer.csv', index=False)

to_file

   subject  gpt_layer  significantly_decoded
0       S1          6               0.000000
1       S1          7               0.414634
2       S1          8               0.341463
3       S1          9               0.341463
4       S1         10               0.024390
5       S2          6               0.000000
6       S2          7               0.024390
7       S2          8               0.219512
8       S2          9               0.000000
9       S2         10               0.024390
10      S3          6               0.000000
11      S3          7               0.000000
12      S3          8               0.000000
13      S3          9               0.000000
14      S3         10               0.000000