In [8]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_movie/presto.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['window_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('presto', 'WER'): array([ 0.32187847,  0.56803756, -0.01503934,  0.19242198, -0.32189659,
        0.23068393,  0.42608143,  0.19448613,  0.47821188,  0.23526341,
        0.88178405, -0.3890192 , -1.21424986, -1.39585843, -1.58178445,
       -0.84706079, -1.05826618,  0.21744906,  0.05098364, -1.20463479,
       -0.9426986 , -0.80050187, -0.88099419, -0.90453403, -1.04755938,
       -0.9910207 , -0.99649191, -0.78539647, -0.8781085 , -0.86643552,
       -0.34237614, -0.53970867, -0.01265575,  0.20282414,  0.51121335,
        0.07398817, -0.44231287,  0.6423086 ,  0.58419   ,  1.13499697,
        0.4872186 ,  0.10624879, -0.08391814, -0.00916737, -0.95941353,
       -0.80060249, -0.1533576 , -0.7097151 , -0.86840753, -0.99138448,
       -0.75645585, -0.61034485,  0.55991439,  0.43154766,  0.89281533,
        1.23069233,  1.4667176 ,  1.40615645,  2.24427351,  3.10873377,
        3.0567028 ,  2.63779803,  3.57548854,  4.2765146 ,  4.29944728,
        3.72694072,  3.30739918,  3.71827009,  2.02522478,  2.07591775,
        2.48518399,  3.05495492,  2.91579235,  2.95065853,  1.17335776,
        1.20727996, -0.05021824,  0.30684241,  0.19203123,  0.82802636,
        0.73325145, -0.16436228,  0.00540746,  0.26900757, -0.44770043,
       -0.61127288, -0.71902339,  0.40441816, -0.57735027, -0.25628788,
       -0.70479387, -0.91661623, -0.92715373, -1.12070794, -1.21326809,
       -1.24960118, -1.05089682, -1.31770669, -1.45170462, -2.21400401,
       -2.45439778, -1.00627398, -1.19271046, -1.09636241, -1.27694721,
       -2.02721956, -2.02113021, -1.89070208, -1.81049679, -1.75255464,
       -1.70271806, -1.55767388, -1.64814651, -1.56829653, -1.29278937,
       -1.2667166 , -1.6455395 , -1.39269241, -1.27517313, -0.54403307,
       -1.45004815, -1.6087777 , -1.53392998, -2.18419602, -1.18933657,
       -0.78475121, -0.81727578, -0.7922968 ,  1.75490808,  1.47658652,
        2.14329383,  2.0492673 ,  1.98241338,  2.23400613,  2.81586324,
        2.7364458 ,  2.10668103,  2.55566147,  2.5259384 ,  3.5459443 ,
        2.96695415,  3.40422578,  2.72496135,  3.08594459,  3.15797104,
        3.77488887,  3.08535961,  2.18746125,  2.01065678,  2.29131305,
        1.11008532,  0.59458482,  0.76944606, -0.16036863, -0.0316386 ,
        0.12570344,  0.29241125,  0.45195269,  0.65882927,  0.16805379,
       -0.02786511, -0.18257419, -1.0786585 , -1.00416961, -0.99138448,
       -0.85057197, -0.82495791, -1.02841893, -1.73205081, -0.96131896,
       -0.7044449 , -1.01789569, -0.50267369, -0.57374561, -0.51152724,
       -0.55485132, -0.46138014,  0.25961323,  0.6521136 ,  0.76351005,
        1.45542314,  0.65824263,  2.23255983,  1.57565123,  1.67281891,
        2.45543881,  3.19467149,  2.98245168,  2.2639618 ,  1.26430434,
        0.96459556,  1.36979261,  0.79166972,  1.15055322,  1.4445929 ,
        1.92334761,  1.3457673 ,  1.44337567,  0.9345507 ,  0.42954656,
        0.4779369 ,  0.5407697 ,  2.37719089,  1.75400659,  1.72135607,
        2.17751504,  1.22998101,  0.12924   ,  0.71402483,  1.60365486,
        0.74279715,  0.7596365 ,  1.38873015,  1.95070712,  2.29741626,
        1.45362362,  1.92982022,  1.59408382,  1.59408382,  1.74471349,
        1.59062563,  1.31378274,  0.35736058,  0.65085651,  0.63442926,
        0.62885987,  0.98449518,  0.4274094 ,  0.47754373,  0.2453767 ,
        0.23676411,  1.28373482,  0.91917479,  1.69083108,  1.38236708]), ('presto', 'BLEU'): array([ 7.48028415e-01,  7.20389480e-01,  6.77414183e-01,  2.76042915e-01,
        2.02278349e-01, -2.24792923e-01,  4.04770520e-01,  8.36508398e-01,
        6.03205874e-01,  5.66591447e-01, -2.92103341e-01, -7.53953232e-01,
       -3.54828767e-01, -6.73058144e-01, -3.19293511e-01, -1.42938395e-01,
       -2.34375353e-01,  8.95852004e-01,  8.92082784e-01,  1.14049547e+00,
        1.04926217e+00, -1.40510582e-01,  3.80262025e-01,  5.53565671e-01,
        4.72993205e-01,  4.83300094e-01,  2.25704309e-02, -4.24458327e-01,
        3.47165902e-01,  7.98629568e-01,  7.43829101e-01,  9.07130063e-01,
        7.28986226e-01,  3.75725442e-01, -3.11756093e-01, -4.35595672e-01,
       -3.64024441e-01, -2.86681098e-02, -6.71085210e-02,  3.11487688e-01,
        7.86543820e-01,  7.36442379e-01,  3.62203755e-01,  3.75320474e-01,
        5.09091200e-01,  4.86135912e-01,  6.65935609e-01,  2.57205776e-01,
       -2.25762396e-03,  3.93189986e-01,  7.70220935e-01,  6.12770123e-01,
        1.37758649e+00,  1.71179344e+00,  1.65530886e+00,  2.06098750e+00,
        2.62527680e+00,  2.61210282e+00,  2.80846702e+00,  3.56052089e+00,
        2.74410650e+00,  2.74127956e+00,  2.98757813e+00,  2.91182961e+00,
        3.29413824e+00,  3.07224523e+00,  2.88372113e+00,  2.62553664e+00,
        2.03729684e+00,  2.82389075e+00,  2.88852224e+00,  2.60185185e+00,
        1.84121518e+00,  5.95225548e-01, -9.66586359e-02,  4.02835835e-01,
        2.91328574e-01,  3.37481937e-01, -5.65862730e-01,  4.28571429e-01,
        7.43436003e-01,  2.67382786e-01,  1.98537743e-01,  2.02943740e-01,
       -3.18946878e-01, -4.20496320e-01, -4.67909354e-01, -2.31865268e-01,
       -9.77972050e-02, -6.58865041e-02,  3.42319885e-01,  3.32573858e-01,
        4.09177184e-01,  4.65004778e-01, -6.43674570e-02, -5.42170609e-01,
       -2.79871039e-02,  4.25160511e-01, -2.32382515e-01, -4.19118444e-01,
       -4.42861048e-01,  4.74578998e-02, -3.59295090e-01,  1.65183869e-01,
       -6.09912036e-02, -6.87059129e-02, -7.36459694e-01, -4.41836082e-01,
       -6.47467353e-01, -9.57043566e-01, -1.03407135e+00, -1.03805925e-01,
       -5.95525777e-01, -1.08619340e+00, -1.47009455e+00, -1.09814677e+00,
       -1.19813513e+00, -1.13483277e+00, -1.31076884e+00, -1.59831397e+00,
       -2.16817283e+00, -2.44084492e+00, -2.42384934e+00, -2.54409735e+00,
       -2.03734758e+00, -1.34095680e+00, -8.98192640e-01, -1.21428916e-01,
        5.54963774e-01,  5.33115103e-01,  1.32625884e+00,  1.30315317e+00,
        1.16867204e+00,  9.94493047e-01,  1.38218948e+00,  1.38421967e+00,
        1.82149525e+00,  1.86240569e+00,  1.88931153e+00,  2.24254583e+00,
        1.74172392e+00,  1.54690204e+00,  1.97304870e+00,  1.96275669e+00,
        1.53213737e+00,  1.06545699e+00,  1.39521577e+00,  9.20488493e-01,
        5.35438036e-01,  4.11288471e-01,  4.45144140e-01,  1.41863660e-01,
        3.10537863e-01, -1.25779423e-01, -1.58145650e-01, -6.08516060e-01,
       -4.44994159e-01, -4.49675682e-01, -1.55689776e-02, -6.41567385e-01,
       -9.52410715e-01, -9.31621496e-01, -1.73043402e+00, -1.72415485e+00,
       -1.52673370e+00, -2.36960067e+00, -2.54424596e+00, -2.38677632e+00,
       -2.13232005e+00, -1.71138615e+00, -1.63106841e+00, -1.67399496e+00,
       -1.31168224e+00, -7.28336143e-01, -6.97715727e-01, -1.14995370e+00,
       -1.29724894e+00, -7.65281519e-01, -1.26728933e+00, -1.15856131e+00,
       -8.05910495e-01, -6.82825508e-01, -7.22230209e-01, -6.41083217e-01,
       -4.50937321e-01, -3.50365337e-02,  8.00792276e-01,  1.06682860e+00,
        1.15676322e+00,  1.20129230e+00,  8.26908721e-01,  1.32825967e+00,
        1.38549465e+00,  1.32374406e+00,  1.06196600e+00,  4.65713492e-01,
        9.74381175e-01,  9.15079364e-01,  1.97854715e+00,  2.28331290e+00,
        2.37785736e+00,  2.39822032e+00,  3.18283611e+00,  3.15324001e+00,
        3.06995636e+00,  2.71487332e+00,  1.95762251e+00,  1.92973441e+00,
        2.31818118e+00,  1.86385389e+00,  1.79584920e+00,  2.23944582e+00,
        2.63139383e+00,  2.33013480e+00,  1.91793744e+00,  1.31561442e+00,
        1.49224801e+00,  2.10473022e+00,  2.23395916e+00,  1.78015573e+00,
        1.36881709e+00,  1.49892711e+00,  7.36563670e-01,  3.32048285e-01,
        8.75865367e-01,  8.87717302e-01,  9.00683415e-01,  9.81894895e-01,
        6.53449512e-01,  7.18240389e-01,  3.83185876e-01,  9.47590215e-01,
        8.41823237e-01,  1.36730903e+00,  1.07304332e+00]), ('presto', 'METEOR'): array([ 2.47670372,  2.22902474,  1.02553207,  0.50742409,  0.45303443,
        0.07535443,  0.3511227 ,  1.79625853,  1.69901823,  1.46446026,
       -0.32655504, -0.72785602, -0.34276481, -0.98728911, -0.39561192,
       -0.21177899, -0.32443046,  0.58250132,  0.56579079,  0.73636568,
        0.99761277,  0.03829568,  0.70635315,  0.65662303,  0.52588837,
        0.52577539,  0.08826855, -0.70825358, -0.05394942,  0.32143051,
        0.23810848,  0.34604203,  0.93528233,  0.63693532,  1.01793625,
        0.91533353,  1.47298247,  1.36936446,  1.28034778,  1.55868826,
        1.58796786,  1.22295959,  0.91853762,  1.00920481,  1.03097292,
        1.44074311,  1.54539855,  1.28050422,  0.99205028,  1.12733337,
        1.50900606,  1.47575511,  2.02144609,  1.85548425,  1.72603177,
        2.02672617,  2.51263544,  2.62341936,  2.86369466,  3.59652647,
        2.70218697,  2.56842004,  2.83252541,  2.30950592,  2.58568176,
        2.42830678,  2.37775394,  2.03390223,  1.73276694,  2.43381313,
        2.57996055,  1.81129667,  1.12294016,  0.01313903, -0.62056973,
       -0.22432258, -0.42877496, -0.32365755, -1.08264665,  0.14817754,
        0.38943233, -0.02044234, -0.21337289, -0.18536173, -0.1567899 ,
       -0.26091575, -0.27977367, -0.55524874, -0.095144  , -0.11512039,
        0.14572632,  0.15157023,  0.26178961,  0.19787626, -0.30766741,
       -0.67727087, -0.14138077, -0.16254212, -0.67314433, -0.72033521,
       -0.61623859, -0.21004008, -0.75878453, -0.73466895, -0.52151619,
       -0.57271836, -1.07577243, -0.82287992, -0.55043004, -0.4708487 ,
       -0.07857942,  0.35392179, -0.14999726, -0.26663443, -0.16757596,
        0.43773406,  0.34109219, -0.34573897, -0.48756985, -0.63519426,
       -1.51340609, -1.7260393 , -2.10034693, -2.10616604, -1.8365633 ,
       -1.33426159, -0.9840967 , -0.43507161,  0.09169587,  0.03477633,
        0.56325516,  0.55960039,  0.1412541 ,  0.11403847,  0.46183794,
        0.6176501 ,  0.88911748,  1.03201405,  1.39010575,  1.71159289,
        1.3015789 ,  1.21390777,  1.39264207,  1.37888406,  0.68247206,
        0.20942341,  0.53028047,  0.55885385,  0.24712742,  0.42680435,
        0.81136321,  0.62813239,  0.81471057,  0.79201132,  0.60322977,
        0.22112102, -0.11940668,  0.42029188,  0.42780492, -0.08660614,
        0.01026573,  0.39852286, -0.29931212, -0.29127173, -0.10506474,
       -0.92080757, -0.79485447, -0.74430149, -0.59603917, -0.56548333,
       -0.40004843, -0.83789117, -0.5760547 , -0.13062851, -0.3414088 ,
       -0.75195195, -1.12589144, -0.31096761, -0.12372546,  0.00715364,
       -0.12384078, -0.85354537,  0.35041794, -0.40179634, -0.65835799,
       -0.3398666 ,  0.41003733,  0.6374564 ,  0.39226428,  0.41166683,
        0.12482366,  0.60281842,  0.66547828,  1.04936469,  0.80703841,
        1.35090513,  1.94321173,  1.11106687,  2.02869738,  2.40486248,
        2.55294361,  2.49524926,  3.15677988,  3.18509055,  3.1964695 ,
        2.91038873,  2.36186059,  2.4099051 ,  3.09272429,  2.68577267,
        2.96256186,  3.4347996 ,  3.23095218,  3.04553315,  2.65937276,
        2.12766316,  1.90206648,  1.59273847,  2.06671119,  1.63524616,
        1.51961794,  1.57528849,  0.99764908,  0.67624525,  1.1196379 ,
        1.14902828,  0.88044153,  0.31920883,  0.15734149,  0.24954198,
       -0.03092596,  0.37856102,  0.28553441,  0.66295795,  0.43867513]), ('presto', 'BERT'): array([ 3.9280827 ,  4.06608   ,  4.537503  ,  3.246677  ,  3.9269507 ,
        3.4492004 ,  2.9008102 ,  3.1264746 ,  3.6219797 ,  3.5737484 ,
        3.0694065 ,  3.0114064 ,  2.9161289 ,  1.2687162 ,  2.0454578 ,
        2.314654  ,  2.2854729 ,  2.0254717 ,  2.2734585 ,  1.777434  ,
        2.1308613 ,  0.8282308 ,  0.92461765,  0.6436047 ,  0.75209033,
        0.4079655 ,  0.90918046,  0.24628551,  1.770638  ,  1.7422142 ,
        2.2330856 ,  2.930138  ,  2.6042404 ,  2.30367   ,  2.2403393 ,
        1.3778328 ,  2.273322  ,  2.2352648 ,  1.8549731 ,  1.922163  ,
        2.274231  ,  2.7812717 ,  2.7087991 ,  2.2526705 ,  2.0662804 ,
        2.0571187 ,  1.9709134 ,  1.3264018 ,  1.2307894 ,  1.59801   ,
        0.1118053 ,  0.31056124,  0.82049197,  1.647553  ,  1.2127447 ,
        1.0364655 ,  0.26230636,  0.7218841 ,  0.12352582,  0.4570766 ,
        0.84231085,  0.74226797,  0.6505813 ,  0.6489397 ,  0.34977508,
        0.94065714,  0.43926287,  0.30976057,  0.44722626, -0.14905235,
        0.7944369 ,  0.10805847,  0.6561368 ,  0.09633605,  0.46634287,
        0.57922155,  0.2570906 ,  0.04024755, -0.0634398 ,  0.08495223,
        0.23960058,  0.6137128 ,  1.533601  ,  1.1183252 ,  0.72923625,
        1.6998557 ,  1.8219066 ,  0.7935732 ,  0.96380746,  1.5006019 ,
        1.4510146 ,  1.7460711 ,  2.4968436 ,  3.258377  ,  2.5616498 ,
        2.97831   ,  3.0073981 ,  3.1828089 ,  2.397713  ,  2.2508092 ,
        2.3872495 ,  1.600528  ,  1.1960558 ,  1.7799968 ,  2.238616  ,
        1.8972191 ,  1.7318875 ,  2.4642692 ,  2.6281528 ,  2.669727  ,
        2.5146446 ,  2.183404  ,  2.3284712 ,  1.5647105 ,  1.8149008 ,
        1.7592335 ,  1.2099978 ,  1.5888792 ,  1.6240592 ,  0.92082494,
        1.6506832 ,  1.4180559 ,  1.4542631 ,  0.6087576 , -0.4043702 ,
        0.5712779 ,  0.13072778,  0.23282707,  0.28426316, -0.02981526,
       -0.42167804,  0.02927308, -0.26370937, -0.603021  , -1.1320888 ,
       -1.1116743 , -0.8510339 , -0.8763934 , -0.6451763 , -0.7217397 ,
       -0.24165708,  0.3401257 ,  0.16482462,  0.3886533 , -0.26564962,
       -0.1595925 , -0.29154977, -0.2997395 , -0.19530869, -0.23282702,
       -0.18238361, -0.23189634, -0.5130197 , -0.3390303 ,  0.22432482,
       -0.19493754, -0.74677324, -0.8729761 ,  0.06354593, -0.19989234,
        0.02626093, -0.10549083, -1.6140975 , -0.86902744, -0.49614346,
        0.14158705,  0.74530864, -0.11281751, -1.1854186 ,  1.3511024 ,
        0.9991103 ,  0.9755109 ,  0.86160564,  1.502649  ,  1.4204565 ,
        0.56182194,  1.8403038 ,  1.3878038 ,  1.7210178 ,  1.8373567 ,
        2.3390274 ,  2.164898  ,  1.7759696 ,  2.162983  ,  1.6194681 ,
        1.5717951 ,  1.4151496 ,  1.7071751 ,  1.300496  ,  1.3654679 ,
        1.3266402 ,  1.2979151 ,  0.8696084 ,  1.1737247 ,  0.96344036,
        1.8991148 ,  1.8276734 ,  2.2967076 ,  2.4555864 ,  1.8737423 ,
        1.9692973 ,  2.0153909 ,  2.4954393 ,  1.5286529 ,  2.3717837 ,
        2.0416553 ,  2.4892988 ,  2.529762  ,  2.1375022 ,  2.3635979 ,
        3.0137515 ,  2.846288  ,  3.712956  ,  3.694495  ,  2.0801356 ,
        3.4787521 ,  3.148781  ,  1.8651752 ,  2.2749617 ,  2.4416358 ,
        2.497618  ,  2.8611522 ,  2.310592  ,  2.3813298 ,  2.2817457 ,
        2.033154  ,  1.6765735 ,  1.1153992 ,  0.8890977 ,  0.41572148,
        1.0194498 ,  0.78637385, -0.13983959, -0.3793985 ,  1.2615356 ],
      dtype=float32)}

In [24]:
window_zscores = {'subject': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for subject in [1,2,3]:
    for task in ['presto','partlycloudy','laluna']:
        scores = np.load(f'scores/S{subject}/perceived_movie/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['subject'].append(subject)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'subject': [1, 1, 1, 2, 2, 2, 3, 3, 3],
 'WER': [array([ 0.32187847,  0.56803756, -0.01503934,  0.19242198, -0.32189659,
          0.23068393,  0.42608143,  0.19448613,  0.47821188,  0.23526341,
          0.88178405, -0.3890192 , -1.21424986, -1.39585843, -1.58178445,
         -0.84706079, -1.05826618,  0.21744906,  0.05098364, -1.20463479,
         -0.9426986 , -0.80050187, -0.88099419, -0.90453403, -1.04755938,
         -0.9910207 , -0.99649191, -0.78539647, -0.8781085 , -0.86643552,
         -0.34237614, -0.53970867, -0.01265575,  0.20282414,  0.51121335,
          0.07398817, -0.44231287,  0.6423086 ,  0.58419   ,  1.13499697,
          0.4872186 ,  0.10624879, -0.08391814, -0.00916737, -0.95941353,
         -0.80060249, -0.1533576 , -0.7097151 , -0.86840753, -0.99138448,
         -0.75645585, -0.61034485,  0.55991439,  0.43154766,  0.89281533,
          1.23069233,  1.4667176 ,  1.40615645,  2.24427351,  3.10873377,
          3.0567028 ,  2.63779803,  3.57548854,  4.2765146 ,  4.29944728,
          3.72694072,  3.30739918,  3.71827009,  2.02522478,  2.07591775,
          2.48518399,  3.05495492,  2.91579235,  2.95065853,  1.17335776,
          1.20727996, -0.05021824,  0.30684241,  0.19203123,  0.82802636,
          0.73325145, -0.16436228,  0.00540746,  0.26900757, -0.44770043,
         -0.61127288, -0.71902339,  0.40441816, -0.57735027, -0.25628788,
         -0.70479387, -0.91661623, -0.92715373, -1.12070794, -1.21326809,
         -1.24960118, -1.05089682, -1.31770669, -1.45170462, -2.21400401,
         -2.45439778, -1.00627398, -1.19271046, -1.09636241, -1.27694721,
         -2.02721956, -2.02113021, -1.89070208, -1.81049679, -1.75255464,
         -1.70271806, -1.55767388, -1.64814651, -1.56829653, -1.29278937,
         -1.2667166 , -1.6455395 , -1.39269241, -1.27517313, -0.54403307,
         -1.45004815, -1.6087777 , -1.53392998, -2.18419602, -1.18933657,
         -0.78475121, -0.81727578, -0.7922968 ,  1.75490808,  1.47658652,
          2.14329383,  2.0492673 ,  1.98241338,  2.23400613,  2.81586324,
          2.7364458 ,  2.10668103,  2.55566147,  2.5259384 ,  3.5459443 ,
          2.96695415,  3.40422578,  2.72496135,  3.08594459,  3.15797104,
          3.77488887,  3.08535961,  2.18746125,  2.01065678,  2.29131305,
          1.11008532,  0.59458482,  0.76944606, -0.16036863, -0.0316386 ,
          0.12570344,  0.29241125,  0.45195269,  0.65882927,  0.16805379,
         -0.02786511, -0.18257419, -1.0786585 , -1.00416961, -0.99138448,
         -0.85057197, -0.82495791, -1.02841893, -1.73205081, -0.96131896,
         -0.7044449 , -1.01789569, -0.50267369, -0.57374561, -0.51152724,
         -0.55485132, -0.46138014,  0.25961323,  0.6521136 ,  0.76351005,
          1.45542314,  0.65824263,  2.23255983,  1.57565123,  1.67281891,
          2.45543881,  3.19467149,  2.98245168,  2.2639618 ,  1.26430434,
          0.96459556,  1.36979261,  0.79166972,  1.15055322,  1.4445929 ,
          1.92334761,  1.3457673 ,  1.44337567,  0.9345507 ,  0.42954656,
          0.4779369 ,  0.5407697 ,  2.37719089,  1.75400659,  1.72135607,
          2.17751504,  1.22998101,  0.12924   ,  0.71402483,  1.60365486,
          0.74279715,  0.7596365 ,  1.38873015,  1.95070712,  2.29741626,
          1.45362362,  1.92982022,  1.59408382,  1.59408382,  1.74471349,
          1.59062563,  1.31378274,  0.35736058,  0.65085651,  0.63442926,
          0.62885987,  0.98449518,  0.4274094 ,  0.47754373,  0.2453767 ,
          0.23676411,  1.28373482,  0.91917479,  1.69083108,  1.38236708]),
  array([-0.57937068, -0.65411313,  0.41367176,  0.89114837, -0.69885303,
          0.40810265, -0.00547184,  0.86955102,  0.05021824,  0.26845243,
          1.52400152,  2.49051803,  1.14731762,  0.76430957,  1.32209761,
          0.67642269,  0.05109761,  1.03235129,  0.91607121,  0.74659924,
          1.17141018,  0.95894335,  0.71824039,  1.61356859,  1.26137619,
          1.41826202,  1.5678272 ,  1.21701459,  1.36253177,  1.01443689,
          1.32248575, -0.53987041, -0.54469346, -0.34365569,  0.09160006,
          0.13000563, -0.24012393, -0.22553363,  0.37243498, -0.74536429,
          0.68456997,  0.00418858, -0.69646466, -0.28816853,  1.37100604,
          0.51524466,  1.05584261,  1.21268171,  0.86928689,  1.67413939,
          1.67770044,  1.02131297,  2.01198779,  1.75784796,  1.32745018,
          1.56015275,  1.38141451,  1.65434968,  0.34752402,  0.5530745 ,
          0.25929878,  0.87077718,  1.00963342,  0.44567459,  1.67661153,
          0.65305191,  0.70098033,  0.5619776 ,  1.25356634,  0.53898026,
          0.40782648,  1.03586669,  0.82767643, -0.17586311, -0.35341758,
          0.68290175,  0.32088164,  0.22207644,  0.56025237, -0.21257718,
         -1.14203056, -0.88318644, -0.73857398, -0.83558453,  0.72011924,
         -0.01147154, -0.49024873, -0.15984477,  0.31311215, -0.01318239,
         -0.4354556 , -0.89968447, -0.12685903, -1.61862222, -0.82345803,
         -0.17670853, -0.85783483, -0.67915038,  0.00962295,  0.37235088,
         -1.30654916, -0.60461272, -0.63907604, -0.51121335, -0.54069129,
         -0.43151697, -0.28541155, -0.34996607, -0.24241301, -0.16119439,
         -0.14839672, -0.14514203,  0.0460969 , -0.39372844, -0.70195258,
         -1.24522724,  0.45228826,  0.20469574,  2.06063464,  1.52695433,
          1.24162766,  1.20527641,  1.55155418,  1.11581175,  0.90119407,
          0.70133156,  1.85025549,  1.82574186,  1.39655172,  1.80230851,
          1.57366477,  2.77534249,  2.91044122,  2.66254842,  2.8548025 ,
          1.14220575,  1.09471681,  1.93697554,  2.07626608,  1.48822494,
          1.02281605,  0.75807004, -0.63440674,  0.2309211 ,  0.87287156,
          0.49055246,  0.81652642,  0.47021164,  1.10633644,  2.83124   ,
          3.29213461,  3.70133574,  3.17379777,  2.61510689,  0.28221626,
          1.26634403,  0.85753664,  1.88170924,  1.84451868,  1.70160271,
          2.10589235,  1.00463701,  1.62288234,  2.30947646,  0.4493959 ,
          0.76859493,  0.76225171,  0.41227995,  0.76584243, -0.07173806,
          0.27978024,  0.1405707 ,  0.45557345,  0.49970027,  0.27288393,
          1.29591619,  1.49956489,  0.64912486,  0.84513481,  0.54472524,
          0.69126056, -0.21877339, -0.79805407, -0.87240764, -0.67044183,
         -0.46704912, -0.41107867, -0.24177596,  0.48495273,  0.59991441,
          2.21874456,  0.45341345, -0.7951068 , -0.81427221, -1.01896773,
         -0.76133777, -1.00453201, -1.25565588, -1.18877425, -1.43325956,
         -0.02978777, -0.57835718,  0.22222222,  1.72570707,  1.52662801,
          1.66717433,  0.66529914,  0.46787599,  0.47372302,  0.78329678,
          1.08347268,  0.88178405,  0.63754981,  0.56921939, -0.43496995,
         -0.37917727, -1.17692778, -1.14248939, -1.99456328, -1.1763765 ,
         -0.94599316, -1.05394799, -1.16711373, -0.9544029 ,  0.22122974,
          0.14123842, -0.02446312,  0.01990469,  0.12380638, -0.10762361,
         -0.3029504 , -0.14057312, -0.17259885, -0.33429868,  0.63754981,
          0.37679332,  0.46246549,  0.30002344,  0.20432542, -1.39422775,
         -1.84281296, -1.62382806, -1.40866761, -1.68361554, -1.74143841,
         -1.46490812, -0.52959523, -0.55126695, -0.57112617, -1.94580994,
         -1.3006047 , -1.45781587, -1.490586  , -0.949158  , -0.16390751,
         -0.15551716, -0.20936726,  0.67749689,  0.58989097,  0.21507971,
          1.08742057,  0.68858273, -0.16661063]),
  array([ 7.13076184e-01,  1.35837708e+00,  2.34197321e+00,  9.85706013e-01,
          8.92294177e-01, -4.11401864e-02,  6.08695652e-01,  1.47802357e+00,
          1.65754018e+00,  1.15878673e+00,  3.94610899e-01,  2.72237292e+00,
          2.13221249e+00,  2.55567238e+00,  1.92209395e+00,  3.05868724e+00,
          1.46578399e+00,  1.94332945e-01,  1.02641719e+00,  6.46342555e-01,
          8.60309002e-02, -6.61915886e-01, -7.12920553e-01, -3.77964473e-01,
         -8.82456389e-01, -1.12329004e+00, -1.28237080e+00, -1.82878652e+00,
         -1.04785227e+00, -1.50678010e+00, -1.49168004e+00, -1.44126792e+00,
         -1.47945288e+00, -1.48069948e+00, -1.68138500e+00, -1.63611742e+00,
         -6.85432479e-01, -4.55022200e-01, -3.42916717e-01, -1.98109973e-01,
          3.64641527e-02, -2.49048636e-01, -2.22294382e-15, -5.29851356e-01,
          3.28057146e-01, -3.95673841e-01,  9.76447256e-02, -2.64369569e-01,
         -7.28923697e-01,  8.03824757e-01,  1.20862332e+00,  1.03739286e+00,
          6.33167295e-01,  7.37737162e-01,  1.61006088e+00,  1.75735135e+00,
          1.77826529e+00,  2.20676171e+00,  1.40343499e+00,  3.06651272e+00,
          1.24682766e+00,  1.37688979e+00,  1.36682253e+00,  1.57874036e+00,
         -1.50806382e-01,  5.60436218e-01,  1.24007081e+00,  8.65279474e-01,
          8.33441541e-01,  8.35576134e-01,  2.49037100e-01,  8.71471687e-01,
          1.29586258e+00,  1.80991938e+00,  1.20681219e+00,  1.47663315e+00,
          1.28499688e+00,  7.54317030e-01,  7.97497741e-01,  4.01834063e-01,
          7.11134704e-01,  4.66740089e-01,  9.19585550e-01, -2.60025484e-02,
          1.65543857e-02, -5.94067750e-01,  9.27057733e-02,  1.05242321e+00,
         -9.31414183e-01, -4.41145287e-01, -1.11149235e-01, -2.61443493e-02,
         -8.55661036e-01,  7.73809977e-01,  2.24123128e-01,  8.48394679e-01,
          1.45267275e+00,  1.08917648e+00,  4.26032113e-01,  6.68153414e-01,
          6.93687976e-01,  9.91384481e-01,  1.37098832e+00,  2.84930593e-01,
          1.50302226e+00,  9.75966147e-01,  1.00991932e+00,  8.50556814e-01,
          1.33472129e+00,  5.74105948e-01,  5.53398591e-01,  3.38388181e-01,
          1.07260375e+00,  6.42746931e-01,  2.41684122e+00,  1.64462193e+00,
          1.69758358e+00,  1.98183773e+00,  1.95551327e+00,  2.15739147e+00,
          2.36373459e+00,  3.02098948e+00,  2.76240477e+00,  2.67444428e+00,
          1.77048178e+00,  1.27528693e+00,  1.23712233e+00,  1.39812123e+00,
          4.89767827e-01,  8.66099697e-01,  1.81746089e+00,  1.67845125e+00,
          7.11930907e-01,  1.00347827e+00,  1.44315436e+00,  1.82545695e-01,
          7.41009025e-01, -7.14857404e-01,  1.08095394e+00,  9.03486998e-01,
          1.12316027e+00, -3.88699493e-01, -3.17643715e-01, -5.00031888e-01,
         -7.68810066e-01, -8.19231921e-02,  1.57859015e+00,  8.75473787e-01,
          2.92227725e-01, -6.29307291e-01, -4.88915319e-01,  5.53633474e-01,
          7.09219559e-01,  6.12549704e-01,  7.93903029e-01,  6.29630921e-01,
          6.51217145e-01,  3.27468505e-01,  7.80013495e-01,  5.68145145e-01,
          1.15727512e+00,  2.79787718e+00,  2.56590469e+00,  2.43216175e+00,
          2.81917685e+00,  2.22831825e+00,  2.97038197e+00,  2.97038197e+00,
          3.35411898e+00,  3.33061905e+00,  2.70500890e+00,  1.67125804e+00,
          1.53252206e+00,  2.40425427e+00,  1.71859199e+00,  2.83735185e-01,
          4.39411324e-01,  5.55411442e-01,  1.26388393e+00,  9.97559980e-01,
          8.52066257e-01,  3.25818826e+00,  1.54223083e+00,  2.28135468e+00,
          2.44102877e+00,  2.63040551e+00,  2.79723301e+00,  2.61138823e+00,
          2.48731299e+00,  1.98412907e+00,  2.34934097e+00,  3.03616812e+00,
          1.76093205e+00,  1.98815106e+00,  6.63407659e-01,  1.61510680e-01,
          1.54152824e+00,  1.58025177e+00,  1.60481919e+00,  1.41437547e-01,
          1.17838142e-01,  7.20227098e-01,  3.18686150e-01,  3.54867171e-01,
         -3.22514474e-01, -6.57951695e-02, -1.34769962e+00, -1.64791542e+00,
         -1.61078051e+00, -1.62791966e+00, -1.33401001e+00, -1.50748225e+00,
          2.97533112e-02, -2.72990076e-02,  3.17598422e-01, -6.49639190e-01,
         -6.64139304e-01, -4.40589337e-01, -1.24514827e+00, -1.90772106e+00,
         -1.91040994e+00, -2.00849675e+00, -2.11980432e+00, -1.97105491e+00,
         -1.39410984e+00, -1.04730832e+00, -1.40859800e+00,  2.15079707e-01,
          2.28276406e-01, -7.17740563e-01, -5.39330879e-01, -3.71586253e-01,
         -4.57066185e-01, -1.63763418e-01, -1.12041887e+00,  6.13794906e-01,
          1.55517161e-01, -6.65209025e-01, -6.38966295e-01, -6.42124901e-01,
         -1.31833288e+00, -4.65574791e-01, -5.08079965e-01, -6.04960848e-01,
         -6.98548214e-01, -8.79748584e-01, -2.80822736e-01,  3.90670208e-01,
          8.20825282e-01,  6.87597577e-01,  5.74236969e-01,  6.42999053e-01,
          4.67874817e-01,  3.69295043e-01,  1.17164979e+00, -1.17219700e-01,
          1.92628532e-02,  1.02208642e+00,  1.11400589e+00,  1.08173216e+00,
          2.78777799e-01,  8.97984945e-01,  6.30263162e-01,  4.03056393e-01,
          1.28285769e+00,  5.56815650e-01,  1.24363617e-02,  1.57680034e+00,
          8.17680425e-01,  1.36661690e+00,  1.39103008e+00,  1.31132985e+00,
          1.30795405e+00,  1.23656804e+00,  1.85142830e+00,  1.92096661e+00,
          1.44434706e+00,  1.42062057e+00,  1.28794967e+00,  1.25326750e+00,
          5.09510171e-01,  9.36448232e-01,  8.69082973e-01,  6.33531886e-01,
         -4.80175403e-02,  3.91770864e-01,  2.68765256e-01, -3.62123561e-01,
          1.03785902e+00,  1.24084612e+00,  2.23649063e+00,  3.55794800e+00,
          3.23351570e+00,  2.65533198e+00,  4.01502094e+00,  3.10557096e+00,
          3.64662479e+00,  3.30232364e+00,  3.22573285e+00,  3.48373162e+00,
          2.43719702e+00,  1.20726713e+00,  2.40509188e+00,  8.47501110e-01,
          1.74208051e-01,  1.86859135e-01,  1.87769405e-01,  2.03444176e-01,
          1.06667720e-01, -5.47662554e-01, -1.52452649e+00, -1.55481992e+00,
         -1.77961467e+00, -1.58209205e+00, -1.96157503e+00, -9.22069664e-01,
         -8.47168128e-01, -8.93896173e-01, -6.25543242e-01, -9.06439923e-01,
         -1.16173388e+00, -1.35630111e+00, -8.24788689e-01, -1.09691655e+00,
         -6.19828949e-01, -7.91256568e-01, -6.84189105e-01, -4.33422934e-01,
         -3.42864809e-01,  7.41991340e-15, -4.26044792e-01]),
  array([ 2.02845413,  1.94136202,  1.50523562, -0.19983354,  0.44700104,
          0.33745622,  2.01515236,  1.91848427,  3.05753225,  2.81497954,
          2.4520692 ,  2.33646709,  2.60672562,  0.91072335,  0.87330486,
          0.75030284,  0.5055678 ,  2.48133117,  2.07925084,  2.7355078 ,
          2.31866019,  2.60820774,  2.75990096,  2.15523092,  2.66666667,
          1.8423077 ,  1.68227229,  0.45972425,  0.48041686,  0.44114349,
          0.19399438,  0.79570146,  1.51324255,  0.15401236,  0.88581704,
          1.86387479,  1.68982029,  0.78688525,  1.06503581, -0.31066832,
          0.60902611, -0.7709718 , -0.63900965, -0.8123032 ,  0.67153905,
          0.6047079 ,  0.87507883,  0.83872623,  0.68456997,  0.91444851,
          1.33735186,  0.42316838,  0.07692308,  0.56156887,  0.3153818 ,
          0.61727339,  0.70808257,  1.47848344,  1.52022683,  1.88996588,
          1.78322087,  2.27500588,  2.17196967,  1.7516582 , -0.09819548,
          0.13000563, -0.16992053,  1.25953136,  1.08128378,  2.42552067,
          2.        ,  1.18539879,  0.73407922,  2.1426204 ,  0.92295821,
          1.58538256,  1.1085106 ,  1.18097946,  1.06707697,  2.01723344,
          2.00329544,  2.09557193,  2.53739713,  1.99578681,  1.84450088,
          1.77363205,  0.71649792,  1.76082911,  1.55519264,  1.73500198,
          0.52997344,  1.33033733,  1.3909102 ,  0.49217479,  0.46460599,
          0.51558005,  0.038831  , -0.41239305,  0.14036543, -0.60529197,
         -0.87800631, -0.15743826, -0.25030134,  0.64564895,  1.04640913,
          0.36831696,  0.50320266,  0.53602696,  1.41807182,  1.5893915 ,
          0.9335412 ,  1.11727157,  1.04143851,  1.09870053,  1.22696883,
          1.19990603,  1.63767945,  1.27272727,  1.60451491,  1.39138786,
          1.35741083, -0.5581202 ,  0.22609635, -0.14447701, -0.00477824,
          0.38067564,  0.24773521,  1.15443664,  1.97417489,  2.33124467,
          2.18817251,  2.11395954,  1.30421035,  1.28801137,  1.20072377,
          1.07323096,  1.20819134,  0.97166562,  0.18448444,  0.23889307,
          0.43813465, -0.11614561,  0.11032175,  0.5955923 , -0.05911976,
          0.7101306 ,  0.69853547,  0.63441897,  0.12693942, -0.48068168,
          0.19914441, -1.02450358, -0.56934801, -0.44079414, -0.1518156 ,
         -1.12840655, -1.19854437,  1.00992732, -0.97172731, -1.16393768,
         -0.97238125, -0.39372844, -0.40930363, -0.117103  , -0.48803791,
          0.36251394,  0.5060769 ,  0.93080864,  0.72690046,  0.50260283,
          2.48282838,  1.28901833,  1.42831273,  1.43575022,  1.34236351,
          0.56466396,  0.67985062,  0.70352647,  0.30892431,  0.40505209,
          0.15815423, -0.01721581,  0.24864765,  0.26688917,  1.21732916,
          1.14182965,  1.96423106,  2.95467766,  3.96059017,  1.94374818,
          1.01732465,  1.52547679,  1.19798944,  0.9656164 ,  1.14857226,
          0.85914075,  1.34804074,  2.8491729 ,  2.37478647,  2.5883142 ,
          1.99569113,  0.68797309,  2.1471705 ,  1.9969759 ,  1.91757999,
          2.27816136,  1.21992755,  2.20553755,  1.90515869,  1.43858107,
          0.58624751,  1.39853292,  1.20347991,  1.07634471,  1.15739269,
          1.30235034,  1.74600188,  1.33535054,  1.37674599,  1.64595907,
          1.48842733,  3.1643011 ,  3.30835059,  2.94913944,  3.01303245,
          2.25889043,  1.74665872,  0.66710112, -0.00564342, -0.35285464,
          0.03398793, -0.0335599 ,  1.36649846,  1.35851234,  2.18752929]),
  array([ 0.13052797,  0.19802951,  1.53444193,  0.86928735,  0.76249285,
          0.76133777,  1.12102613, -0.02294761,  0.47124508,  2.33816095,
         -0.18421252,  0.16410115,  0.13665914,  1.10419199,  0.26255698,
         -0.62366951,  0.86791215,  0.66852869,  0.63329409, -0.57954553,
         -0.39155973, -0.64584061, -0.07997868,  0.02144718, -0.29661408,
         -0.24722569, -0.43055225,  0.10479193,  0.09302696, -0.92258522,
         -0.56940673, -0.44194174, -0.0148904 , -0.08043734,  0.11008303,
          0.80529983,  0.23821377,  1.05008023,  0.97058977, -0.09545749,
          0.01318239,  0.0445878 ,  0.17324096, -0.50281288, -1.0147187 ,
         -1.33426052, -0.38760987,  0.16464252,  0.10546253, -0.75495388,
         -0.80011899, -0.4145781 , -0.37162148, -0.62745098, -0.88344706,
         -1.39296689,  0.18935832,  0.18356269, -0.54775746, -0.60902611,
          0.75464314,  0.2231912 ,  0.00912909, -0.05215731,  0.20908137,
          0.24641167,  1.95003374,  1.30009965,  1.64553008,  1.54713187,
          1.41486693,  0.8780426 ,  0.56965192,  1.17613847,  1.81676939,
          1.98328365,  0.95742711,  0.78213649,  1.19539028, -0.44262295,
          0.40847627, -1.26882593, -1.2001394 , -0.44915581, -0.91634307,
         -0.55733915,  0.03513401,  0.26015714,  0.65884394,  0.36378501,
         -0.93645884, -0.40334824,  3.06791913,  3.35696059,  2.73031897,
          2.134491  ,  2.10943695,  2.47029502,  2.0580189 ,  2.37256686,
          2.17160635,  2.15468818,  2.17134106,  2.23300354,  2.87550186,
          2.95809617,  3.00520382,  1.95083454,  1.48793201,  0.55212572,
          0.63907604, -0.35192853,  0.05414123,  0.21942963, -0.39715658,
          0.21707238,  0.74857871,  0.43921492,  0.12789908, -0.46032327,
          0.09675846,  0.08457092,  2.40092898,  1.97565832,  1.59106245,
          1.41596173,  0.75545903,  1.52467421,  1.37636899,  0.76722146,
          0.97049496,  2.05453405,  1.77954493,  0.5471923 ,  1.99365279,
          1.14906888,  1.26410749,  0.05678601,  0.30171917,  1.4096425 ,
          1.12311467,  0.92821074,  0.24203801,  1.21660825,  1.90349354,
          2.95535116,  1.97410443,  1.88283702,  1.74273908,  0.32964155,
          1.39915396,  2.38808926,  1.64296408,  1.64944494,  2.09363668,
          2.14073207,  2.19702815,  3.01490641,  2.87670601,  4.16637117,
          3.52303666,  3.21671253,  3.18902886,  4.40195331,  3.91067955,
          2.94672936,  2.88318938,  2.61294189,  2.70120535,  2.6957804 ,
          1.90847892,  1.41132577,  0.46208257,  0.42857782,  1.00836597,
          0.43776424,  1.32862256,  0.42884637,  0.50853555,  0.30484213,

In [52]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(235+263+331)
m=829

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(9):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
print(S1,S2,S3,'BERT')

results_df

235
263
331
=
829
0.1158021712907117 0.39324487334137515 0.29191797346200243 BERT

,subject,WER,BLEU,METEOR,BERT
0,1,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,1,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,2,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,2,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
5,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
6,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
7,3,"[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
8,3,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [54]:
to_file = pd.DataFrame({'subject':[1,2,3], 'significantly_decoded': [S1,S2,S3]})
to_file.to_csv('perceived_movie_percentages.csv', index=False)

to_file

   subject  significantly_decoded
0        1               0.115802
1        2               0.393245
2        3               0.291918

In [27]:
results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

{'words': array(['she', 'said', 'she', ..., 'that', 'she', 'needs'],
       shape=(1589,), dtype='<U13'),
 'times': array([ 10.2,  10.6,  11. , ..., 591. , 591.4, 591.8], shape=(1589,))}