In [6]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_movie/wr_speech/presto.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['window_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('presto', 'WER'): array([ 0.78041856,  0.71696973,  1.14015658,  0.97382558,  0.73502576,
        0.53220014,  0.65505166,  1.35928737,  1.62896459,  1.26640715,
        0.78472857,  0.57945633, -0.1839418 , -0.26280061,  0.37965046,
        0.23606113,  0.08809253, -0.05290915,  0.56976017,  0.13099088,
        0.2305734 ,  0.3309984 , -0.39310793, -0.3762982 , -0.37410636,
       -0.34657144, -0.30032905, -0.92213889, -0.15972417, -0.16793485,
        0.34742403, -0.06106147, -0.42583648,  0.42768588,  0.35706231,
       -0.41555505, -0.50866316, -0.23735633, -0.24426598, -0.20469574,
       -0.5479715 , -1.45984032, -1.67808988, -1.44820369, -0.9822398 ,
       -0.3148335 , -0.92591938, -0.2078275 , -0.58171004,  0.24722569,
        1.02070286,  1.64316767,  0.99559499,  0.6829508 ,  1.05487982,
        0.59735964,  1.47782133,  2.36904369,  2.42258297,  2.34585751,
        2.3953223 ,  3.49176286,  3.29725923,  2.83054471,  2.41699176,
        3.23757089,  3.12271577,  2.95929255,  1.88128362,  1.58068927,
        1.0916935 ,  1.59841558,  1.21658836,  1.94008267,  0.88650984,
        0.46247666,  2.54107987,  1.12886504,  0.91901209,  1.14034289,
        0.77718201,  0.02612055,  0.09128709,  0.20938323, -0.33837701,
       -1.00778244, -1.46403818, -1.45260037, -0.5752608 , -0.13643695,
       -0.64198611, -0.64438608, -0.47237749, -0.457289  , -0.52538656,
       -0.63208163, -1.38261993, -1.71238084, -2.00351122, -1.75773434,
       -2.02460285, -2.23258908, -1.69467481, -1.71524976, -2.02479187,
       -1.9579028 , -1.83441527, -1.70546862, -1.45842339, -1.43265594,
       -1.32504382, -1.29612391, -1.43815391, -1.49081812, -1.44001422,
       -0.72953983, -0.94669421, -0.7459861 , -0.60663431, -0.66429735,
       -0.77737847, -0.81835213, -0.69148058, -0.35942538, -0.18387041,
        0.13519768,  0.00731292,  0.82914025,  0.84894921,  1.41836778,
        1.89796813,  2.7836558 ,  2.45480297,  2.59994973,  2.47444593,
        1.66771078,  2.05090284,  1.71194376,  2.44755254,  3.32608736,
        3.48257755,  3.73704204,  4.0529878 ,  3.67625809,  3.85412807,
        3.14138745,  2.34957039,  2.11985281,  2.82706215,  1.48053541,
        0.61379491,  0.20412415, -0.18932754,  0.83049899, -0.01812664,
       -0.24077171, -0.33445616, -0.56851378, -0.5513228 , -1.63943946,
       -1.43505485, -1.40892676, -0.07850316, -1.21308122, -1.61102263,
       -0.92376043, -1.21535992, -1.55026362,  0.57097551,  0.68103012,
        0.83956438,  0.53961175,  0.23330441,  0.3357573 ,  0.24505026,
        0.33455748,  0.33299029,  1.27399917,  0.93179927,  1.83855392,
        1.59255514,  1.29267372,  1.40584544,  0.75016838,  0.88247478,
        0.91342339,  0.11720203,  0.76575741,  0.32995601,  0.8       ,
        0.46563307,  1.20650193,  1.34964535,  1.7247953 ,  1.41286138,
        1.75111856,  1.94965055,  0.40890842, -0.15599742,  0.45228826,
        0.86928735,  2.12387052,  2.23712172,  2.94764578,  2.8583527 ,
        2.16880748,  2.24383663,  2.40849497,  2.04378401,  2.54417949,
        1.66971745,  1.82036411,  2.42097838,  2.31779189,  1.69870914,
        1.91057002,  1.66769737,  2.71167932,  1.90029981,  2.53608731,
        2.17007633,  1.04093521,  0.06371401,  0.81794429,  0.70300067,
        0.90631821, -0.26026167,  1.7761202 ,  0.39077778, -0.10050378,
       -0.27836557, -0.33837701, -0.89970724, -1.20528331,  0.56197674]), ('presto', 'BLEU'): array([ 1.70883911e+00,  1.58782733e+00,  1.47235740e+00,  1.59801849e+00,
        1.14064250e+00,  1.07063451e+00,  1.36470348e+00,  2.13964032e+00,
        2.16936707e+00,  2.14218267e+00,  1.38510660e+00,  1.34341854e+00,
        1.83266414e+00,  1.06518149e+00,  9.64593351e-01,  1.16612889e+00,
        5.99629357e-01,  8.52394055e-01,  8.44150508e-01,  6.39076972e-01,
        1.39061800e+00,  1.69011748e+00,  9.73448195e-01,  5.45183339e-01,
        7.44205311e-01,  7.04623610e-01, -2.65684466e-01, -3.16506392e-01,
        5.63496671e-01,  6.12632101e-01,  1.61596598e-01, -2.31247071e-01,
       -2.57788035e-02,  4.44695162e-01,  6.70495461e-01,  1.40964250e+00,
        1.93554422e+00,  1.80250920e+00,  1.26867500e+00,  2.06249388e+00,
        2.22725766e+00,  1.98845366e+00,  1.88130581e+00,  1.92679071e+00,
        1.28214505e+00,  1.39639155e+00,  1.65083109e+00,  1.65232569e+00,
        8.08234573e-01,  7.36563670e-01,  5.97526624e-01,  1.74940623e+00,
        1.60001449e+00,  1.51022742e+00,  1.46856889e+00,  1.42936067e+00,
        2.05746602e+00,  2.48598380e+00,  3.31691193e+00,  3.24211456e+00,
        2.36458910e+00,  2.76585893e+00,  3.32745334e+00,  2.75643481e+00,
        2.40496491e+00,  2.42453233e+00,  2.82562035e+00,  2.58469142e+00,
        2.45200159e+00,  2.31085931e+00,  2.47959030e+00,  1.48451297e+00,
        1.23792522e+00,  1.46498412e+00,  1.42867575e+00,  9.44513084e-01,
        8.45900500e-01,  8.66347591e-01, -4.00822530e-02,  3.36256318e-01,
        5.55758251e-02, -4.15748246e-01,  2.52057147e-03, -1.21348143e-02,
       -2.22702019e-02, -5.97703249e-01, -5.52305876e-01, -3.58073800e-01,
       -1.16248394e+00, -1.66837378e+00, -1.67398823e+00, -1.70722197e+00,
       -1.78007527e+00, -1.30933730e+00, -9.57876777e-01, -9.81497794e-01,
       -1.51577092e+00, -1.50079750e+00, -1.56397348e+00, -1.26671620e+00,
       -7.94690728e-01, -2.98784054e-01, -7.16660285e-01, -6.58462043e-01,
        1.46371384e-01,  1.35045689e-01,  2.98779328e-01,  7.90295055e-02,
        6.79285700e-01,  8.38115669e-01, -6.11440699e-02, -4.51925778e-01,
       -4.51098209e-01, -9.74099847e-01, -6.97727584e-01, -9.64094447e-02,
       -1.48397233e-01, -1.11030229e-01, -3.00551115e-01,  4.86021403e-01,
       -1.49829666e-02, -3.67828295e-01,  2.39525252e-02,  2.70900629e-02,
       -1.05000137e+00, -4.31606307e-01,  7.93636734e-02,  8.75560276e-01,
        6.65889152e-01,  7.28782888e-01,  1.09187033e+00,  1.56237017e+00,
        1.47304896e+00,  1.20127477e+00,  1.09854559e+00,  5.25097551e-01,
        1.35333307e+00,  1.41003150e+00,  1.71208449e+00,  2.18487430e+00,
        2.77693783e+00,  2.14232454e+00,  2.43908528e+00,  2.77205540e+00,
        2.64254156e+00,  1.85532667e+00,  2.23079121e+00,  1.18735422e+00,
        7.48824498e-01,  5.44624893e-01, -3.98988513e-01, -8.35130980e-01,
       -7.48420532e-01, -1.10347207e+00, -1.05441082e+00, -9.77065372e-01,
       -1.15521004e+00, -1.17814032e+00, -1.61013157e+00, -1.78621238e+00,
       -2.23269938e+00, -1.77910876e+00, -1.39944062e+00, -9.45853877e-01,
       -1.60440624e+00, -1.92800899e+00, -1.13969668e+00, -1.12173983e+00,
       -1.30582801e+00, -8.54829732e-01, -7.27047705e-01,  2.28371099e-01,
        1.70670312e-01,  2.76397920e-01,  2.92501578e-01,  3.09586466e-01,
        1.78365561e-01,  1.16699750e+00,  9.10895605e-01,  8.29872226e-01,
        8.01127094e-01,  5.32706521e-01,  3.55166401e-02,  4.82496546e-01,
        1.59473643e-01,  5.06853245e-01, -1.87350034e-02,  7.28350450e-01,
        8.73182196e-01,  9.32702028e-01,  9.59819903e-01,  6.58119959e-01,
        7.16668698e-01,  7.39985370e-01,  1.00423500e+00,  8.89890988e-01,
       -5.35821085e-02,  9.13645802e-01,  1.12745922e+00,  1.37496048e+00,
        1.77184138e+00,  2.47594129e+00,  2.45062079e+00,  2.93702194e+00,
        2.41952649e+00,  2.08608232e+00,  2.58295100e+00,  2.92306066e+00,
        1.90776994e+00,  2.63975566e+00,  2.69003854e+00,  3.07668435e+00,
        3.46834079e+00,  3.44143628e+00,  3.66471339e+00,  3.56047662e+00,
        3.15302698e+00,  4.23669006e+00,  3.79560260e+00,  3.52709065e+00,
        2.49826441e+00,  2.06888394e+00,  1.72189284e+00,  7.30929199e-01,
        8.16011581e-01,  7.96382033e-01,  7.68768443e-01,  8.49567597e-01,
        4.18848820e-01, -5.55154593e-01, -4.44430417e-01, -4.48681007e-01,
       -4.99827913e-01,  1.10414904e-01, -1.77102381e-01]), ('presto', 'METEOR'): array([ 1.47970897,  1.42403506,  1.28862308,  1.26881391,  1.21297811,
        0.45306419,  0.78416239,  1.44077653,  1.18927748,  1.098439  ,
        0.42352025,  0.82604797,  1.36786513,  0.64496051,  0.76008139,
        0.8508711 ,  0.40656404,  0.49100934,  0.51929625,  0.40835794,
        0.99893835,  1.19726638,  0.4669604 ,  0.28236812,  0.45427496,
        0.70388801, -0.13400884, -0.1905353 ,  0.54379136,  0.58629666,
        0.57905424,  0.23078178,  0.43227381,  0.84932991,  1.13586233,
        2.73786392,  2.24465144,  2.10164399,  1.73799954,  2.71334671,
        2.96693332,  3.13365579,  3.17797085,  2.747196  ,  2.16440677,
        2.31269972,  2.43592119,  2.47508018,  1.73450368,  1.43238598,
        1.2552959 ,  2.24025319,  2.007602  ,  1.98891832,  1.46038824,
        2.45368518,  2.0020433 ,  3.7314351 ,  2.86345766,  2.7282008 ,
        2.03352379,  2.18459152,  2.67497623,  2.48147312,  2.26979886,
        2.25703438,  3.15226372,  2.72491096,  2.55614221,  2.40564735,
        2.52929595,  1.6340167 ,  1.10818139,  1.66688252,  1.75851529,
        1.21542485,  0.96470305,  1.04465284,  0.23522956,  0.4815125 ,
        0.20877169, -0.18543768,  0.45070382, -0.02416822, -0.03165141,
       -0.55555116, -0.48726337,  0.2690339 , -0.60440511, -1.01926193,
       -1.08110559, -1.1670734 , -1.25359231, -0.5680517 , -0.26585105,
       -0.26658445, -0.61118892,  0.18920731,  0.12387022,  0.49034568,
        0.99544758,  1.29406741,  0.53278026,  0.56664725,  1.39080554,
        0.96129157,  1.01784353,  0.47548542,  0.33850854,  0.46817374,
        0.18534433, -0.0939821 , -0.0991231 , -1.06145286, -0.81373333,
       -0.40266839, -0.01751641, -0.28496282, -0.44926203,  1.31635073,
       -0.222725  , -0.53430201, -0.32135253, -0.31898419, -1.14381765,
       -0.58823961, -0.24917429,  0.71803674,  0.57310835,  0.68576037,
        0.09882861,  0.51363705,  0.12018321,  0.41882182,  0.30141374,
        0.02117827,  0.62432757,  0.75548182,  1.02340364,  1.43379947,
        1.94698356,  1.42427623,  1.55392347,  2.59318071,  2.13526717,
        1.3102801 ,  1.61363335,  0.86247016,  0.47193414,  0.5312396 ,
       -0.26538851, -0.24578177,  0.49017418,  0.22816582,  0.13863363,
        0.27710779, -0.38731571, -0.12883452, -0.49049499, -1.04033016,
       -1.41442534, -1.04967976, -0.77030341, -0.35711246, -0.09922862,
       -0.42919069,  0.65501835,  0.70468749,  0.39831742,  0.74888046,
        0.93171104,  1.19428986,  0.79674705,  0.7743898 ,  0.5266648 ,
        0.89507753,  0.59219697,  1.26319282,  0.77391729,  0.72556792,
        0.72556334,  0.61054648,  0.19743376,  0.54668407, -0.12625347,
        0.1598557 , -0.21930265,  0.40368018,  0.53493046,  0.63777299,
        0.6821413 ,  0.21541186,  0.26913588,  0.35299072,  0.86818473,
        1.18197114, -0.0392887 ,  1.15240176,  1.35393207,  1.65433191,
        2.21241984,  2.79659401,  2.66426467,  3.09959481,  2.7362109 ,
        2.57233553,  2.68566404,  4.09596351,  3.82429883,  3.34951994,
        4.48797407,  4.83971698,  4.12018058,  3.79046244,  3.6622774 ,
        3.66839321,  3.46190027,  4.07891886,  3.69906826,  3.53893503,
        2.94716831,  2.12985694,  1.95628166,  1.13515182,  1.29695984,
        1.21760918,  1.23828311,  1.36368645,  0.71652657, -0.02213555,
       -0.33949848, -0.35426233, -0.39911703,  0.02085636, -0.19888103]), ('presto', 'BERT'): array([ 2.3987195 ,  2.8271694 ,  3.1526628 ,  1.9892673 ,  2.2928357 ,
        1.3530078 ,  1.4564325 ,  1.6344429 ,  1.3145932 ,  1.8377267 ,
        1.809815  ,  1.4771622 ,  0.95371825,  1.2654935 ,  1.4006705 ,
        0.9382951 ,  1.2771734 ,  0.7969825 ,  1.4202387 ,  1.6661135 ,
        1.6301605 ,  0.61392736, -0.06741789,  0.22160205,  1.4105368 ,
        2.053063  ,  1.4153568 ,  1.5535157 ,  2.1893356 ,  2.1956494 ,
        2.5721767 ,  2.9901018 ,  2.5212724 ,  2.5490122 ,  3.16129   ,
        1.8852661 ,  2.5494547 ,  2.1210115 ,  2.5919352 ,  2.9812238 ,
        3.124411  ,  3.5916955 ,  3.0263345 ,  3.7102566 ,  2.8529603 ,
        3.1660032 ,  2.6078851 ,  2.3025734 ,  2.5349433 ,  2.3978536 ,
        1.5766393 ,  2.73408   ,  3.0230231 ,  3.393348  ,  2.9621065 ,
        1.9220159 ,  1.6659272 ,  1.6350895 ,  1.4109592 ,  1.8291245 ,
        0.16691175,  0.5610196 ,  0.7554997 ,  0.28074816,  0.43374336,
        0.18594363, -1.670931  , -0.7224654 , -0.6435002 , -0.8342411 ,
       -0.86703336, -0.6669119 , -1.8940792 , -0.68644905, -0.9046505 ,
       -1.7128028 , -0.5652592 , -1.3192445 , -1.2108992 , -1.5911204 ,
       -1.2920192 , -1.4903867 , -1.4456091 , -1.9763012 , -1.574436  ,
       -1.0181369 , -1.133234  , -1.6586899 , -1.342982  , -0.32798153,
       -0.5126225 , -1.2086775 , -0.47180876, -0.4237054 , -0.7319679 ,
        0.4443852 ,  0.552473  ,  0.28012118,  0.27318075, -0.17755796,
        0.44850022,  0.4313173 , -0.03350613,  0.15991329,  0.4393309 ,
        0.48628214, -0.11169495,  0.29172847,  1.0661725 ,  1.0645195 ,
        0.72518915,  1.0618213 ,  0.44568056,  1.1882254 ,  0.6616942 ,
        0.83186847,  0.6395719 ,  1.3088522 ,  0.71022016,  0.4747725 ,
        0.41606128,  0.8896371 ,  0.5999831 , -0.24653545,  0.14966643,
        0.09427712,  1.7183336 ,  0.20363954,  0.07168118,  0.17074127,
        0.40239966, -0.21613014, -0.2837676 ,  0.08575975,  0.6295711 ,
        0.78599054,  1.279005  ,  1.2096635 ,  0.8560049 ,  1.4868499 ,
        0.8556008 ,  0.683402  ,  0.49169478,  1.4213809 ,  0.4025281 ,
        0.4909749 , -0.6939754 ,  0.72695106, -0.04382489,  0.29617667,
        0.9769487 ,  0.3121649 , -0.22901677,  0.60659784,  0.49651167,
        0.16624147, -0.39187554, -0.6736244 , -0.14587928, -0.1924318 ,
        0.315092  , -0.22496329,  0.7565966 , -0.01294212,  0.8191275 ,
       -0.28313276,  0.5065763 ,  0.4168917 , -0.18807043,  0.34221414,
       -0.57674253, -0.40117836, -0.11966707, -0.73733413, -0.65845716,
       -0.37321606, -0.18856266,  0.03515166, -0.66624415,  0.07226934,
       -0.15622953,  0.8632417 ,  0.1865071 ,  0.25058773, -0.36722037,
        0.13802569, -0.4653409 ,  0.39279425,  0.6381676 ,  1.0952218 ,
        1.6426136 ,  1.4489547 ,  1.1074461 ,  0.9631928 ,  0.966737  ,
        2.1205978 ,  2.3899436 ,  2.5092978 ,  1.6898901 ,  3.3584943 ,
        3.1258001 ,  3.9648755 ,  3.051852  ,  3.347342  ,  3.674928  ,
        3.6578138 ,  3.089253  ,  2.7413223 ,  3.1422977 ,  4.0124407 ,
        3.0203516 ,  4.176069  ,  3.3195612 ,  3.4161034 ,  3.047087  ,
        2.8121548 ,  3.0465708 ,  3.1667042 ,  1.5105861 ,  2.748263  ,
        2.308647  ,  2.0456607 ,  1.1254685 ,  1.4956199 ,  0.9650859 ,
        1.1011803 ,  1.5365088 ,  0.50434726, -0.17835693, -0.70533377,
       -0.0124464 ,  0.26439473,  0.03795414,  0.22705981,  0.48681718],
      dtype=float32)}

In [7]:
window_zscores = {'subject': [], 'wrmodel': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for subject in [1,2,3]:
    for task in ['presto','partlycloudy','laluna']:
        for model in ['speech', 'auditory']:
            scores = np.load(f'scores/S{subject}/perceived_movie/wr_{model}/{task}.npz', allow_pickle=True)['window_zscores'].item()
            # print(scores['window_zscores'].item())
            window_zscores['subject'].append(subject)
            window_zscores['WER'].append(scores[(task, 'WER')])
            window_zscores['BLEU'].append(scores[(task, 'BLEU')])
            window_zscores['METEOR'].append(scores[(task, 'METEOR')])
            window_zscores['BERT'].append(scores[(task, 'BERT')])
            window_zscores['wrmodel'].append(model)

window_zscores

{'subject': [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
 'wrmodel': ['speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory',
  'speech',
  'auditory'],
 'WER': [array([ 0.78041856,  0.71696973,  1.14015658,  0.97382558,  0.73502576,
          0.53220014,  0.65505166,  1.35928737,  1.62896459,  1.26640715,
          0.78472857,  0.57945633, -0.1839418 , -0.26280061,  0.37965046,
          0.23606113,  0.08809253, -0.05290915,  0.56976017,  0.13099088,
          0.2305734 ,  0.3309984 , -0.39310793, -0.3762982 , -0.37410636,
         -0.34657144, -0.30032905, -0.92213889, -0.15972417, -0.16793485,
          0.34742403, -0.06106147, -0.42583648,  0.42768588,  0.35706231,
         -0.41555505, -0.50866316, -0.23735633, -0.24426598, -0.20469574,
         -0.5479715 , -1.45984032, -1.67808988, -1.44820369, -0.9822398 ,
         -0.3148335 , -0.92591938, -0.2078275 , -0.58171004,  0.24722569,
          1.02070286,  1.64316767,  0.99559499,  0.6829508 ,  1.05487982,
          0.59735964,  1.47782133,  2.36904369,  2.42258297,  2.34585751,
          2.3953223 ,  3.49176286,  3.29725923,  2.83054471,  2.41699176,
          3.23757089,  3.12271577,  2.95929255,  1.88128362,  1.58068927,
          1.0916935 ,  1.59841558,  1.21658836,  1.94008267,  0.88650984,
          0.46247666,  2.54107987,  1.12886504,  0.91901209,  1.14034289,
          0.77718201,  0.02612055,  0.09128709,  0.20938323, -0.33837701,
         -1.00778244, -1.46403818, -1.45260037, -0.5752608 , -0.13643695,
         -0.64198611, -0.64438608, -0.47237749, -0.457289  , -0.52538656,
         -0.63208163, -1.38261993, -1.71238084, -2.00351122, -1.75773434,
         -2.02460285, -2.23258908, -1.69467481, -1.71524976, -2.02479187,
         -1.9579028 , -1.83441527, -1.70546862, -1.45842339, -1.43265594,
         -1.32504382, -1.29612391, -1.43815391, -1.49081812, -1.44001422,
         -0.72953983, -0.94669421, -0.7459861 , -0.60663431, -0.66429735,
         -0.77737847, -0.81835213, -0.69148058, -0.35942538, -0.18387041,
          0.13519768,  0.00731292,  0.82914025,  0.84894921,  1.41836778,
          1.89796813,  2.7836558 ,  2.45480297,  2.59994973,  2.47444593,
          1.66771078,  2.05090284,  1.71194376,  2.44755254,  3.32608736,
          3.48257755,  3.73704204,  4.0529878 ,  3.67625809,  3.85412807,
          3.14138745,  2.34957039,  2.11985281,  2.82706215,  1.48053541,
          0.61379491,  0.20412415, -0.18932754,  0.83049899, -0.01812664,
         -0.24077171, -0.33445616, -0.56851378, -0.5513228 , -1.63943946,
         -1.43505485, -1.40892676, -0.07850316, -1.21308122, -1.61102263,
         -0.92376043, -1.21535992, -1.55026362,  0.57097551,  0.68103012,
          0.83956438,  0.53961175,  0.23330441,  0.3357573 ,  0.24505026,
          0.33455748,  0.33299029,  1.27399917,  0.93179927,  1.83855392,
          1.59255514,  1.29267372,  1.40584544,  0.75016838,  0.88247478,
          0.91342339,  0.11720203,  0.76575741,  0.32995601,  0.8       ,
          0.46563307,  1.20650193,  1.34964535,  1.7247953 ,  1.41286138,
          1.75111856,  1.94965055,  0.40890842, -0.15599742,  0.45228826,
          0.86928735,  2.12387052,  2.23712172,  2.94764578,  2.8583527 ,
          2.16880748,  2.24383663,  2.40849497,  2.04378401,  2.54417949,
          1.66971745,  1.82036411,  2.42097838,  2.31779189,  1.69870914,
          1.91057002,  1.66769737,  2.71167932,  1.90029981,  2.53608731,
          2.17007633,  1.04093521,  0.06371401,  0.81794429,  0.70300067,
          0.90631821, -0.26026167,  1.7761202 ,  0.39077778, -0.10050378,
         -0.27836557, -0.33837701, -0.89970724, -1.20528331,  0.56197674]),
  array([ 0.68898103,  0.65783685,  0.08612933,  0.20152289, -0.15751231,
          0.43519414,  0.47643873,  0.18387041,  0.43752659,  0.19551363,
          0.72919727, -0.46517657, -1.30358096, -1.4212555 , -1.58665216,
         -0.82796468, -1.06165176,  0.22116293,  0.16167732, -1.06492957,
         -0.85221962, -0.69675063, -0.80488612, -0.80164419, -0.93706291,
         -0.88223084, -0.89791429, -0.65352125, -0.77392725, -0.7568091 ,
         -0.21685075, -0.4214867 , -0.03943615,  0.17729688,  0.5364532 ,
          0.19214284, -0.18002404,  0.62689067,  0.62241997,  1.31465962,
          0.68748728,  0.20534031, -0.07202824, -0.12672927, -1.05849937,
         -0.88178405, -0.24561789, -0.8011752 , -0.99526407, -1.01252683,
         -0.84443443, -0.62401929,  0.39823399,  0.34802263,  0.79498957,
          1.11434752,  1.24700354,  1.31741297,  2.09990444,  2.90908388,
          3.08098249,  2.91442951,  3.87343024,  4.24409946,  3.73354819,
          3.74251426,  3.83111487,  3.61911996,  2.0155298 ,  2.38015429,
          2.92133306,  3.16590775,  3.25383729,  3.3242734 ,  1.11519645,
          1.3214406 , -0.08510638,  0.22506683,  0.16802629,  0.86772183,
          0.83632448, -0.19906828, -0.12924   ,  0.20421099, -0.49050514,
         -0.73981023, -0.84624048,  0.3520894 , -0.55753223, -0.31726463,
         -0.63354989, -0.91286284, -0.99881189, -1.13359727, -1.30390068,
         -1.3241594 , -1.0390041 , -1.3027689 , -1.53536403, -2.52560346,
         -2.48281767, -0.94361242, -1.10833761, -1.13032352, -1.36766621,
         -2.02575248, -2.05785882, -1.9758707 , -1.81272673, -1.86760995,
         -1.78628919, -1.58150765, -1.66661405, -1.61155897, -1.34176322,
         -1.3307227 , -1.68165932, -1.57786412, -1.42142426, -0.70986468,
         -1.51148307, -1.58926726, -1.64435836, -2.20823075, -1.21466334,
         -0.81106682, -0.86046627, -0.90144107,  1.51876937,  1.23540596,
          1.92936911,  1.9219753 ,  1.88541782,  1.93199643,  2.55482035,
          2.35043904,  1.99226039,  2.30481998,  2.30241729,  3.23270501,
          2.71428571,  2.93358563,  2.65495395,  2.84985488,  2.84832478,
          3.3714809 ,  2.85660536,  2.01060948,  1.89454029,  2.23654277,
          1.17556903,  0.6815021 ,  0.79498957, -0.06208373,  0.07495057,
          0.31546998,  0.42828957,  0.47718547,  0.71012574,  0.35659143,
          0.22506683,  0.05395998, -0.85839065, -0.74038427, -0.80822386,
         -0.89112574, -0.86372742, -1.09152148, -1.85025549, -1.02595932,
         -0.71399788, -1.05464142, -0.43432411, -0.44056292, -0.51825299,
         -0.49478609, -0.42922347,  0.3577819 ,  0.84987576,  0.91863847,
          1.62703537,  0.74867726,  2.47582903,  1.74006378,  1.93422615,
          2.82376458,  3.56768911,  3.27953957,  2.40221527,  1.3574885 ,
          0.96664431,  1.5028978 ,  0.8868336 ,  1.33277048,  1.72175517,
          1.95574696,  1.41784308,  1.58224097,  1.11417203,  0.58324421,
          0.6101441 ,  0.6820705 ,  2.66789188,  1.84618093,  1.74126763,
          2.21292696,  1.19051632,  0.16796775,  0.66631217,  1.51310069,
          0.7690096 ,  0.82206844,  1.49596995,  1.95215088,  2.18122284,
          1.5459826 ,  2.10317543,  1.5238561 ,  1.5538551 ,  1.83001003,
          1.4946376 ,  1.11016894,  0.25558323,  0.45291423,  0.4544387 ,
          0.52368224,  0.97068377,  0.29621739,  0.3755467 ,  0.21072488,
          0.25090599,  1.26144284,  0.90802928,  1.67618205,  1.4823737 ]),
  array([-7.63721044e-01,  1.09239069e-01,  2.34708655e-01,  2.19082729e+00,
          2.87684510e+00,  2.15503060e+00,  2.77561081e+00,  1.72409228e+00,
          1.96296145e+00,  3.55142403e-01,  4.26308920e+00,  3.22954781e+00,
          3.41351808e+00,  4.07240422e+00,  4.30000000e+00,  4.33568155e+00,
          3.35907802e+00,  3.38525547e+00,  3.30045073e+00,  2.95530987e+00,
          3.26586320e+00,  3.34783596e+00,  3.07149564e+00,  3.48742916e+00,
          3.34972010e+00,  2.86798125e+00,  2.98110272e+00,  2.11433690e+00,
          2.89378038e+00,  3.33673440e+00,  2.86400083e+00,  2.08893654e+00,
          1.73805273e+00,  2.01007563e+00,  1.49839937e+00,  1.20237339e+00,
         -3.62695467e-01,  3.10323205e-01,  8.12031681e-01,  6.29310996e-01,
         -1.46253132e-01,  6.56157332e-01,  6.82280858e-01,  1.05021006e-01,
          1.03003932e+00,  6.84316473e-01,  1.61389098e+00,  1.43657973e+00,
          5.71766767e-01,  6.91081347e-01,  5.58226604e-01,  7.70256547e-02,
          1.35568795e-01, -1.46401351e-01, -2.58916609e-01,  1.07594904e+00,
          1.59829898e+00,  5.36828127e-02,  2.26942482e+00,  2.83556680e+00,
          1.50095520e+00,  3.64793306e+00,  3.77172919e+00,  1.74884106e+00,
         -3.02198943e-02,  2.80197192e-01,  1.16172316e+00,  1.71013299e+00,
          1.42821057e+00,  5.20662627e-01,  3.95056153e-01,  5.77231838e-01,
          9.37128857e-01, -2.23567987e-01,  3.10286355e-01,  4.35194140e-01,
         -5.25217927e-01, -7.23358464e-01, -3.09340980e-01, -1.08071948e+00,
         -5.40542389e-01, -6.78710519e-01, -7.21594342e-01, -8.55288696e-01,
         -6.57506206e-01, -4.67731917e-01, -1.01463616e+00, -4.04624904e-01,
         -1.01282954e+00,  1.81101183e-02, -3.82220146e-01, -6.04858379e-01,
         -6.26861397e-01, -1.37657127e+00, -1.25915467e+00, -1.56015698e+00,
         -1.30759679e+00, -1.14432024e+00, -5.09950463e-01,  6.38807388e-01,
          5.25547288e-01,  4.76163456e-01,  5.72077554e-01,  1.53807811e+00,
          1.62545812e+00,  1.61942726e+00,  1.58849165e+00,  4.36216349e-01,
          7.93308624e-01,  1.84676103e+00,  1.67845125e+00,  1.64112181e+00,
          9.53895421e-01,  1.07010135e+00, -4.80000726e-01, -8.09638345e-01,
         -1.39796521e+00,  3.74182369e-01,  3.53774569e-02, -8.70370370e-01,
         -5.27604835e-01, -4.18041016e-01, -7.72692841e-01, -9.01141866e-01,
         -2.50905986e-01, -3.04212076e-01, -1.12615643e+00, -1.16962477e+00,
         -1.44001422e+00, -1.17573532e+00, -1.35909852e+00, -2.86628894e-01,
         -1.66202199e+00, -1.74649321e+00, -1.65172374e-01, -1.01534617e-01,
         -1.61194392e-01, -1.21114816e+00, -1.07581967e+00, -7.72539396e-01,
         -1.10432147e+00, -1.18539879e+00, -1.59248871e+00, -9.77355555e-01,
         -4.31313330e-01, -4.00211840e-01, -1.98957700e-01, -1.42508569e-01,
          6.93033952e-01,  1.30658295e+00,  6.38648377e-01, -4.90123094e-02,
          5.73362099e-01,  4.59315212e-02,  2.53855042e+00,  1.10648535e+00,
          6.66312173e-01, -4.20619625e-01,  6.04722807e-01, -1.44174910e-01,
          7.95647961e-01,  2.07565308e+00,  1.48704479e-01,  7.26716836e-01,
          1.72818163e-01, -2.99788313e-01, -3.59039315e-01,  1.15746857e+00,
          2.58683275e-01,  5.93174589e-02,  3.12012887e-01,  3.15761009e-01,
          6.16249519e-01,  6.60915376e-01,  3.87609867e-01, -2.05136491e-01,
          4.11266505e-16, -1.62690553e-01,  7.75666986e-01,  5.92045153e-01,
          6.41767383e-01, -2.02229744e-01,  6.56797626e-02,  1.49605727e-01,
          3.82045791e-01,  3.62338342e-01,  1.18141479e+00,  1.13187611e+00,
          1.81326090e+00, -1.18587303e-01, -8.32805172e-01,  1.12515912e-02,
         -8.16842990e-01,  5.83498513e-01,  1.87830500e-01,  2.11539260e-01,
          2.20994990e-01,  2.81312443e-01,  5.80429492e-01,  9.46802696e-01,
          1.23400348e+00,  3.24274169e-01,  1.13985788e+00,  9.53462589e-01,
          8.80696034e-01, -1.20026139e-01,  7.43616064e-01, -3.87520380e-01,
         -3.63785008e-01, -1.37254902e-01,  1.24604979e-01,  1.10436107e-01,
          7.66000050e-02,  0.00000000e+00, -1.86892613e-01, -1.89728622e-01,
         -9.96331055e-01, -1.03903144e+00,  2.74089456e-01, -1.26065038e-01,
         -9.48291523e-01,  7.16264814e-02, -8.45550840e-01, -5.77649485e-01,
          7.16381983e-01, -3.64179851e-01, -4.31484000e-01, -4.75822056e-01,
         -7.09760099e-01, -8.77551020e-01,  5.21573092e-02,  1.17622641e-01,
          9.75946548e-03, -1.65032988e-01, -1.41913252e-01, -3.84857765e-01,
         -3.56591433e-01,  4.01537910e-01,  3.89020346e-01,  5.42364081e-01,
          1.98238426e-01,  3.66436762e-01,  5.17086498e-01,  1.32300728e-01,
          6.72451730e-02,  1.24863039e-01,  7.04309943e-01,  7.19386087e-01,
          2.89302392e-01,  8.67142569e-03, -3.34680734e-01, -4.46599412e-01,
          5.11976262e-01,  5.55555556e-02,  1.38195036e+00,  1.38723873e+00,
         -1.16737572e-01, -1.52653804e-01,  1.99068280e-01, -4.47583652e-01,
         -5.47662554e-01, -6.24204464e-01, -5.59837471e-01]),
  array([-0.58251187, -0.66583584,  0.4076337 ,  0.98484156, -0.62535158,
          0.52549016,  0.06898831,  0.97049496,  0.15729004,  0.36985705,
          1.78378378,  2.41886543,  0.9899916 ,  0.86955102,  1.63330717,
          0.8026826 ,  0.12680145,  1.0173395 ,  0.93405188,  0.78777417,
          1.2163201 ,  1.15312993,  0.70226353,  1.49178605,  1.2525137 ,
          1.29901007,  1.44820369,  1.17056906,  1.34562403,  0.99136057,
          1.23426941, -0.4887276 , -0.48199747, -0.27672104,  0.14846737,
          0.12570344, -0.26884699, -0.26137329,  0.25224892, -0.89981522,
          0.72971799, -0.13271219, -0.85581952, -0.34048211,  1.18091145,
          0.37122345,  0.93943651,  1.06468884,  0.76736574,  1.69222822,
          1.6940724 ,  0.95316959,  1.87391736,  1.6669932 ,  1.25219807,
          1.45033637,  1.2655965 ,  1.59186413,  0.25561545,  0.54167626,
          0.19341287,  0.94059509,  0.91816615,  0.42516051,  1.71623266,
          0.69434712,  0.65581133,  0.52049615,  1.13879786,  0.54871143,
          0.39876133,  1.00009804,  0.85594936, -0.2354408 , -0.31893125,
          0.50620758,  0.18716797,  0.05531614,  0.49266464, -0.22161534,
         -0.9898799 , -0.86280144, -0.68912933, -0.80769437,  0.81652642,
          0.01704133, -0.46979618, -0.10762361,  0.35835969,  0.10694744,
         -0.36276684, -0.848452  , -0.08859796, -1.60695895, -0.82605616,
         -0.06570236, -0.91256059, -0.73992026,  0.0189016 ,  0.25503396,
         -1.15420456, -0.57410595, -0.62751019, -0.53465464, -0.57432998,
         -0.48669093, -0.37856522, -0.2695386 , -0.12042177, -0.15776625,
         -0.22782488, -0.21072155, -0.11505415, -0.38953564, -0.83395039,
         -1.31778677,  0.21043183,  0.06906139,  1.81298842,  1.46335681,
          1.14575949,  0.9978158 ,  1.16909763,  0.83204349,  0.67855114,
          0.59160798,  1.77567525,  1.78072721,  1.44123893,  1.83494703,
          1.38316572,  2.26788588,  2.55018977,  2.72537119,  2.96996095,
          1.12836113,  1.02737675,  1.84435979,  1.93466251,  1.25313355,
          1.04093521,  0.7890151 , -0.64499829,  0.29893953,  0.86953871,
          0.56110816,  0.84220148,  0.51847585,  1.2416889 ,  2.53740076,
          2.99053839,  3.39882333,  3.08998892,  2.39055783,  0.29507466,
          1.40275411,  0.85961161,  1.76781724,  1.77253664,  1.73087246,
          2.48769993,  1.31560604,  1.84681923,  2.47412683,  0.56208315,
          0.8590724 ,  0.75      ,  0.36927447,  0.86437032,  0.08128347,
          0.33844018,  0.21125596,  0.53376415,  0.71269665,  0.41250358,
          1.61912432,  1.87182982,  0.81947578,  1.10142384,  0.7638839 ,
          0.90853251,  0.05699179, -0.5479715 , -0.60632072, -0.36722252,
         -0.19965308, -0.25437733, -0.13269984,  0.5100255 ,  0.57201287,
          2.73680896,  0.5292089 , -0.78742359, -0.77184498, -1.08398458,
         -0.77231191, -1.03626261, -1.53802381, -1.35821104, -1.67122742,
         -0.23735633, -0.72447156,  0.05337605,  1.62776996,  1.3129012 ,
          1.38490513,  0.56939443,  0.45244627,  0.43823499,  0.78086637,
          1.04629206,  0.98029412,  0.75829596,  0.69691105, -0.45455736,
         -0.39886962, -1.10593351, -1.09174327, -1.92116006, -1.11123132,
         -1.00148258, -1.10187366, -1.08642895, -0.87291636,  0.37989904,
          0.30779351,  0.20253524,  0.24371313,  0.29507466,  0.0148904 ,
         -0.13531782, -0.01433603,  0.00940762, -0.10849688,  0.985343  ,
          0.65437979,  0.69095053,  0.50160205,  0.2787778 , -1.43215786,
         -1.69807483, -1.51318195, -1.31202572, -1.46381087, -1.59138602,
         -1.36781589, -0.56042813, -0.42717883, -0.44731679, -1.7645436 ,
         -1.28295716, -1.42478228, -1.50922939, -0.96932859, -0.08235421,
         -0.14758065, -0.26305418,  0.71127546,  0.7950652 ,  0.34621854,
          1.18561079,  0.6811953 , -0.12688648]),
  array([ 1.46438436,  1.95475665,  2.00811143,  0.6661219 ,  0.59085321,
          0.18254569,  1.69877471,  2.57631973,  3.56642535,  1.87501316,
          1.94837125,  2.26339365,  2.73766563,  3.02353949,  3.32627355,
          2.39475841,  1.12208171,  0.85239406,  1.12716438,  0.58756425,
         -0.06922304,  0.94567499,  1.15346861,  0.34914964,  0.19366349,
         -0.11784264, -0.29171862, -0.09192452, -0.01428717, -0.51327924,
         -0.61011879, -1.14363722, -1.25824168, -1.25508026, -0.75820663,
         -0.83561644, -0.56742667, -1.13346614, -1.06905868, -0.95219558,
         -0.74200995,  0.43519414,  0.34883264,  0.62143964,  0.04990843,
          0.10130641, -0.20296914, -0.2329902 ,  1.03455715,  0.51703649,
          0.07200442,  0.12177838, -0.2453767 , -0.21252319, -0.38201153,
         -0.24054487,  0.57932412,  0.73197454,  0.75304498, -0.1395614 ,
         -0.13875355, -0.01252274, -0.03746132,  0.85840404,  0.892394  ,
          0.86386843,  1.48806499,  1.61960923,  0.73502576,  0.02912851,
          0.86481796,  2.27572145,  1.75045214,  1.59185397,  1.55629471,
          1.43707627,  1.49053286,  1.22091098,  1.52127766,  1.75444084,
          2.6682672 ,  2.87305573,  1.23373367,  1.73123679,  1.95982374,
          0.98259699,  1.21159175,  1.75106554,  2.35158702,  1.44998001,
          2.09680871,  2.11817438,  0.91553941,  1.00945178,  0.79685141,
          0.42563818,  0.49266464, -0.04839339,  0.21958604,  1.05475402,
         -0.86741264,  0.862286  ,  1.42833528,  2.08076747,  1.66561439,
          1.23091491,  1.16061131,  1.15526203,  1.54890198,  0.6453081 ,
          0.37301141, -0.29846004,  0.43643578,  0.85197103,  0.34902603,
         -0.96786455,  0.46532714,  0.9743912 ,  1.09299204,  0.60385342,
          1.01263622, -0.01971041,  0.14768457,  0.19252912,  0.25754184,
         -0.10479193, -0.14586499, -0.0488532 , -0.25543363, -0.00995086,
          0.77308264,  0.54596793,  0.48000073,  0.7809605 ,  0.1853695 ,
          1.51956881, -0.71980518, -0.71393289,  1.6464639 , -0.45801199,
          0.69145684,  1.44960351,  1.38947526, -0.89643585, -0.99564584,
         -1.07177413,  1.97906676,  1.83044118,  0.70220552,  0.26765874,
          0.31306705,  0.44652126,  0.38818017,  1.13319321,  0.52083906,
          0.31448545, -0.27928357,  0.03854505, -0.06483551,  0.65027735,
          1.15434816,  1.1392103 ,  0.92464842,  0.76367448,  0.92477056,
          0.16678398, -0.8123032 , -0.88127734, -0.54338553, -0.51071055,
         -0.50087742,  0.20791888,  0.0776931 ,  0.8012269 ,  0.77849894,
          0.22910419,  0.30484213,  0.3840932 ,  1.02436011,  0.69871737,
          0.92530316, -0.22118698,  0.41652052,  1.22741142,  1.14300525,
          1.28154518,  0.58412572,  0.30638552,  0.20363661,  0.05053389,
          0.16918197,  0.08336287,  0.5032578 ,  0.61572627,  0.20705176,
          0.65505855,  0.19890509,  0.64943153,  0.03393463,  0.02132492,
          0.19209762,  0.61910747, -0.66520903, -0.33863703, -0.65291846,
          0.03944382, -0.52604949, -0.24545441, -0.23526341, -0.17277369,
          0.06430142, -0.00441085, -0.11223628,  0.63116874,  0.91412255,
         -0.13857353,  0.04265499, -0.75829596, -0.58004189, -0.28764699,
         -0.23995691, -1.36450835, -1.37965177, -0.42282612,  0.63351905,
          0.85287268,  0.64098311,  0.03667547, -0.35473607, -0.23944693,
         -0.13369696,  2.06881969,  1.65027399,  2.85257275,  3.85414633,
          2.86966124,  1.49758198,  1.17238601,  1.26870768,  2.39308602,
          2.67394501,  2.5669604 ,  2.30180967,  2.4702421 ,  1.10996501,
          1.16876049,  2.28906711,  1.61366627,  0.8733828 ,  0.98484156,

In [8]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(235+263+331)
m=829

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(9):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

235
235
263
=
829

,subject,wrmodel,WER,BLEU,METEOR,BERT
0,1,speech,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,1,auditory,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."
2,1,speech,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,1,auditory,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,1,speech,"[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
5,1,auditory,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
6,2,speech,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
7,2,auditory,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
8,2,speech,"[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
9,2,auditory,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
10,2,speech,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
11,2,auditory,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ..."
12,3,speech,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
13,3,auditory,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, ..."
14,3,speech,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
15,3,auditory,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
16,3,speech,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
17,3,auditory,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [9]:
rows = []
for subject in [1, 2, 3]:
    for wrmodel in ['speech', 'auditory']:
        mask = (results_df['subject'] == subject) & (results_df['wrmodel'] == wrmodel)
        subset = results_df[mask]
        bert_values = np.concatenate(subset['BERT'].values).mean()
        rows.append({'subject': subject, 'wrmodel': wrmodel, 'significantly_decoded': bert_values})

to_file = pd.DataFrame(rows)
to_file.to_csv('perceived_movie_percentages.csv', index=False)

to_file

   subject   wrmodel  significantly_decoded
0        1    speech               0.131484
1        1  auditory               0.092883
2        2    speech               0.247286
3        2  auditory               0.376357
4        3    speech               0.290712
5        3  auditory               0.314837

In [10]:
# results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
# result_names = results.files
# result_files={}
# for name in result_names:
#     result_files[name] = results[name]
# result_files