In [1]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/imagined_speech/alpha_repeat-1.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['window_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('alpha_repeat-1', 'WER'): array([ 1.80435178,  0.39458176,  0.7553415 ,  0.65794351,  1.1450376 ,
        0.40872733,  1.1891742 ,  1.95762043,  0.8796883 ,  1.39007397,
        1.05956781,  1.03223887,  0.67617003,  1.04232344,  0.7667776 ,
        1.21165486,  1.6068432 ,  1.7444016 ,  2.3785895 ,  1.65056143,
        1.02012571,  1.24973367,  0.87942521,  0.88902428,  1.09511849,
        0.2549425 ,  0.29451819, -0.83297723,  0.14611468,  1.01485667,
        0.40168006,  0.42833926,  0.27511051,  1.47019011,  1.73797237,
        2.00656433,  1.32424345,  1.44767558,  0.59966694,  0.72514339,
        1.56436002]), ('alpha_repeat-1', 'BLEU'): array([ 0.10711633,  0.14219169,  0.25286393,  0.54276823,  0.53881591,
        0.75968704,  0.67347769,  0.73676474,  0.81378788,  0.93893092,
        1.28485223,  1.2111761 ,  1.66839135,  2.04652061,  2.47520212,
        2.3985014 ,  1.92157021,  1.09932218,  0.75564003,  0.2957186 ,
       -0.0646772 , -0.03506537, -0.55865013, -0.72474144, -0.39296577,
        0.22459349,  0.29709974,  0.82656829,  0.32954807,  0.79731293,
        1.74649321,  1.73761481,  1.99152563,  2.38909973,  2.26740621,
        2.02741262,  1.68503181,  2.24095678,  2.50430998,  2.55129347,
        2.80028719]), ('alpha_repeat-1', 'METEOR'): array([-0.97912547, -0.98059468, -0.88056979, -0.64520975, -0.61885612,
       -0.43677518, -0.47572311,  0.62462701,  0.76491261,  0.80935341,
        0.97569193,  0.90933394,  1.5804892 ,  2.08748341,  2.2216817 ,
        2.29559875,  2.11456353,  0.64234247,  0.3750378 , -0.30847801,
       -0.87342894, -0.87461517, -1.27688101, -1.00170318, -0.73113172,
       -0.37619441, -0.2517681 ,  0.12967547,  0.16480439,  0.00314621,
        0.82592456,  0.81283897,  1.1509173 ,  2.87247032,  2.69354092,
        2.60172496,  2.287593  ,  2.71026458,  2.92772848,  2.4312294 ,
        2.56287338]), ('alpha_repeat-1', 'BERT'): array([-0.6805724 , -0.85969144, -0.40011168,  0.15573733, -0.45014614,
       -0.5598176 , -0.255398  ,  0.21751592, -0.02710051,  0.20606264,
        0.09398437,  0.5635311 ,  0.51282936,  1.1180072 ,  1.7453156 ,
        2.2070813 ,  1.7257737 ,  1.3563807 ,  0.83951503, -0.64842534,
       -0.61066043, -0.33178553,  0.88810307,  0.5829055 ,  0.6254898 ,
        1.3396949 ,  3.1515749 ,  3.2368536 ,  3.80718   ,  4.712847  ,
        5.1917415 ,  5.6680164 ,  4.634117  ,  5.7461314 ,  4.5709066 ,
        4.800977  ,  4.9038954 ,  4.0207787 ,  4.226354  ,  4.26064   ,
        3.7585902 ], dtype=float32)}

In [2]:
window_zscores = {'subject': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}
for subject in [1,2,3]:
    for task in ["echo_repeat-2", "echo_repeat-1", "delta_repeat-2", "delta_repeat-1", "charlie_repeat-2", "charlie_repeat-1", "bravo_repeat-2", "bravo_repeat-1", "alpha_repeat-2", "alpha_repeat-1"]:
        scores = np.load(f'scores/S{subject}/imagined_speech/{task}.npz', allow_pickle=True)['window_zscores'].item()
        # print(scores['window_zscores'].item())
        window_zscores['subject'].append(subject)
        window_zscores['WER'].append(scores[(task, 'WER')])
        window_zscores['BLEU'].append(scores[(task, 'BLEU')])
        window_zscores['METEOR'].append(scores[(task, 'METEOR')])
        window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores

{'subject': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3],
 'WER': [array([ 0.75809125,  0.79325623, -0.38108186,  0.58893509,  0.42379592,
          0.12406125,  0.12668014,  0.21300967,  0.39652579,  0.88379864,
         -1.02663737, -0.87235674, -0.73184869,  1.03087014,  0.81566965,
          0.43685203,  1.37047865,  2.25404901,  1.5539527 ,  1.63681681,
          1.76310782,  0.77937675,  1.46091528,  0.7916245 ,  0.9218049 ,
          2.03109225,  1.29076687,  1.10419199,  1.15790496,  0.72070552,
          2.11493191,  2.54107987,  1.15217391,  2.18012868,  1.10130242,
          1.17232895,  2.46773126,  2.33486893,  2.1384111 ,  1.80794315,
          2.38468063]),
  array([-0.28636438, -0.00595502,  1.03746722, -0.3074594 , -0.48154341,
          0.52470632,  0.4975186 ,  0.81660563,  1.53510742,  0.40080519,
          0.77701682,  0.76056299,  1.28499688,  0.39820018,  1.1885587 ,
          1.43351643,  1.64097209,  1.00186719,  1.88208973,  1.24028999,
          1.38776942,  1.4420777 ,  0.93399166,  1.29456601, -0.13980887,
         -0.1353881 ,  0.01324649,  2.28691699,  1.69278129,  1.2984974 ,
          1.42366205,  1.42017638,  0.73728879, -0.71145999,  0.25968856,
          1.49243436,  0.69871737,  0.51574143,  0.5402006 ,  0.16498342,
         -0.24174689]),
  array([1.51849657, 2.04474408, 3.23868424, 1.60200256, 2.37099773,
         1.65467071, 1.3577418 , 2.48445858, 2.4603156 , 2.85388095,
         3.32163273, 3.01838819, 3.29395766, 3.54020229, 3.66124661,
         2.76476171, 3.12193643, 2.94097358, 2.86553804, 3.44713376,
         3.49247958, 2.98715496, 1.73288464, 0.81247854, 0.87792975,
         1.95317282, 0.93939213, 1.7645436 , 1.59876338, 1.47920052,
         1.84341015, 1.23648766, 1.42605532, 1.37958353, 1.72245838,
         1.36668147, 1.02641719, 0.36121191, 0.70816339, 1.4795153 ,
         1.58682868]),
  array([ 0.41670274,  0.29995834,  1.44060116,  0.78576892,  1.50741189,
          1.41596173,  1.87584637,  3.01078466,  2.67964188, -0.0174104 ,
          0.40893611,  0.24032595, -0.53237915, -0.44770043, -0.56672731,
          0.29800528, -0.46036844, -0.65042413,  1.02864159,  0.743064  ,
          0.76337004,  0.69197118, -0.2962738 , -0.15984477, -0.1660179 ,
          0.1668647 , -0.92894996, -1.93225903, -1.90527468, -1.65503613,
         -1.84114924, -1.71238084, -1.46135127, -1.5726673 , -1.40701114,
         -1.02804909, -1.18750554, -0.8554163 , -1.59932957, -1.56601175,
         -0.89689085]),
  array([-1.04694666,  0.39236695, -0.97877227, -0.80480325, -1.07437487,
         -1.07211253, -1.35418853, -1.01577203, -1.3545322 , -1.29462063,
         -0.08481889, -0.94179503, -0.50100426, -0.46935641,  0.15088969,
          0.35951881,  1.13967126,  0.8660254 ,  0.29926602, -0.14450492,
         -0.30980865,  0.73733549,  0.6910468 , -0.07267944,  0.31094623,
          0.99967303,  1.2655965 ,  1.26018496,  1.2655965 ,  0.56983913,
         -0.06010829, -1.00282052, -0.96506441, -0.79966229, -0.87541022,
         -0.49305865, -0.18894059,  0.14074837,  0.36276684,  0.90269504,
         -1.2722144 ]),
  array([-1.53044728, -2.26300953,  0.        ,  0.11378325,  0.66340766,
          0.01355386,  0.01811012,  1.3914618 ,  1.43643918,  2.62989648,
          0.87428682, -0.35992802, -0.27408946,  0.84527539,  0.98029412,
          0.76129074,  1.14731762, -0.02265135, -0.39778013, -0.20941562,
         -1.42729097, -1.48268502, -1.66720322, -1.67667762, -2.09036389,
         -2.20025609, -2.91001282, -2.11137011, -1.89928314,  0.02259346,
         -0.7178548 , -0.6515136 , -0.71505906, -0.53493751, -0.64411771,
         -0.42466374, -1.12283167, -0.70710678, -0.53833946,  0.10379166,
          1.03193835]),
  array([-1.14203056e+00, -9.73231702e-01, -1.24728421e+00, -1.39252025e+00,
         -1.18817705e+00, -1.24675745e-01,  7.15013739e-01,  7.03966688e-01,
          1.52143683e+00,  2.06474160e+00,  3.21465172e+00,  2.81153473e+00,
          3.00271430e+00,  1.56475191e+00,  2.68229150e+00,  2.10772688e+00,
          2.08963516e+00,  2.70876873e+00,  1.98071850e+00,  1.86370957e+00,
          1.75018066e+00,  1.53056146e+00,  1.70239259e+00,  1.24123008e+00,
          9.01155113e-01, -4.55915808e-01,  1.09980811e-01,  1.31879008e+00,
          8.39181358e-01, -8.49895584e-01, -6.18666153e-01, -1.22370211e+00,
         -1.18061775e+00,  7.55214288e-02, -2.63429439e-01, -1.54862507e-15,
         -9.82468468e-01, -1.35178736e+00, -1.03903144e+00, -1.41580057e+00,
         -6.51430344e-01]),
  array([ 2.18419602,  1.42868536,  1.92307692,  1.16461268,  0.7371988 ,
          0.93659795,  0.49960188,  0.26095212,  0.22109142,  0.35192853,
         -0.4823893 ,  0.06295246,  0.08545132, -0.55119609,  0.36710811,
          0.71646841,  0.1398159 , -0.06810305,  1.06856886,  0.9233852 ,
          0.8205379 ,  1.8695781 ,  1.19759151,  0.0536072 ,  0.60485838,
         -0.00848219, -0.17464259, -0.4218312 , -0.18852561,  0.42732739,
          0.62846414, -0.09230524, -0.24124895,  1.20208577,  0.72252458,
          1.31838971,  0.69854821,  0.89553347, -0.45244627, -0.68107337,
         -1.50749915]),
  array([ 1.12724296,  0.04955206,  1.09949206,  1.34134201,  0.90201026,
          0.78559754,  0.07049668, -0.38891173, -1.50839189, -0.76596647,
          0.02132492,  0.02500782,  0.21823025, -0.11071619,  0.11379649,
          1.10524648,  0.08390172,  0.07594519,  0.78659983,  0.86592093,
          0.14505544,  0.15359474,  0.47047689,  0.49743118,  0.48218242,
          2.11480321,  1.90906152,  2.17621496,  0.9053541 ,  1.62705643,
          0.35464968,  0.35717547,  0.28082274,  0.56387196,  0.86643227,
          1.45240802,  1.63906402,  1.65262582, -0.18051107, -0.88446033,
          0.06541485]),
  array([ 1.80435178,  0.39458176,  0.7553415 ,  0.65794351,  1.1450376 ,
          0.40872733,  1.1891742 ,  1.95762043,  0.8796883 ,  1.39007397,
          1.05956781,  1.03223887,  0.67617003,  1.04232344,  0.7667776 ,
          1.21165486,  1.6068432 ,  1.7444016 ,  2.3785895 ,  1.65056143,
          1.02012571,  1.24973367,  0.87942521,  0.88902428,  1.09511849,
          0.2549425 ,  0.29451819, -0.83297723,  0.14611468,  1.01485667,
          0.40168006,  0.42833926,  0.27511051,  1.47019011,  1.73797237,
          2.00656433,  1.32424345,  1.44767558,  0.59966694,  0.72514339,
          1.56436002]),
  array([ 3.26927405,  2.62213026,  2.59664468,  1.71831726,  1.5717518 ,
          1.14857226,  0.16080274,  0.29639637,  0.4276029 , -0.79740247,
          0.23284516,  0.59696515, -0.16208818,  2.54000254,  1.85425321,
          0.86974636, -0.37922629,  0.66899361, -0.18987257, -0.18614161,
         -0.29206777, -0.44744194, -0.45659384, -0.544855  , -0.73320378,
         -0.15205718, -0.04704761, -0.13947101,  0.48827308,  0.02073012,
          0.50219246,  0.50362645,  0.58906792, -0.29174484, -0.27386128,
          0.57946665, -0.6208347 , -0.5716726 , -0.48404788, -0.79020975,
         -0.18405716]),
  array([ 0.74201428,  0.06195325,  0.14057312, -0.79968106, -0.88546514,
         -0.0836974 ,  0.03641539,  0.22567603,  0.36539703,  0.04227682,
         -0.0769737 ,  0.06103413,  0.39438227, -0.32872857, -0.32032922,
          0.20100756,  1.70227712,  0.93912797,  0.55976629,  0.57207755,
          1.60962703,  1.06320944,  1.07832773,  0.57228075,  0.92952152,
          0.87436424,  1.28089569,  0.08004011,  0.49442106,  0.79862086,
          1.23274689,  2.41684122,  1.45495541,  1.76140969,  1.87361312,
          0.34166673,  0.11043153,  0.67080238, -0.32973126,  0.18181818,
          1.46558145]),
  array([ 1.01793024,  2.41362833,  1.44777663,  2.47509672,  1.48165149,
          0.45659384,  1.57135902,  1.58464393,  1.30306614,  1.94716087,
          2.27912595,  2.18996351,  3.22153424,  3.28744521,  3.0212252 ,
          2.10277432,  1.44444444,  1.292531  ,  0.36271004,  2.35798039,
          0.86181624,  1.02109974,  1.01776021,  2.74660104,  3.50008248,
          2.91468098,  3.65610834,  4.71713194,  3.71274867,  2.64297908,
          3.19267245,  2.65903218,  2.04754977,  2.59509546,  0.3848236 ,
         -0.93840891,  1.27727635,  1.96935995,  1.29406004,  1.44709354,
          0.14712364]),
  array([-1.05099994e+00, -5.20870703e-01,  4.57407415e-01, -1.04084892e+00,
          1.17451969e+00,  1.98396827e-01,  4.86309618e-01,  8.31702665e-01,
          6.91702496e-01, -3.38440183e-01, -9.26033888e-01, -1.18468056e+00,
         -1.04990131e+00, -1.05089682e+00, -1.76090181e-01, -1.01212759e+00,
         -8.93562821e-01, -1.07672806e+00, -1.18655863e+00, -5.67114123e-01,
         -5.54866948e-01, -5.30596579e-01, -1.52694352e+00, -4.76163456e-01,
         -1.33615330e+00, -2.13495578e+00, -2.23773340e+00, -1.25335325e+00,
         -2.23801154e+00, -1.81299866e+00, -1.17050076e+00, -8.98978434e-01,
         -8.77568563e-01, -3.07453894e-15, -6.01379154e-01, -7.48029125e-01,
          4.14425383e-01,  9.44513084e-01, -8.70648490e-01, -1.19250131e+00,
         -1.47094744e+00]),
  array([-1.02444263, -0.91878372, -0.2876148 , -0.33243985,  0.02518342,
          0.21786319,  0.24545441,  0.04531433, -0.1933473 ,  0.23570226,
         -0.64848847, -1.28835539, -1.07935864, -0.43812734, -0.21821789,
          0.85458766,  2.02116461,  1.84048595,  1.4969104 ,  1.17119839,
          0.90883249,  0.16245911,  0.37398113, -0.46412027, -0.10450628,
          0.62675974,  0.95329292,  0.96279254,  0.95276981,  3.00126332,
          0.69874797,  1.75730558,  1.60009264,  0.72514339,  1.42184655,
          1.75962264,  0.61859574,  1.03565981,  0.37152142, -1.29539277,
          0.00564342]),
  array([-0.12621323, -0.06656812,  0.40415894,  0.21464921,  0.51298918,
          0.61494005,  0.67297543,  1.06300735,  2.46311889,  0.8294508 ,
          1.00189574, -0.30856323, -0.78288136, -1.22900783, -1.28475971,
         -1.07002028, -1.17315222, -1.60784314, -0.34913429,  0.08040532,
         -0.28000853,  0.51707985,  0.41140493,  1.39413304,  1.7366258 ,
          0.48630962,  0.91477437,  0.14212656, -0.58907296,  1.40739739,
          2.21874456,  2.12936815,  1.82042407,  1.93318401,  1.58567255,
          1.81157892,  1.44298017,  0.86865942,  1.03479296,  1.53840729,
          0.6111775 ]),
  array([ 0.48929751,  1.29548811,  0.33572   ,  0.511119  ,  0.85824474,
          0.55254194,  1.32466675,  0.6267825 , -1.03017576, -1.32394521,
         -0.46510837, -0.48886592, -0.44231499, -0.24054487, -0.0895777 ,
         -1.16567587, -0.67343582, -0.16833946, -0.54770186, -0.52058647,
         -0.43621635,  0.01511551,  0.2804145 , -0.37300192, -1.58509915,
         -0.53338717,  0.04695584, -0.2695386 ,  0.0352399 , -0.04895954,
          0.06252385, -0.61751929,  1.2058407 , -0.20589436,  0.51806532,
          0.24271268,  1.50070939,  1.70135718,  0.59262575,  0.06631359,
          1.99020622]),
  array([ 0.44944782, -0.04214498,  0.3757889 ,  0.40009666,  0.79549513,
          0.15937762, -0.21698152,  0.20238925, -0.68739588, -0.88784869,
         -0.94852373, -0.46419674, -1.23906918,  0.63723955, -0.11764622,
         -0.11071619, -1.11063159, -1.46312704, -0.76069702, -0.90671567,
         -0.92192315, -0.80031723, -0.72416682, -0.95192479, -1.11112486,
         -0.875814  , -1.01709913, -1.19725308, -0.89105639, -0.88315182,
         -0.63392384, -0.41389614, -1.52456341, -0.90021436, -0.30636061,
         -0.26342944,  0.03528744, -0.28118346,  0.01535114,  0.51020537,
         -0.6970318 ]),
  array([ 1.01709913,  0.38191584,  0.5545227 , -0.02242869,  0.59329913,
          0.545311  ,  0.53626621,  0.64041345,  0.35447913,  0.20444119,
          0.78559754,  0.80244228,  0.49819197,  0.19953879,  0.50206717,
          0.83144999,  2.09246909,  2.26519649,  2.1961821 ,  1.67384267,
          1.6847684 ,  1.86908307,  1.70932737,  1.60147109,  0.94009462,
          2.13447353,  1.11822574,  2.41379708,  2.96725984,  2.185734  ,
          2.46545757,  1.46403818,  2.16306523,  3.25187426,  2.80948013,
          4.2597316 ,  5.20729022,  5.04301497,  2.57997582,  2.58789705,
          1.375     ]),
  array([-0.41181385, -0.92966968, -0.54494926, -0.44887706, -0.70133632,
         -1.39801768, -1.1447673 , -1.82050514, -0.55364502, -0.4423578 ,
         -1.3536998 , -1.0753361 , -0.74204814, -1.01015254, -0.13764944,
         -0.68516579, -1.05280372, -2.09562351, -1.2142193 , -1.16041426,
         -1.10782562, -0.4084801 , -0.08274077,  0.40456067,  0.55485132,
          0.48373924,  0.34733575, -0.17729688, -0.08070148, -0.13288212,
          0.10542553,  0.11008303, -0.06013293,  0.20668798,  0.44529131,
          0.12746914, -0.33514339, -1.02661104, -0.12106256, -0.75829596,
          0.15447525]),
  array([-0.16503299,  0.05248639,  1.2001984 ,  1.38808177,  1.42318434,
          0.99284544,  0.84664878, -0.82243246, -0.74769376, -0.9962506 ,
         -0.17823462, -0.2847474 , -0.10534179, -0.83212641, -0.0573016 ,
          0.43432411,  0.52000057,  0.45514956,  0.8059652 , -0.16948502,
          0.6277053 ,  1.57054696,  0.8100809 ,  1.58991927,  2.45410262,
          1.93480654,  2.19772138,  3.16341082,  3.06523579,  2.03539697,
          2.3902603 ,  2.06744979,  1.71604805,  1.38226979,  2.43032244,
          2.25955033,  0.24371313, -0.23276727, -0.22476762,  0.2655729 ,
         -0.09926844]),
  array([ 0.45568926,  0.70897115,  0.65351082, -0.07218967, -0.12608293,
         -0.29955541, -0.2849077 , -0.14579231,  0.86666318, -0.33409177,
         -0.39467898, -0.35132677, -0.41120263, -0.70462361, -0.81575472,
         -0.84425308,  0.14574887,  0.08913314, -0.43967877, -0.13927763,
         -0.0582353 , -1.11594825, -0.88931003, -0.3837024 ,  0.12606504,
          0.05653338, -0.75826677, -0.600742  ,  0.77109095, -0.3847226 ,
         -1.00442987, -0.93811359, -0.68694984,  0.2905305 , -0.62618797,
          0.8169443 ,  0.86928735,  1.43618891,  1.11705902,  0.03016485,
          0.2509876 ]),
  array([-0.78296109, -0.32841466,  1.24243027,  2.73990168,  2.67422515,
          0.22186537,  1.21053621,  1.41279267,  1.27528065,  1.14412193,
          0.85363628,  1.44039704,  1.73500198,  1.58481163,  1.61856616,
          0.63104256,  0.69795528,  1.42621959,  1.84831517,  2.45200344,
          2.4477024 ,  1.80099534,  0.77847981,  1.49181714,  1.30000614,
          0.78432607,  0.78265274,  1.9345539 , -0.67898398,  0.30662427,
          0.03278689,  0.1774713 ,  0.1789063 ,  0.1911959 ,  0.38079947,
         -1.0227483 , -1.22636518,  0.44977156, -0.12366507, -0.18530133,
         -0.5871464 ]),
  array([ 0.61177529,  0.94185678,  1.08024286,  0.43414476, -0.41100987,
         -0.48753809, -0.35676728, -0.25      ,  0.5614714 ,  1.3998351 ,
          2.01132602,  1.58704788,  1.72999664,  1.71813181, -0.10237806,
         -0.06350268,  1.17816593,  0.90432692,  1.57377477,  2.18396012,
          2.26339365,  2.64361907,  1.75885396,  3.3293041 ,  2.71951439,
          1.04170822,  1.82500261,  2.61390206,  1.59662734,  1.61174531,
          2.28803167,  2.60575509,  3.02076573,  3.79985852,  4.34793452,
          2.69984382,  2.37183296,  1.8804572 ,  1.1652508 ,  1.67849211,
          0.60990569]),
  array([ 0.98782916,  0.82425995,  1.29270634,  0.24333395, -0.34144148,
          0.45979785,  0.39584869,  0.51468345, -0.8177919 , -0.73186808,
         -0.50361585, -0.18923375,  1.01121178,  1.35558125,  0.76540961,
          0.84459354,  1.67667762,  2.25785343,  0.78276757,  0.43643578,
          0.62566373,  1.42635296,  0.07685206, -0.07579097,  0.30236859,
          0.97517822,  1.30853512,  1.26282507,  1.15175612,  1.2523568 ,
          0.65972096,  1.70866151,  1.57722733,  1.76480203, -0.17756626,
         -0.88446033, -0.5984684 , -0.24652068, -0.08692914, -0.51275642,
         -0.01097709]),
  array([ 3.08487384,  3.30314125,  2.73533198,  1.74522545,  2.76581619,
          2.83678872,  1.78976842,  1.18100594, -0.28829639, -0.96398156,
         -0.01440195,  0.59708207,  0.18618138, -0.00932545, -0.37629986,
         -0.5866129 , -0.55474053, -0.12289115,  0.29127407,  0.58501021,
          1.12891556,  0.58072358,  0.70133156,  2.50624901,  2.03518867,
          0.96225045,  0.45032609,  0.43310478,  1.20458344, -0.30969115,
          0.04209148,  0.08692914, -0.07218967,  0.11706962,  1.47959089,
          1.70240901,  0.18310144,  0.75750528,  1.08357181,  0.46009501,
         -0.36837223]),
  array([-4.81639854e-01,  2.62467121e-01,  1.15303589e-01,  1.56703328e-01,
         -1.86002796e-01,  4.28577818e-01,  3.91033933e-03,  6.02900903e-01,
         -2.04523830e-01, -1.37606352e-01, -1.62086791e+00, -7.96490921e-01,
         -4.44950218e-01, -2.07143004e-01, -3.17686639e-02, -9.59975777e-01,
         -3.35068523e-01,  7.36363238e-01,  3.61397032e-01, -7.13392896e-01,
          7.10742316e-01,  9.26094723e-01,  1.28834456e+00,  1.93717306e+00,
          1.25852282e+00,  1.05475402e+00,  3.90391899e-02, -1.06393573e-01,
          3.02986706e-01, -3.95326851e-15,  1.21632010e+00, -7.23043186e-01,
         -4.88531969e-02, -2.27360631e-01, -8.51598246e-01, -1.49293693e+00,
         -1.33181178e+00, -1.42246665e+00, -1.17079573e+00, -5.44693465e-01,
         -8.38338383e-01]),
  array([-0.16589314,  0.10243821,  2.41209076,  3.05190552,  3.00734109,
          0.44022545,  0.99074731,  1.52664507,  1.53449956,  1.60444953,
          1.01610232,  1.50150225,  0.77360621,  0.98167727,  1.18906509,
          2.14181646,  0.76894131,  0.78299363,  1.26231064,  0.87477144,
          0.95842088,  1.8276231 ,  1.23644405, -0.09759001,  0.46510837,
          2.04904174, -0.82055272,  0.22602255, -1.28159495, -0.45749571,
         -0.44690443, -0.53761707,  1.24434203,  0.67075489, -0.50054342,
          0.12144654, -0.97834757,  0.81764814,  0.21952852, -0.30718186,
          0.28611863]),
  array([ 0.79250793,  0.56369396,  0.90408963,  0.84197806,  0.5559033 ,
          0.62258877,  0.00348792,  0.16494681,  0.9294667 , -0.81762356,
         -1.2695324 , -0.37918474,  0.03592106, -0.48605607, -0.16713157,
          0.27487017, -0.63282806, -1.41886351, -0.74098702, -1.32070989,
         -1.2616516 , -1.28074127, -1.06809131, -0.12445986, -0.18013433,
          0.63637509,  0.42782233, -0.05298926,  0.05376509,  0.00798112,
          0.13991608,  0.24201144,  0.24173888, -0.07088812,  0.6882472 ,
          1.42170068,  2.14531121,  2.1509603 ,  0.54545455,  0.68973049,
         -0.35977364]),
  array([ 1.69205895,  0.78666218,  0.31919711,  0.60663431,  0.46917044,
          0.95696949,  0.88971795,  0.84563235,  1.31176642, -0.55584245,
          0.07273397, -0.65411991,  0.53000229,  0.11581372,  0.64299905,
          0.47564513,  0.28847917, -1.04094985, -0.88981054, -1.50030753,
         -1.36515215, -1.43282776, -1.19722581, -1.35604142,  0.21777735,
         -1.40177016, -0.7066176 , -0.30151134, -0.02274883, -0.85287205,
         -0.50825159, -0.45035487, -1.27556114,  0.07368391, -0.12212631,
          0.60166452, -0.86407199, -0.11481404,  0.33232713,  0.35763718,
          0.35112344])],
 'BLEU': [array([-0.55697238, -0.17946714,  0.2967849 , -0.27720746, -0.12143817,
         -0.26386408,  0.91213238,  0.19557813,  1.02251087,  0.53980512,
          0.27895967,  0.31722063,  0.4516086 ,  0.79616686,  0.88411422,
          0.93716406,  1.53044007,  1.54315126,  1.08368697,  1.62643226,
          0.97314333,  0.55319981,  0.71209743,  0.84040088,  1.36719815,
          1.60582149,  1.70590967,  2.21867679,  1.71988088,  1.64106334,
          1.95117398,  1.63504309,  1.3574182 ,  0.66077594,  0.40473916,
          0.58540951, -0.13850867, -0.89642146, -0.36346511, -0.17385833,
          0.33197867]),
  array([ 1.14089163,  1.53468355,  0.81975154,  0.47325227,  0.6673208 ,
          0.47340862,  0.93075784,  0.44630711,  0.23400036,  0.32999712,

In [3]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print(len(results_df.loc[3, 'WER']))
print(len(results_df.loc[4, 'WER']))
print(len(results_df.loc[5, 'WER']))
print(len(results_df.loc[6, 'WER']))
print(len(results_df.loc[7, 'WER']))
print(len(results_df.loc[8, 'WER']))
print(len(results_df.loc[9, 'WER']))
print('=')
print(41*10)
m=410

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT'] + results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT'] + results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT'] + results_df.loc[9, 'BERT']).mean()
S2=np.array(results_df.loc[10, 'BERT'] + results_df.loc[11, 'BERT'] + results_df.loc[12, 'BERT'] + results_df.loc[13, 'BERT'] + results_df.loc[14, 'BERT'] + results_df.loc[15, 'BERT'] + results_df.loc[16, 'BERT'] + results_df.loc[17, 'BERT'] + results_df.loc[18, 'BERT'] + results_df.loc[19, 'BERT']).mean()
S3=np.array(results_df.loc[20, 'BERT'] + results_df.loc[21, 'BERT'] + results_df.loc[22, 'BERT'] + results_df.loc[23, 'BERT'] + results_df.loc[24, 'BERT'] + results_df.loc[25, 'BERT'] + results_df.loc[26, 'BERT'] + results_df.loc[27, 'BERT'] + results_df.loc[28, 'BERT'] + results_df.loc[29, 'BERT']).mean()
print(S1,S2,S3,'BERT')

results_df

41
41
41
41
41
41
41
41
41
41
=
410
0.08536585365853659 0.3902439024390244 0.20243902439024392 BERT

,subject,WER,BLEU,METEOR,BERT
0,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,1,"[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, ..."
4,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
11,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
12,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, ..."
13,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."
14,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
15,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ..."
16,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ..."
17,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
18,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
19,2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
21,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, ...","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
22,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
23,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, ..."
24,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ..."
25,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
26,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, ..."
27,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, ..."
28,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, ..."
29,3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [5]:
to_file = pd.DataFrame({'subject':[1,2,3], 'significantly_decoded': [S1,S2,S3]})
to_file.to_csv('imagined_speech_percentages.csv', index=False)

to_file

   subject  significantly_decoded
0        1               0.085366
1        2               0.390244
2        3               0.202439

In [6]:
results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

{'words': array(['she', 'said', 'she', ..., 'that', 'she', 'needs'],
       shape=(1589,), dtype='<U13'),
 'times': array([ 10.2,  10.6,  11. , ..., 591. , 591.4, 591.8], shape=(1589,))}