In [1]:
# Significant similarity to audio descriptions. 

import numpy as np
import pandas as pd

scores = np.load('scores/S1/perceived_speech/gpt_layers_3_5_7_9/wheretheressmoke.npz', allow_pickle=True)
print(scores.files)
score_names = ['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
score_files = {}
for name in score_names:
    score_files[name] = scores[name].item()

print(score_files['window_zscores'])

['window_scores', 'window_zscores', 'story_scores', 'story_zscores']
{('wheretheressmoke', 'WER'): array([-2.83584442e-15,  1.02416281e+00,  8.09638345e-01,  5.84936013e-01,
        8.90026857e-01,  1.32067636e-01,  3.46895762e-01,  9.52630069e-01,
        1.20995588e+00,  1.10318691e+00,  1.16697591e+00,  2.34543223e+00,
        2.98662997e+00,  2.42529003e+00,  2.83314068e+00,  2.28785370e+00,
        3.11138623e+00,  2.63438441e+00,  1.54642163e+00,  1.02442668e+00,
        2.11911637e+00,  8.65884132e-01,  8.92268598e-01,  2.17105433e+00,
        2.35985820e+00,  1.41437547e-01,  2.77797329e-01,  1.61639361e+00,
        1.24052255e+00,  8.05653536e-01,  5.86767048e-01,  2.22327362e-01,
        2.94218804e-01,  1.19442208e+00,  2.19063736e+00,  2.02801257e+00,
        1.65664667e+00,  3.10879129e+00,  2.67088519e+00,  3.48789000e+00,
        2.94184818e+00,  2.11995052e+00,  1.18982615e+00,  1.83643427e+00,
        7.76786630e-01,  1.95771420e+00,  3.64504070e+00,  3.38396058e+00,
        2.51678554e+00,  1.78645055e+00,  1.61796004e+00,  2.06355112e+00,
        1.90847892e+00,  2.41432343e+00,  2.14436565e+00,  3.61122158e+00,
        3.21895220e+00,  3.83984714e+00,  4.41171594e+00,  4.06409192e+00,
        4.66049916e+00,  5.06814034e+00,  4.47421760e+00,  5.79627335e+00,
        2.20172736e+00,  7.67444248e-01,  1.05456341e+00,  4.05480254e-01,
       -4.90000043e-01,  1.35246521e+00,  5.40008219e-01,  8.24529770e-01,
        1.63399219e+00,  5.65032047e-01, -2.09610479e-01,  1.30028478e-01,
        3.22823141e-01,  1.15221153e+00,  2.55033961e-01,  1.10516884e+00,
        7.41236918e-01,  4.85942101e-01,  9.25436444e-01,  1.37070923e+00,
        1.25776551e+00,  1.89894532e+00,  1.71433100e+00,  1.92851454e+00,
        1.87753685e+00,  8.77929748e-01,  5.51015751e-01, -4.38671957e-02,
        3.88882659e-01,  1.22589562e+00,  2.21328783e+00,  2.29187769e+00,
        3.43742869e+00,  3.02256010e+00,  3.44260443e+00,  3.25601220e+00,
        2.23352898e+00,  2.47681468e+00,  1.96798801e+00,  1.92596602e+00,
        1.29215731e+00,  1.73342636e+00,  1.93482423e+00,  1.44989302e+00,
        1.03796697e+00,  1.01948220e+00,  1.09595262e+00,  9.58372715e-01,
        7.18278196e-01,  2.93294230e-01,  7.46984583e-01,  9.27579416e-01,
        2.03320573e-01,  2.36433122e-01,  5.10566119e-02, -9.16167209e-01,
       -8.89051270e-01, -7.20147053e-01, -3.86872293e-02,  1.08173216e+00,
        1.10038779e+00,  1.26057419e+00,  1.64215347e+00,  1.10971229e+00,
        1.45618374e+00,  1.42770616e+00,  1.99045870e+00,  2.21063665e+00,
        2.69295737e+00,  2.35237387e+00,  2.27950613e+00,  3.49515592e+00,
        2.79978158e+00,  2.71203999e+00,  3.03782470e+00,  3.47566606e+00,
        3.10691502e+00,  2.93666484e+00,  2.05011741e+00,  2.37584516e+00,
        2.51153263e+00,  3.13700400e+00,  3.35840955e+00,  2.76029204e+00,
        2.91683446e+00,  2.83724895e+00,  3.12870165e+00,  2.91305148e+00,
        2.10282327e+00,  2.33512822e+00,  2.07200258e+00,  1.27653582e+00,
        3.24112158e-01, -6.06594872e-01, -8.70784780e-02, -2.47435830e-01,
       -8.89866819e-01, -6.36184827e-01, -1.11347249e-01, -4.39462543e-01,
       -9.24477500e-01, -2.14269543e-01, -8.35801524e-01, -4.61622775e-01,
       -9.91384481e-01, -7.24831545e-01,  1.06445521e-01,  6.57554256e-01,
        9.11413858e-01, -6.32786443e-01, -1.13774693e+00, -1.34485080e+00,
        4.26871667e-01,  3.69274473e-01, -8.40900096e-01,  5.08555746e-02,
        8.72871561e-01,  9.08646417e-01, -8.24673906e-01, -8.05556126e-02,
        6.50063709e-01, -4.88037908e-01,  1.47457985e-02,  9.94611766e-01,
        2.22796660e-01,  3.99110725e-01, -2.65328742e-01, -2.00601341e-01,
        2.32024326e-01, -2.45856436e-01,  1.50593743e+00,  1.23759669e+00,
        2.90641294e+00,  2.07135823e+00,  1.95720037e+00,  1.38645316e+00,
        9.49077734e-01,  7.84652076e-01,  2.51222205e+00,  1.05352015e+00,
        2.07741111e+00,  2.99874355e+00,  1.17932379e+00,  9.35257269e-01,
        1.48266964e+00,  6.99680641e-01,  2.09678633e+00,  2.64012504e+00,
        2.46612465e+00,  3.40422684e+00,  1.92791024e+00,  2.74429820e+00,
        1.71176999e+00,  2.04598562e+00,  1.74179127e+00,  2.40610766e+00,
        4.09889641e+00,  4.68373348e+00,  2.88981433e+00,  2.56555833e+00,
        3.25913973e+00,  1.69836912e+00,  2.13635834e+00,  2.50000000e+00,
        3.97492138e+00,  3.12433600e+00,  3.04563694e+00,  4.11670656e-01,
        4.69877262e-01,  1.23311714e+00,  1.55542754e+00,  1.19224206e+00,
        1.60358967e+00,  7.30556906e-01,  8.16631590e-01,  1.29774741e+00,
        1.07679455e+00,  1.74786767e+00,  1.67499087e+00,  1.52020558e+00,
        1.27603254e+00,  1.14478442e+00,  2.25274141e+00,  2.61908381e+00,
        1.45148441e+00,  1.22932680e+00,  1.71910071e+00,  1.46221099e+00,
        1.18377646e+00,  6.52116192e-01,  9.11953487e-01,  9.15939662e-01,
        1.95154202e-01, -2.78196795e-01, -6.61697858e-01, -1.28307665e+00,
       -6.54653671e-01, -1.42626912e+00, -1.70575867e+00, -1.82987214e+00,
       -1.49022791e+00,  2.64386351e-01, -2.00522330e+00, -1.23437266e+00,
       -5.84582009e-01,  1.25251370e+00,  3.29754947e-01, -3.66436762e-01,
       -9.54574876e-02,  3.52412034e-01,  1.54896741e+00,  1.54997297e+00,
        2.60654308e+00,  3.49808417e+00,  3.60505475e+00,  3.19650169e+00,
        5.06625957e+00,  4.92568600e+00,  4.71707770e+00,  4.17452039e+00,
        4.15902199e+00,  3.55091867e+00,  4.01544850e+00,  4.32669985e+00,
        3.60447430e+00,  4.47643205e+00,  4.48561135e+00,  4.53927225e+00,
        4.39462822e+00,  4.40011086e+00,  2.66864975e+00,  4.30769231e+00,
        3.67820045e+00,  3.13604034e+00,  3.40810906e+00,  3.29319032e+00,
        1.10258614e+00,  5.42937679e-01,  1.38232703e-01,  2.16643973e-01,
        6.88333362e-01,  2.43256386e-01,  2.96695415e+00,  2.92133391e+00,
        3.16275183e+00,  1.36438534e+00,  2.40698068e+00,  8.38175247e-01,
        1.65471821e+00,  1.96774705e+00,  3.19955319e+00,  1.51737177e+00,
        1.94837125e+00,  1.87330826e+00,  1.77353684e+00, -2.64070005e-01,
       -8.61600446e-01, -2.73946193e-01, -2.18489226e-01, -2.31643123e-01,
       -2.47231932e-01, -2.08741430e-02, -6.38511102e-01, -6.76230296e-01,
       -3.21942282e-01, -5.56369868e-01, -6.41543316e-01,  9.05719470e-02,
       -6.66451414e-01, -3.43634466e-01, -1.14035252e+00, -8.55466854e-01,
       -7.77188539e-01,  8.73240718e-01,  9.96746035e-01,  5.34115830e-01,
        8.36107020e-01,  8.84230501e-01,  5.02237679e-01,  1.96776706e+00,
        1.52080409e+00,  1.94320096e+00,  1.25748649e+00,  1.32855627e+00,
        1.97616695e+00,  2.13221249e+00,  2.09373750e+00,  2.53791575e+00,
        7.96074648e-01,  8.77058019e-01, -2.96789846e-01,  9.65621881e-01,
        1.00403800e+00, -2.60952124e-01, -3.56602641e-01, -1.40274365e-01,
        1.46945284e+00,  1.57914205e+00,  1.92487440e+00,  1.13071939e+00,
        6.80967968e-01,  7.92145738e-01,  7.55029414e-02,  1.47846509e+00,
        7.21321053e-01,  8.12990232e-01,  1.01157923e+00,  4.54296735e-01,
        5.54849627e-01,  6.50427218e-01,  5.82190570e-01, -7.62960717e-02,
        4.44410979e-01,  1.10386042e+00,  1.02885448e+00,  8.66241869e-01,
        1.89541316e-01,  7.01683569e-01, -8.24971642e-02,  1.22191440e+00,
        1.06500150e+00,  1.85718659e+00,  1.98263769e+00,  1.10296055e+00,
        1.13187611e+00,  1.76889331e+00,  1.88425737e+00,  2.68032521e+00,
        2.32019951e+00,  2.01494688e+00,  1.51177902e+00,  1.76889331e+00,
        1.06450564e+00,  3.46506093e-01,  1.10321753e-01,  2.31640341e-01,
        3.21664487e-01, -9.01127353e-01, -3.61982270e-01,  3.97700456e-01,
        7.31167039e-01,  6.77903118e-01,  1.05367962e+00,  1.68983692e+00,
        3.58740949e-01,  4.35539644e-01,  3.99884757e-01,  8.03435538e-01,
        1.47796619e+00,  1.55128205e+00,  2.45491362e+00,  2.10922295e+00,
        1.80430518e+00,  1.56547275e+00,  2.25199685e+00,  2.55334880e+00,
        3.57838527e+00,  2.92578698e+00,  3.96396908e+00,  3.57355834e+00,
        3.57204407e+00,  2.31545312e+00,  2.91503756e+00,  1.58569276e+00,
        1.09655531e+00,  9.88931921e-01,  5.47401085e-01,  4.35153275e-01,
        3.87201546e-02,  3.09074714e-01,  1.32378340e-01, -4.26806709e-01,
       -9.08780255e-01, -5.04840563e-01, -1.09559839e-01, -9.67448927e-01,
       -7.59089638e-01, -2.57749777e-01,  9.75361440e-01,  1.26410749e+00,
        1.09010500e+00,  8.84307911e-01,  2.42822526e+00,  1.93438590e+00,
        1.59708450e+00,  2.63780464e+00,  2.78939201e+00,  3.01688399e+00,
        2.88032685e+00,  1.99917868e+00,  2.27335992e+00,  2.51754627e+00,
        2.59752548e+00,  2.29995563e+00,  2.77179224e+00,  3.01182279e+00,
        2.38833973e+00,  2.51491470e+00,  2.22381308e+00,  2.84942399e+00,
        2.82845317e+00,  2.86813944e+00,  2.48932697e+00,  2.72097051e+00,
        2.82189050e+00,  3.05756857e+00,  1.90400760e+00,  1.96935167e+00,
        1.66769051e+00,  2.40623829e+00,  1.92086469e+00,  1.86759818e+00,
        3.13254790e+00,  3.45005394e+00,  2.12582510e+00,  3.22125295e+00,
        3.46159155e+00,  2.71911122e+00,  2.80961055e+00,  2.90054255e+00,
        3.19089310e+00,  3.80556622e+00,  3.13395995e+00,  3.22126423e+00,
        2.50972800e+00,  1.68930605e+00,  1.72392288e+00,  1.57960966e+00,
        2.37533891e+00,  2.59462018e+00,  2.41861589e+00,  1.93049611e+00,
        2.01399597e+00,  2.52180604e+00,  2.32291049e+00,  1.57714824e+00,
        3.65407567e-01,  6.44278154e-01,  3.85223700e-01,  2.23043704e-02,
        5.92018945e-01,  6.49639190e-01,  3.90816776e-01,  1.11312491e+00,
        7.02145944e-01,  1.28831603e+00,  1.21639614e+00,  1.09333878e+00,
       -5.32327310e-01, -2.18699881e-01,  9.64979379e-02, -9.15846131e-02,
       -1.43237881e-01, -3.04745259e-02, -1.59468474e-02, -2.13249188e-02,
        9.24500327e-01, -7.21514145e-01,  1.11306925e+00,  5.96623066e-01,
        3.96010091e-01,  7.71591333e-01, -2.41817561e-02, -3.87100885e-01,
       -6.74621334e-01, -6.39350802e-01, -6.35674156e-01,  4.58228004e-01,
        1.21808609e+00,  1.38110434e+00,  5.69839131e-01,  7.86666183e-01,
        5.46812908e-01,  5.01543030e-01,  3.96139783e-01,  8.73192003e-01,
        1.08711461e+00,  1.01407365e+00, -9.69080545e-02,  2.90179273e-01,
        8.92714430e-01,  1.74586839e+00,  1.60698323e+00,  2.31768108e+00,
        3.75233543e+00,  3.89884663e+00,  3.71356973e+00,  2.14013669e+00,
        1.25901837e+00,  1.17568559e+00,  7.06114505e-02,  9.79197611e-01,
        9.41870808e-01,  1.58651627e+00,  1.24295447e+00,  1.21734316e+00,
        1.25855523e+00,  1.27653582e+00,  1.08525104e+00]), ('wheretheressmoke', 'BLEU'): array([ 2.10351450e-01,  8.37956462e-01,  1.08226686e+00,  1.03274645e+00,
        1.15796132e+00,  1.79526820e+00,  1.39895915e+00,  1.90706785e+00,
        8.38788271e-01,  5.39022821e-01,  4.34782609e-01,  1.28496290e+00,
        1.47480734e+00,  2.41104061e+00,  2.19618030e+00,  1.97975899e+00,
        1.65311948e+00,  1.85660061e+00,  1.43592647e+00,  9.83518543e-01,
        1.29517151e+00,  1.04409673e+00,  8.82855568e-01,  9.86900800e-01,
        2.67401519e-01,  4.42316978e-01,  9.86244289e-01,  2.22711538e+00,
        2.03328265e+00,  1.82748903e+00,  1.81171384e+00,  1.83180292e+00,
        1.38204329e+00,  1.65628374e+00,  2.12836333e+00,  2.12649211e+00,
        1.81605515e+00,  1.47513660e+00,  1.18272733e+00,  1.39380641e+00,
        1.00918297e+00,  9.37444097e-01,  6.82732073e-01,  6.08796102e-01,
        1.35385951e+00,  1.88333481e+00,  1.10159500e+00,  1.57509239e+00,
        1.74940110e+00,  1.76362221e+00,  1.00440379e+00,  1.10546825e+00,
        1.42457843e+00,  1.33445361e+00,  1.05791606e+00,  1.43870415e+00,
        1.41794739e+00,  1.76712705e+00,  1.84935345e+00,  1.69653791e+00,
        2.22408743e+00,  2.21304660e+00,  2.13259173e+00,  2.07460986e+00,
        1.21242830e+00,  5.77225352e-01,  2.42708071e+00,  1.57709187e+00,
        2.22249962e+00,  2.58379273e+00,  2.22665360e+00,  1.73684211e+00,
        1.12817218e+00,  1.11336048e+00,  1.12146020e+00,  1.12146020e+00,
        1.12146020e+00,  8.91114590e-01,  7.84958590e-01,  1.02936617e+00,
        9.91115041e-01,  3.46885306e-01,  1.82342185e-01, -2.37115747e-01,
        9.69868694e-03, -9.99513387e-02,  2.30489812e-02,  9.80015779e-01,
        1.08970659e+00,  4.79713373e-01,  9.03679571e-01,  1.24120706e+00,
        1.72115453e+00,  1.30435224e+00,  1.33724334e+00,  2.23634670e+00,
        2.39168341e+00,  2.57255650e+00,  3.38020347e+00,  3.54334830e+00,
        3.52676989e+00,  3.98730559e+00,  3.82840570e+00,  3.42438970e+00,
        3.24986356e+00,  3.45563417e+00,  2.42459106e+00,  2.17169381e+00,
        2.39573076e+00,  2.25339052e+00,  2.55653475e+00,  2.08041186e+00,
        2.09785764e+00,  2.09600283e+00,  1.33596934e+00,  1.02982020e+00,
        9.47637908e-01,  9.44550362e-01,  9.25244439e-01,  6.22296039e-01,
        4.09233209e-01,  1.04567036e-01,  7.83962756e-02,  5.81677002e-01,
        7.93436186e-01,  2.75544545e-01,  4.30220844e-01,  3.59963693e-01,
        6.28407206e-01,  8.51597978e-01,  7.98638323e-01,  1.12685175e+00,
        1.59977493e+00,  1.43470727e+00,  1.64875403e+00,  1.87503755e+00,
        1.66162794e+00,  2.09358949e+00,  2.50171072e+00,  2.98669724e+00,
        2.31689350e+00,  2.66634887e+00,  2.74572724e+00,  2.71029818e+00,
        1.79834762e+00,  1.79834762e+00,  1.69162099e+00,  2.28935614e+00,
        2.67106910e+00,  2.23701441e+00,  1.65585024e+00,  2.05263747e+00,
        1.35625294e+00,  1.39273114e+00,  1.42982034e+00,  9.17198106e-01,
        4.60396908e-01,  1.09409607e+00,  1.18411283e+00,  9.59398767e-01,
        7.52015089e-01,  1.91914802e-01, -3.77021427e-01, -4.65392159e-01,
       -8.65643346e-02, -3.84049161e-01,  1.02754759e-01, -5.60612575e-01,
       -2.38203117e-01, -1.24247305e-01, -3.80609588e-01,  1.30445880e-02,
        2.79766224e-01, -2.41065999e-01,  1.18095503e-01,  4.87858144e-01,
        8.01127111e-01,  4.37672502e-01,  3.13992913e-01,  5.07468161e-01,
        5.48330370e-01,  1.08115727e+00,  3.26216523e-01,  7.07050138e-01,
        1.32837984e+00,  1.17599616e+00,  5.70713839e-01,  6.66786911e-01,
        1.10061955e+00,  1.53787232e+00,  1.14297427e+00,  1.16915034e+00,
        1.92590148e+00,  2.15250650e+00,  2.71066545e+00,  1.95493871e+00,
        2.77342035e+00,  9.38533895e-01,  2.26366616e+00,  2.35673756e+00,
        1.95133424e+00,  2.67889011e+00,  3.44239629e+00,  4.26704110e+00,
        3.59195241e+00,  4.28458213e+00,  3.66718796e+00,  2.92454716e+00,
        2.75481283e+00,  2.64856994e+00,  2.69062792e+00,  2.47013213e+00,
        2.25324413e+00,  1.51132114e+00,  1.30607961e+00,  1.94729063e+00,
        1.43805958e+00,  1.09760480e+00,  9.87291191e-01,  6.30507142e-01,
        8.87485928e-01,  1.07354544e+00,  1.07749722e+00,  1.40138333e+00,
        1.22601844e+00,  6.43462019e-01,  4.86974033e-01,  5.84678718e-01,
        7.19761215e-01,  1.06212202e+00,  9.41800275e-01,  1.09621440e+00,
        1.17903073e+00,  1.10823148e+00,  1.47840099e+00,  1.89784182e+00,
        1.73147238e+00,  1.33414251e+00,  1.17877364e+00,  1.28461825e+00,
        1.45238842e+00,  1.71739433e+00,  1.32278139e+00,  1.30861090e+00,
        1.03852035e+00,  5.02263970e-01,  1.49543498e+00,  1.76034289e+00,
        7.87723539e-01,  6.12439200e-01,  8.82639247e-01,  6.38405650e-01,
        6.81894263e-01,  1.61627046e-01,  1.91423350e-01,  3.47793270e-01,
       -2.98194124e-01, -6.02900903e-01, -8.16199288e-01, -4.72055183e-01,
       -5.08657264e-02, -1.84841320e-01, -6.10342839e-01, -5.78318893e-01,
       -1.22908946e+00, -9.48597234e-01, -1.30018684e+00, -1.36307267e+00,
       -1.27868667e+00, -7.20500361e-01, -8.45241444e-01, -8.92133436e-02,
        1.59323232e-01, -1.72670886e-03,  4.22396139e-01,  5.44787607e-01,
        1.11294191e+00,  1.14228282e+00,  6.87028391e-01,  5.58088543e-01,
        6.88968863e-01,  1.09281209e+00,  1.57836037e+00,  1.78125180e+00,
        2.02729430e+00,  1.61134634e+00,  1.78963227e+00,  1.63682917e+00,
        1.25458866e+00,  1.17879470e+00,  1.34796631e+00,  1.95114560e+00,
        1.05287288e+00,  1.58257044e+00,  2.25588230e+00,  2.31484664e+00,
        1.58873657e+00,  1.45981473e+00,  1.57882450e+00,  2.32339495e+00,
        1.90377311e+00,  1.79691469e+00,  1.51707174e+00,  1.39404621e+00,
        1.42221406e+00,  8.65286339e-01,  1.41894726e+00,  1.40564160e+00,
        1.71690880e+00,  1.87293423e+00,  1.97492765e+00,  1.60125713e+00,
        2.23595744e+00,  1.98171980e+00,  1.95890136e+00,  1.76320833e+00,
       -1.21967932e-01, -7.92662205e-02, -7.04751716e-01, -1.03393081e+00,
       -8.32210437e-01, -8.33728542e-01, -7.00220830e-01, -6.65050789e-01,
       -1.16478562e+00, -7.96594502e-01, -4.59043972e-01, -6.42988446e-01,
       -7.26131135e-02,  7.44132480e-02,  6.94941056e-01,  9.51740234e-01,
        6.48753668e-01,  4.49631002e-01,  3.71649640e-03,  7.30278962e-01,
        1.12914875e+00,  1.16650858e+00,  1.23480692e+00,  5.83907657e-01,
        1.38907776e+00,  1.52829337e+00,  9.52579344e-01,  1.01421350e+00,
        1.15012193e+00,  7.17718504e-01,  1.39925644e+00,  1.31333273e+00,
        1.79344256e+00,  2.01226468e+00,  2.58874602e+00,  2.85045947e+00,
        2.64466404e+00,  2.96298794e+00,  2.51669938e+00,  2.35339362e+00,
        2.45597484e+00,  2.01947890e+00,  2.01274710e+00,  1.86651507e+00,
        1.98853918e+00,  2.31845049e+00,  1.60219431e+00,  1.21087267e+00,
        5.34002952e-01,  4.61602529e-01,  6.75507720e-01,  8.65004027e-01,
        1.29450560e+00,  9.44260538e-01,  1.24908618e+00,  1.44291626e+00,
        9.73370094e-01,  9.44063052e-01,  4.60672150e-02, -3.83230003e-01,
       -7.12202754e-02,  2.44172347e-01,  4.75025356e-01,  7.16419343e-01,
        2.39464557e-01,  3.93521933e-01,  4.71854140e-01,  7.87573115e-01,
        9.13669109e-01,  1.15144593e+00,  1.21554160e+00,  5.72091960e-01,
        9.65225875e-01,  1.48644609e+00,  1.36379272e+00,  1.35386403e+00,
        1.88939360e+00,  1.13924922e+00,  2.09110468e+00,  2.16586463e+00,
        2.01219341e+00,  1.88108596e+00,  1.39551743e+00,  1.43267786e+00,
        1.44675997e+00,  1.04459909e+00,  5.51938496e-01,  1.01108331e+00,
        7.33203783e-01,  3.13292708e-01,  8.39715656e-01,  6.85248289e-01,
       -4.23958834e-01,  1.47905450e-01,  3.81944465e-01,  7.79773029e-01,
        1.10881865e+00,  1.17584800e+00,  1.94435044e+00,  2.03360514e+00,
        1.32334135e+00,  1.57242460e+00,  2.17598852e+00,  2.05928494e+00,
        2.33408928e+00,  2.82318014e+00,  2.48486039e+00,  2.22492169e+00,
        1.65126849e+00,  9.79721630e-01,  1.72818479e+00,  1.32264332e+00,
        7.47572966e-01,  5.47497637e-01,  3.77311961e-01,  2.13304500e-01,
        2.05293921e-01,  3.91029540e-01, -2.20278883e-01, -9.32286908e-01,
       -6.90688929e-01, -2.35151454e-01, -7.89349757e-01, -4.69786497e-01,
        3.78234737e-02,  2.91139651e-01,  1.21714871e+00,  9.81959368e-01,
        1.20646660e+00,  1.70430547e+00,  2.21204535e+00,  2.02913380e+00,
        1.28514842e+00,  1.59338465e+00,  1.37632183e+00,  1.34884603e+00,
        1.53996471e+00,  1.46458618e+00,  1.37882849e+00,  6.75594520e-01,
        6.94946729e-01,  1.06272558e+00,  6.56429160e-01,  1.23660153e+00,
        4.03350956e-01,  1.06323595e+00,  8.65124959e-01,  8.58509101e-01,
        7.95253324e-01,  6.29158305e-01,  6.44509373e-01,  5.73670451e-01,
        1.58043788e+00,  2.00550106e+00,  1.52346169e+00,  1.47417857e+00,
        1.51764392e+00,  1.58004201e+00,  2.22889149e+00,  2.26402336e+00,
        2.61905334e+00,  2.01173634e+00,  1.83880661e+00,  2.09365580e+00,
        2.14484564e+00,  1.71993335e+00,  1.87918103e+00,  1.45152362e+00,
        8.06477839e-01,  3.01066253e-01, -7.66534192e-02,  1.66887564e-01,
        2.54369126e-01,  3.46097178e-01,  9.32550637e-01,  1.41214650e+00,
        1.95175574e+00,  1.49921132e+00,  1.55350172e+00,  1.47426482e+00,

In [2]:
window_zscores = {'subject': [], 'gpt_layers': [], 'WER':[],'BLEU':[], 'METEOR':[], 'BERT':[]}

for j in ["default", "gpt_layers_3_5_7_9"]:
    for subject in [1,2,3]:
        for task in ['wheretheressmoke']:
            scores = np.load(f'scores/S{subject}/perceived_speech/{j}/{task}.npz', allow_pickle=True)['window_zscores'].item()
            # print(scores['window_zscores'].item())
            window_zscores['subject'].append(subject)
            window_zscores['gpt_layers'].append(j)
            window_zscores['WER'].append(scores[(task, 'WER')])
            window_zscores['BLEU'].append(scores[(task, 'BLEU')])
            window_zscores['METEOR'].append(scores[(task, 'METEOR')])
            window_zscores['BERT'].append(scores[(task, 'BERT')])

window_zscores.keys()

dict_keys(['subject', 'gpt_layers', 'WER', 'BLEU', 'METEOR', 'BERT'])

In [3]:
results_df = pd.DataFrame(window_zscores)

print(len(results_df.loc[0, 'WER']))
print(len(results_df.loc[1, 'WER']))
print(len(results_df.loc[2, 'WER']))
print('=')
print(563*3)
m=1689

from scipy.stats import norm
#convert to p val
results_df['WER'] = results_df['WER'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1-norm.cdf(z) for z in l])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1-norm.cdf(z) for z in l])
#sort
for i in range(3):
    for met in ['WER','BLEU','METEOR','BERT']:
        results_df.loc[i,met].sort()
# to q and check threshold
def p_to_q(p, i):
    return p*m/i
results_df['WER'] = results_df['WER'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BLEU'] = results_df['BLEU'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['METEOR'] = results_df['METEOR'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])
results_df['BERT'] = results_df['BERT'].apply(lambda l : [1 if p_to_q(l[i-1], i) < 0.05 else 0 for i in range(1, len(l)+1)])

# S1=np.array(results_df.loc[0, 'BERT'] + results_df.loc[1, 'BERT'] + results_df.loc[2, 'BERT']).mean()
# S2=np.array(results_df.loc[3, 'BERT'] + results_df.loc[4, 'BERT'] + results_df.loc[5, 'BERT']).mean()
# S3=np.array(results_df.loc[6, 'BERT'] + results_df.loc[7, 'BERT'] + results_df.loc[8, 'BERT']).mean()
# print(S1,S2,S3,'BERT')

results_df

563
563
563
=
1689

,subject,gpt_layers,WER,BLEU,METEOR,BERT
0,1,default,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,default,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,3,default,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,1,gpt_layers_3_5_7_9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,2,gpt_layers_3_5_7_9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,3,gpt_layers_3_5_7_9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [4]:
results_df

,subject,gpt_layers,WER,BLEU,METEOR,BERT
0,1,default,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,default,"[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,3,default,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,1,gpt_layers_3_5_7_9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,2,gpt_layers_3_5_7_9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,3,gpt_layers_3_5_7_9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [5]:
# S1=np.array(results_df.loc[0, 'BERT']).mean()
# S2=np.array(results_df.loc[1, 'BERT']).mean()
# S3=np.array(results_df.loc[2, 'BERT']).mean()
# to_file = pd.DataFrame({'subject':[1,2,3], 'significantly_decoded': [S1,S2,S3]})
tocsv = results_df.drop(columns=['WER', 'BLEU', 'METEOR'])

tocsv['BERT'] = tocsv['BERT'].apply(lambda x : x.count(1)/len(x))

tocsv.to_csv('perceived_speech_sig_decoded.csv', index=False)

tocsv

   subject          gpt_layers      BERT
0        1             default  0.619893
1        2             default  0.642984
2        3             default  0.808171
3        1  gpt_layers_3_5_7_9  0.618117
4        2  gpt_layers_3_5_7_9  0.539964
5        3  gpt_layers_3_5_7_9  0.758437

In [6]:
results = np.load('results/S1/perceived_speech/wheretheressmoke.npz', allow_pickle=True)
result_names = results.files
result_files={}
for name in result_names:
    result_files[name] = results[name]
result_files

FileNotFoundError: [Errno 2] No such file or directory: 'results/S1/perceived_speech/wheretheressmoke.npz'